import { execa } from 'execa';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { gitSshCommand, sshArgs } from '../sandboxes/openssh.ts';
import { createGithubAppClient, decodeGithubPrivateKey, publishVerifiedCommit, type GithubAppClient } from './app.ts';
import { collectGithubFileChanges } from './git-changes.ts';

const repoPath = '/opt/linear-agent-template/repository';
const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const semanticTitle = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z0-9][a-z0-9-]*\))?!?: .+/;
const linearIssue = /^[A-Z][A-Z0-9]*-[1-9][0-9]*$/;

export interface PublishOptions {
	vm: string;
	host?: string;
	previewUrl?: string;
	issue?: string;
}

function requireEnv(name: string): string {
	const value = process.env[name];
	if (!value) throw new Error(`${name} is required`);
	return value;
}

async function vmGit(keyPath: string, host: string, args: readonly string[]): Promise<string> {
	return (await execa('ssh', sshArgs(keyPath, host, ['git', '-C', repoPath, ...args]))).stdout.trim();
}

function characterSlice(value: string, length: number): string {
	return [...value].slice(0, length).join('');
}

function buildTitle(subject: string): string {
	const normalized = subject.replace(/\s+/g, ' ').trim();
	if ([...normalized].length <= 120 && semanticTitle.test(normalized)) return normalized;
	const fallback = normalized || 'implement Linear request';
	return `fix: ${characterSlice(fallback[0].toLowerCase() + fallback.slice(1), 110)}`;
}

function buildBranch(vm: string, issue?: string): string {
	const slug = (issue || 'linear')
		.toLowerCase()
		.replace(/[^a-z0-9-]+/g, '-')
		.replace(/^-+|-+$/g, '');
	return `linear/${characterSlice(slug || 'issue', 40)}-${vm}`;
}

function buildBody(commitMessages: string, previewUrl?: string, issue?: string): string {
	const sections = ['## What changed', '', commitMessages, ''];
	if (previewUrl) {
		sections.push(
			'## Preview',
			'',
			`[Open the Lightdash preview](${previewUrl})`,
			'',
			'Login: `demo@lightdash.com` / `demo_password!`',
			'',
		);
	}
	if (issue) {
		const normalizedIssue = issue.toUpperCase();
		if (linearIssue.test(normalizedIssue)) {
			sections.push('## References', '', `Closes: ${normalizedIssue}`, '');
		} else {
			console.error(`WARN: issue '${issue}' is invalid — skipping Closes line`);
		}
	}
	sections.push('> Generated by the Lightdash Linear agent. Review and test before merging.');
	return `${sections.join('\n')}\n`;
}

let appClient: GithubAppClient | undefined;
let appValidation: Promise<void> | undefined;

function github(): GithubAppClient {
	if (!appClient) {
		appClient = createGithubAppClient({
			appId: requireEnv('GITHUB_APP_ID'),
			installationId: requireEnv('GITHUB_APP_INSTALLATION_ID'),
			privateKey: decodeGithubPrivateKey(requireEnv('GITHUB_APP_PRIVATE_KEY')),
			repository: process.env.GITHUB_REPOSITORY ?? 'lightdash/lightdash',
		});
	}
	return appClient;
}

async function validatedGithub(): Promise<GithubAppClient> {
	const client = github();
	appValidation ??= client.validateRepositoryAccess();
	try {
		await appValidation;
	} catch (error) {
		appValidation = undefined;
		throw error;
	}
	return client;
}

export async function publishPullRequest({
	vm,
	host = `${vm}.exe.xyz`,
	previewUrl,
	issue,
}: PublishOptions): Promise<string> {
	const keyPath = requireEnv('EXE_SSH_KEY');
	const repository = process.env.GITHUB_REPOSITORY ?? 'lightdash/lightdash';
	const baseRef = process.env.GITHUB_BASE_REF ?? 'main';

	console.error(`=== inspect sandbox repo on ${vm} ===`);
	const headSha = await vmGit(keyPath, host, ['rev-parse', 'HEAD']);
	const baseSha = await vmGit(keyPath, host, ['merge-base', 'HEAD', `origin/${baseRef}`]);
	if (headSha === baseSha) throw new Error('Nothing to publish: no commits beyond base branch');
	if (await vmGit(keyPath, host, ['status', '--porcelain'])) {
		console.error('WARN: sandbox tree is dirty — only committed work is published');
	}

	const subject = await vmGit(keyPath, host, ['log', '-1', '--format=%s']);
	const title = buildTitle(subject);
	const branch = buildBranch(vm, issue);
	const commitMessages = await vmGit(keyPath, host, ['log', '--reverse', '--format=- %s%n%n%b', `${baseSha}..HEAD`]);
	const body = buildBody(commitMessages, previewUrl, issue);
	const tempDir = await mkdtemp(join(tmpdir(), 'linear-agent-publish-'));
	const bareRepo = join(tempDir, 'repo.git');

	try {
		console.error('=== fetch sandbox commits ===');
		await execa('git', ['init', '-q', '--bare', bareRepo]);
		const checkout = (
			await execa('git', ['rev-parse', '--show-toplevel'], {
				cwd: packageDir,
			})
		).stdout.trim();
		await execa('git', [
			'-C',
			bareRepo,
			'fetch',
			'-q',
			pathToFileURL(checkout).href,
			`+refs/heads/${baseRef}:refs/heads/seed`,
		]);
		await execa(
			'git',
			['-C', bareRepo, 'fetch', '--update-shallow', '-q', `ssh://exedev@${host}${repoPath}`, 'HEAD'],
			{
				env: {
					...process.env,
					GIT_SSH_COMMAND: gitSshCommand(keyPath),
				},
			},
		);
		const fetched = (
			await execa('git', ['-C', bareRepo, 'rev-parse', '--verify', 'FETCH_HEAD^{commit}'])
		).stdout.trim();
		if (fetched !== headSha) throw new Error(`VM HEAD moved during publish (${headSha} → ${fetched})`);

		const client = await validatedGithub();
		const fileChanges = await collectGithubFileChanges(bareRepo, baseSha, headSha);
		await publishVerifiedCommit({
			client,
			repository,
			branch,
			baseCommit: baseSha,
			headline: title,
			fileChanges,
			stagingLabel: `${issue ?? 'linear'}-${vm}`,
		});

		console.error('=== open or update draft PR ===');
		const owner = repository.split('/')[0] as string;
		const existing = await client.request<Array<{ number?: number }>>(
			`/repos/${repository}/pulls?head=${owner}:${encodeURIComponent(branch)}&state=open`,
		);
		const existingNumber = existing[0]?.number;
		if (existingNumber) {
			await client.request(`/repos/${repository}/pulls/${existingNumber}`, {
				method: 'PATCH',
				body: { title, body },
			});
			return `https://github.com/${repository}/pull/${existingNumber}`;
		}

		const pull = await client.request<{ html_url?: string }>(`/repos/${repository}/pulls`, {
			method: 'POST',
			body: { title, head: branch, base: baseRef, body, draft: true },
		});
		if (!pull.html_url) throw new Error('GitHub did not return the pull request URL');
		return pull.html_url;
	} finally {
		await rm(tempDir, { recursive: true, force: true });
	}
}
