import { CatalogType, Explore, FieldType } from '@lightdash/common';
import { DbCatalog } from '../../../database/entities/catalog';
import { parseCatalog } from './parser';

// Helper to create a minimal DbCatalog entry for testing
const createDbCatalog = (
    overrides: Partial<DbCatalog> &
        Pick<DbCatalog, 'name' | 'table_name' | 'type'>,
): DbCatalog => ({
    cached_explore_uuid: 'uuid-1',
    project_uuid: 'project-1',
    description: null,
    field_type: undefined,
    required_attributes: null,
    chart_usage: 0,
    catalog_search_uuid: 'catalog-1',
    icon: null,
    label: null,
    search_vector: '',
    spotlight_show: true,
    yaml_tags: null,
    ai_hints: null,
    joined_tables: null,
    ...overrides,
});

// Minimal mock explore factory
const createMockExplore = (
    name: string,
    baseTable: string,
    tables: Record<
        string,
        { dimensions: string[]; metrics: string[]; hidden?: boolean }
    >,
): Explore =>
    ({
        name,
        baseTable,
        label: name,
        tags: [],
        tables: Object.fromEntries(
            Object.entries(tables).map(
                ([tableName, { dimensions, metrics }]) => [
                    tableName,
                    {
                        name: tableName,
                        label: tableName,
                        database: 'test',
                        schema: 'test',
                        sqlTable: tableName,
                        dimensions: Object.fromEntries(
                            dimensions.map((d) => [
                                d,
                                {
                                    name: d,
                                    label: d,
                                    table: tableName,
                                    tableLabel: tableName,
                                    fieldType: FieldType.DIMENSION,
                                    type: 'string',
                                    sql: `\${TABLE}.${d}`,
                                    compiledSql: `"${tableName}".${d}`,
                                    hidden: false,
                                    tablesReferences: [tableName],
                                },
                            ]),
                        ),
                        metrics: Object.fromEntries(
                            metrics.map((m) => [
                                m,
                                {
                                    name: m,
                                    label: m,
                                    table: tableName,
                                    tableLabel: tableName,
                                    fieldType: FieldType.METRIC,
                                    type: 'number',
                                    sql: `COUNT(*)`,
                                    compiledSql: `COUNT(*)`,
                                    hidden: false,
                                    tablesReferences: [tableName],
                                    isAutoGenerated: false,
                                },
                            ]),
                        ),
                    },
                ],
            ),
        ),
    } as unknown as Explore);

describe('parseCatalog', () => {
    describe('when same table appears in multiple explores with different fields', () => {
        // This test reproduces a bug where:
        // - "users" explore has "users" as base table with metric "total_orders"
        // - "events" explore has "users" as joined table with only "user_id" dimension
        // The catalog entry for "total_orders" should use the correct explore

        const usersExplore = createMockExplore('users', 'users', {
            users: {
                dimensions: ['user_id', 'name', 'email'],
                metrics: ['total_orders', 'total_sessions'],
            },
        });

        const eventsExplore = createMockExplore('events', 'events', {
            events: {
                dimensions: ['event_id', 'user_id'],
                metrics: ['total_events'],
            },
            // Same table name but with fewer fields (joined table)
            users: {
                dimensions: ['user_id', 'name'],
                metrics: [], // No metrics exposed in this join!
            },
        });

        it('should return the field when using the correct explore', () => {
            const result = parseCatalog({
                ...createDbCatalog({
                    name: 'total_orders',
                    table_name: 'users',
                    type: CatalogType.Field,
                    field_type: FieldType.METRIC,
                    description: 'Total number of orders',
                    label: 'Total Orders',
                }),
                explore: usersExplore, // Correct explore
                catalog_tags: [],
                search_rank: 1,
            });

            expect(result).not.toBeNull();
            expect(result?.type).toBe(CatalogType.Field);
            if (result?.type === CatalogType.Field) {
                expect(result.name).toBe('total_orders');
            }
        });

        it('should return null when field does not exist in the wrong explore', () => {
            // This simulates the bug: catalog entry is for "total_orders"
            // but we're using the wrong explore (events) which doesn't have this metric
            const result = parseCatalog({
                ...createDbCatalog({
                    name: 'total_orders',
                    table_name: 'users',
                    type: CatalogType.Field,
                    field_type: FieldType.METRIC,
                    description: 'Total number of orders',
                    label: 'Total Orders',
                }),
                explore: eventsExplore, // Wrong explore!
                catalog_tags: [],
                search_rank: 1,
            });

            // With the fix, this returns null instead of throwing
            expect(result).toBeNull();
        });

        it('should return null when table does not exist in explore', () => {
            const result = parseCatalog({
                ...createDbCatalog({
                    name: 'some_field',
                    table_name: 'non_existent_table',
                    type: CatalogType.Field,
                    field_type: FieldType.DIMENSION,
                    description: 'Some field',
                    label: 'Some Field',
                }),
                explore: usersExplore,
                catalog_tags: [],
                search_rank: 1,
            });

            expect(result).toBeNull();
        });
    });
});
