import { type REST_OPERATION_CAPABILITIES } from './capabilityMap';

export const HUMAN_ONLY_IN_MANAGED: ReadonlySet<string> = new Set<
    keyof typeof REST_OPERATION_CAPABILITIES
>([
    'AgentPermissionController.applyPilotPreset',
    'AgentPermissionController.confirmWarehouse',
    'AgentPermissionController.deleteWarehouseConfirmation',
    'AgentPermissionController.resetToLegacy',
    'AgentPermissionController.saveCeiling',
    'AiServiceAccountController.delete',
    'AiServiceAccountController.upsert',
    'CustomRolesController.addScopesToRole',
    'CustomRolesController.createOrganizationRole',
    'CustomRolesController.deleteOrganizationRole',
    'CustomRolesController.removeScopeFromRole',
    'CustomRolesController.updateOrganizationRole',
    'DirectAccessController.resetDirectAccessAssignments',
    'DirectAccessController.revokeDirectAccessAssignment',
    'DirectAccessController.upsertDirectAccessAssignment',
    'GroupsController.addProjectAccessToGroup',
    'GroupsController.addUserToGroup',
    'GroupsController.deleteGroup',
    'GroupsController.removeProjectAccessFromGroup',
    'GroupsController.removeUserFromGroup',
    'GroupsController.updateGroup',
    'GroupsController.updateProjectAccessForGroup',
    'InviteLinksController.createInviteLink',
    'OrganizationAgentIdentityController.saveSnowflakeAgentClient',
    'OrganizationAgentIdentityController.updateRule',
    'OrganizationAgentIdentityController.updateSettings',
    'OrganizationCoderController.legacyUpsertCustomRoleAsCode',
    'OrganizationCoderController.legacyUpsertGroupAsCode',
    'OrganizationCoderController.legacyUpsertUserAsCode',
    'OrganizationCoderController.upsertCustomRoleAsCode',
    'OrganizationCoderController.upsertGroupAsCode',
    'OrganizationCoderController.upsertUserAsCode',
    'OrganizationController.createGroup',
    'OrganizationController.deleteUser',
    'OrganizationController.updateOrganizationMember',
    'OrganizationRolesController.duplicateRole',
    'OrganizationRolesController.replaceOrganizationUserRoleSet',
    'OrganizationRolesController.upsertOrganizationUserRoleAssignment',
    'OrganizationSettingsController.updateOrganizationSettings',
    'ProjectController.grantProjectAccessToUser',
    'ProjectController.revokeProjectAccessForUser',
    'ProjectController.updateAgentSqlScope',
    'ProjectController.updateProjectAccessForUser',
    'ProjectRolesController.deleteProjectGroupRoleAssignment',
    'ProjectRolesController.deleteProjectUserRoleAssignment',
    'ProjectRolesController.replaceProjectGroupRoleSet',
    'ProjectRolesController.replaceProjectUserRoleSet',
    'ProjectRolesController.updateProjectGroupRoleAssignment',
    'ProjectRolesController.upsertProjectGroupRoleAssignment',
    'ProjectRolesController.upsertProjectUserRoleAssignment',
    'ScimOrganizationAccessTokenController.rotateOrganizationAccessToken',
    'ServiceAccountsController.rotateServiceAccount',
    'ServiceAccountsController.updateServiceAccount',
    'SpaceController.addSpaceGroupAccess',
    'SpaceController.addSpaceUserAccess',
    'SpaceController.createSpace',
    'SpaceController.revokeGroupSpaceAccess',
    'SpaceController.revokeSpaceAccessForUser',
    'UserController.createPersonalAccessToken',
    'UserController.joinOrganization',
    'UserController.rotatePersonalAccessToken',
    'oauthRouter DELETE /clients/:clientId',
    'oauthRouter PATCH /clients/:clientId',
    'oauthRouter POST /clients',
]);
