import {
    AI_IDENTITY_NAME_PLACEHOLDER,
    fillAiTwinName,
    SNOWFLAKE_LOGIN_PLACEHOLDER,
    type AiIdentity,
} from '../types/aiIdentity';
import { ParameterError } from '../types/errors';

const quoteIdentifier = (value: string): string =>
    /^[A-Za-z_][A-Za-z0-9_$]*$/.test(value)
        ? value
        : `"${value.replace(/"/g, '""')}"`;

const quoteString = (value: string): string =>
    `'${value.replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;

export const validateAiIdentityRoleTemplate = (template: string): void => {
    const filled = fillAiTwinName(template, 'LOGIN')
        .split(AI_IDENTITY_NAME_PLACEHOLDER)
        .join('IDENTITY');
    if (!/^[A-Za-z0-9_$]+$/.test(filled)) {
        throw new ParameterError(
            'Invalid Snowflake role template. Use letters, digits, _ and $ or {snowflake_login} or {ai_identity_name}.',
        );
    }
};

export const resolveAiIdentityRole = (
    template: string | null,
    snowflakeLogin: string | null,
    aiIdentityName: string | null = null,
): string | null => {
    if (template === null) return null;
    validateAiIdentityRoleTemplate(template);
    if (
        template.includes(SNOWFLAKE_LOGIN_PLACEHOLDER) &&
        snowflakeLogin === null
    ) {
        throw new ParameterError(
            'A Snowflake sign-in is required to fill the role template.',
        );
    }
    if (
        template.includes(AI_IDENTITY_NAME_PLACEHOLDER) &&
        aiIdentityName === null
    ) {
        throw new ParameterError(
            'An AI identity name is required to fill the role template.',
        );
    }
    const role = fillAiTwinName(template, snowflakeLogin ?? '')
        .split(AI_IDENTITY_NAME_PLACEHOLDER)
        .join(aiIdentityName ?? '');
    if (!/^[A-Za-z0-9_$]+$/.test(role)) {
        throw new ParameterError(
            'Invalid Snowflake role after filling the template. Use letters, digits, _ and $.',
        );
    }
    return role;
};

export const buildAiTwinProvisioningSql = ({
    identities,
    roleForTwin,
    skipped = [],
}: {
    identities: AiIdentity[];
    roleForTwin: string | null;
    skipped?: { email: string; reason: string }[];
}): string => {
    if (roleForTwin !== null) validateAiIdentityRoleTemplate(roleForTwin);
    return [
        `-- Generated by Lightdash on ${new Date().toISOString()}. Public keys only; Lightdash keeps the private keys.`,
        ...skipped.map(
            ({ email, reason }) =>
                `-- Skipped ${email.replace(/[\r\n]/g, ' ')}: ${reason.replace(/[\r\n]/g, ' ')}`,
        ),
        ...(roleForTwin === null
            ? [
                  '-- Roles are not granted by this script. Your automation grants each AI identity its role.',
              ]
            : []),
        ...identities.flatMap((identity) => {
            if (identity.twinName === null || identity.publicKey === null) {
                return [
                    `-- ${identity.email.replace(/[\r\n]/g, ' ')}: needs Snowflake sign-in`,
                ];
            }
            const user = quoteIdentifier(identity.twinName);
            const resolvedRole = resolveAiIdentityRole(
                roleForTwin,
                identity.snowflakeLogin,
                identity.twinName,
            );
            const role =
                resolvedRole === null ? null : quoteIdentifier(resolvedRole);
            return [
                `CREATE USER IF NOT EXISTS ${user} TYPE = SERVICE_AGENT RSA_PUBLIC_KEY = ${quoteString(identity.publicKey)}${role === null ? '' : ` DEFAULT_ROLE = ${role}`} COMMENT = ${quoteString(`Lightdash AI user for ${identity.email}`)};`,
                `ALTER USER ${user} SET RSA_PUBLIC_KEY = ${quoteString(identity.publicKey)};`,
                ...(role === null
                    ? []
                    : [
                          `ALTER USER ${user} SET DEFAULT_ROLE = ${role};`,
                          `GRANT ROLE ${role} TO USER ${user};`,
                      ]),
            ];
        }),
    ].join('\n');
};
