name: F5. Filter an intermediate table calculation
description: ""
tableName: orders
updatedAt: "2025-08-27T16:49:35.984Z"
metricQuery:
  exploreName: orders
  dimensions:
    - orders_shipping_method
    - orders_order_id
  metrics:
    - orders_total_order_amount
  filters:
    tableCalculations:
      id: 8b0a93c5-773b-4b0f-9eef-690098f6b655
      and:
        - id: c77606b9-26dd-4c18-8e07-80c127eac511
          target:
            fieldId: percentage_of_shipping_method_order_total
          values:
            - 0.05
          operator: greaterThan
  sorts:
    - fieldId: orders_total_order_amount
      descending: true
  limit: 500
  metricOverrides: {}
  tableCalculations:
    - name: order_total_by_shipping_method
      displayName: Order total by shipping method
      sql: >-
        sum(${orders.total_order_amount}) over(partition by
        ${orders.shipping_method})
      format:
        type: default
        separator: default
      type: number
    - name: percentage_of_shipping_method_order_total
      displayName: percentage_of_shipping_method_order_total
      sql: ${orders.total_order_amount}/${order_total_by_shipping_method}
      format:
        type: percent
        separator: default
      type: number
    - name: total_percentage_per_shipping_method
      displayName: total percentage per shipping method
      sql: >-
        sum(${percentage_of_shipping_method_order_total}) over(partition by
        ${orders.shipping_method})
      format:
        type: percent
        separator: default
      type: number
  additionalMetrics:
    - name: amount_sum_of_amount
      label: Sum of Amount
      description: "Sum of Amount on the table Orders "
      uuid: 3c5b5649-677f-4ea5-9c14-8fc446131f73
      sql: ${TABLE}.amount
      table: orders
      type: sum
      baseDimensionName: amount
      formatOptions:
        type: default
        separator: default
  customDimensions: []
chartConfig:
  type: table
  config:
    columns: {}
    metricsAsRows: false
    showSubtotals: false
    hideRowNumbers: false
    showTableNames: true
    showResultsTotal: false
    showRowCalculation: false
    showColumnCalculation: false
    conditionalFormattings: []
dashboardSlug: table-calculation-examples
slug: f6-filter-an-intermediate-table-calculation
tableConfig:
  columnOrder:
    - orders_shipping_method
    - orders_order_id
    - orders_total_order_amount
    - order_total_by_shipping_method
    - percentage_of_shipping_method_order_total
    - total_percentage_per_shipping_method
spaceSlug: parent-space-3
version: 1
downloadedAt: "2025-08-27T17:49:38.467Z"
