import { DimensionType, FieldType, PivotData } from '@lightdash/common';

const DIMENSIONS_DUMMY_DATA: PivotData['dimensions'] = {
    // customers
    customers_created: {
        sql: '${TABLE}.created',
        name: 'created',
        type: DimensionType.TIMESTAMP,
        index: 3,
        label: 'Created',
        table: 'customers',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Timestamp (UTC) when customer was created',
    },
    customers_last_name: {
        sql: '${TABLE}.last_name',
        name: 'last_name',
        type: DimensionType.STRING,
        index: 2,
        label: 'Last name',
        table: 'customers',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: "Customer's last name. PII.",
    },
    customers_first_name: {
        sql: '${TABLE}.first_name',
        name: 'first_name',
        type: DimensionType.STRING,
        urls: [
            {
                url: 'https://example.com/company/${value.formatted | url_encode }',
                label: 'URL from value',
            },
            {
                url: 'https://example.com/company/${row.customers.customer_id.raw | url_encode }',
                label: 'URL from row value',
            },
            {
                url: 'https://example.com/company/${row.customer_id.raw | url_encode }',
                label: 'Invalid URL with bad reference',
            },
        ],
        index: 1,
        label: 'First name',
        table: 'customers',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: "Customer's first name. PII.",
    },
    customers_created_DAY: {
        sql: "DATE_TRUNC('DAY', ${TABLE}.created)",
        name: 'created_day',
        type: DimensionType.DATE,
        group: 'created',
        index: 3,
        label: 'Created day',
        table: 'customers',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Timestamp (UTC) when customer was created',
    },
    customers_created_RAW: {
        sql: '${TABLE}.created',
        name: 'created_raw',
        type: DimensionType.TIMESTAMP,
        group: 'created',
        index: 3,
        label: 'Created raw',
        table: 'customers',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Timestamp (UTC) when customer was created',
    },
    customers_customer_id: {
        sql: '${TABLE}.customer_id',
        name: 'customer_id',
        type: DimensionType.NUMBER,
        index: 0,
        label: 'Customer id',
        table: 'customers',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'This is a unique identifier for a customer',
    },
    customers_first_order: {
        sql: '${TABLE}.first_order',
        name: 'first_order',
        type: DimensionType.DATE,
        index: 4,
        label: 'First order',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Date of the customers first order',
    },
    customers_created_WEEK: {
        sql: "DATE_TRUNC('WEEK', ${TABLE}.created)",
        name: 'created_week',
        type: DimensionType.DATE,
        group: 'created',
        index: 3,
        label: 'Created week',
        table: 'customers',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Timestamp (UTC) when customer was created',
    },
    customers_created_YEAR: {
        sql: "DATE_TRUNC('YEAR', ${TABLE}.created)",
        name: 'created_year',
        type: DimensionType.DATE,
        group: 'created',
        index: 3,
        label: 'Created year',
        table: 'customers',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Timestamp (UTC) when customer was created',
    },
    customers_created_MONTH: {
        sql: "DATE_TRUNC('MONTH', ${TABLE}.created)",
        name: 'created_month',
        type: DimensionType.DATE,
        group: 'created',
        index: 3,
        label: 'Created month',
        table: 'customers',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Timestamp (UTC) when customer was created',
    },
    customers_created_QUARTER: {
        sql: "DATE_TRUNC('QUARTER', ${TABLE}.created)",
        name: 'created_quarter',
        type: DimensionType.DATE,
        group: 'created',
        index: 3,
        label: 'Created quarter',
        table: 'customers',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Timestamp (UTC) when customer was created',
    },
    customers_first_order_DAY: {
        sql: "DATE_TRUNC('DAY', ${TABLE}.first_order)",
        name: 'first_order_day',
        type: DimensionType.DATE,
        group: 'first_order',
        index: 4,
        label: 'First order day',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Date of the customers first order',
    },
    customers_first_order_WEEK: {
        sql: "DATE_TRUNC('WEEK', ${TABLE}.first_order)",
        name: 'first_order_week',
        type: DimensionType.DATE,
        group: 'first_order',
        index: 4,
        label: 'First order week',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Date of the customers first order',
    },
    customers_first_order_YEAR: {
        sql: "DATE_TRUNC('YEAR', ${TABLE}.first_order)",
        name: 'first_order_year',
        type: DimensionType.DATE,
        group: 'first_order',
        index: 4,
        label: 'First order year',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Date of the customers first order',
    },
    customers_number_of_orders: {
        sql: '${TABLE}.number_of_orders',
        name: 'number_of_orders',
        type: DimensionType.NUMBER,
        index: 8,
        label: 'Number of orders',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: '',
    },
    customers_first_order_MONTH: {
        sql: "DATE_TRUNC('MONTH', ${TABLE}.first_order)",
        name: 'first_order_month',
        type: DimensionType.DATE,
        group: 'first_order',
        index: 4,
        label: 'First order month',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Date of the customers first order',
    },
    customers_most_recent_order: {
        sql: '${TABLE}.most_recent_order',
        name: 'most_recent_order',
        type: DimensionType.DATE,
        index: 5,
        label: 'Most recent order',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Date of the customers most recent order',
    },
    customers_days_since_last_order: {
        sql: '${TABLE}.days_since_last_order',
        name: 'days_since_last_order',
        type: DimensionType.NUMBER,
        index: 6,
        label: 'Days since last order',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Number of days since the customers last order',
    },
    customers_most_recent_order_DAY: {
        sql: "DATE_TRUNC('DAY', ${TABLE}.most_recent_order)",
        name: 'most_recent_order_day',
        type: DimensionType.DATE,
        group: 'most_recent_order',
        index: 5,
        label: 'Most recent order day',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Date of the customers most recent order',
    },
    customers_most_recent_order_WEEK: {
        sql: "DATE_TRUNC('WEEK', ${TABLE}.most_recent_order)",
        name: 'most_recent_order_week',
        type: DimensionType.DATE,
        group: 'most_recent_order',
        index: 5,
        label: 'Most recent order week',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Date of the customers most recent order',
    },
    customers_most_recent_order_YEAR: {
        sql: "DATE_TRUNC('YEAR', ${TABLE}.most_recent_order)",
        name: 'most_recent_order_year',
        type: DimensionType.DATE,
        group: 'most_recent_order',
        index: 5,
        label: 'Most recent order year',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Date of the customers most recent order',
    },
    customers_customer_lifetime_value: {
        sql: '${TABLE}.customer_lifetime_value',
        name: 'customer_lifetime_value',
        type: DimensionType.NUMBER,
        index: 9,
        label: 'Customer lifetime value',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: '',
    },
    customers_most_recent_order_MONTH: {
        sql: "DATE_TRUNC('MONTH', ${TABLE}.most_recent_order)",
        name: 'most_recent_order_month',
        type: DimensionType.DATE,
        group: 'most_recent_order',
        index: 5,
        label: 'Most recent order month',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description: 'Date of the customers most recent order',
    },
    customers_days_between_created_and_first_order: {
        sql: '${TABLE}.days_between_created_and_first_order',
        name: 'days_between_created_and_first_order',
        type: DimensionType.NUMBER,
        index: 7,
        label: 'Days between created and first order',
        table: 'customers',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Customers',
        description:
            'Number of days between the customer being created and making their first order',
    },

    // orders table
    orders_amount: {
        sql: '${TABLE}.amount',
        name: 'amount',
        type: DimensionType.NUMBER,
        index: 5,
        label: 'Amount',
        table: 'orders',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Total amount (USD) of the order',
    },
    orders_status: {
        sql: '${TABLE}.status',
        name: 'status',
        type: DimensionType.STRING,
        index: 4,
        label: 'Status',
        table: 'orders',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description:
            'Orders can be one of the following statuses:\n\n| status         | description                                                                                                            |\n|----------------|------------------------------------------------------------------------------------------------------------------------|\n| placed         | The order has been placed but has not yet left the warehouse                                                           |\n| shipped        | The order has ben shipped to the customer and is currently in transit                                                  |\n| completed      | The order has been received by the customer                                                                            |\n| return_pending | The customer has indicated that they would like to return the order, but it has not yet been received at the warehouse |\n| returned       | The order has been returned by the customer and received at the warehouse                                              |',
    },
    orders_order_id: {
        sql: '${TABLE}.order_id',
        name: 'order_id',
        type: DimensionType.NUMBER,
        index: 0,
        label: 'Order id',
        table: 'orders',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'This is a unique identifier for an order',
    },
    orders_order_date: {
        sql: '${TABLE}.order_date',
        name: 'order_date',
        type: DimensionType.DATE,
        index: 3,
        label: 'Order date',
        table: 'orders',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Date (UTC) that the order was placed',
    },
    orders_customer_id: {
        sql: '${TABLE}.customer_id',
        name: 'customer_id',
        type: DimensionType.NUMBER,
        index: 2,
        label: 'Customer id',
        table: 'orders',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Foreign key to the customers table',
    },
    orders_is_completed: {
        sql: '${TABLE}.is_completed',
        name: 'is_completed',
        type: DimensionType.BOOLEAN,
        index: 1,
        label: 'Is completed',
        table: 'orders',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Boolean indicating if status is completed',
    },
    orders_coupon_amount: {
        sql: '${TABLE}.coupon_amount',
        name: 'coupon_amount',
        type: DimensionType.NUMBER,
        index: 7,
        label: 'Coupon amount',
        table: 'orders',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Amount of the order (AUD) paid for by coupon',
    },
    orders_order_date_DAY: {
        sql: "DATE_TRUNC('DAY', ${TABLE}.order_date)",
        name: 'order_date_day',
        type: DimensionType.DATE,
        group: 'order_date',
        index: 3,
        label: 'Order date day',
        table: 'orders',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Date (UTC) that the order was placed',
    },
    orders_order_date_WEEK: {
        sql: "DATE_TRUNC('WEEK', ${TABLE}.order_date)",
        name: 'order_date_week',
        type: DimensionType.DATE,
        group: 'order_date',
        index: 3,
        label: 'Order date week',
        table: 'orders',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Date (UTC) that the order was placed',
    },
    orders_order_date_YEAR: {
        sql: "DATE_TRUNC('YEAR', ${TABLE}.order_date)",
        name: 'order_date_year',
        type: DimensionType.DATE,
        group: 'order_date',
        index: 3,
        label: 'Order date year',
        table: 'orders',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Date (UTC) that the order was placed',
    },
    orders_gift_card_amount: {
        sql: '${TABLE}.gift_card_amount',
        name: 'gift_card_amount',
        type: DimensionType.NUMBER,
        index: 9,
        label: 'Gift card amount',
        table: 'orders',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Amount of the order (AUD) paid for by gift card',
    },
    orders_order_date_MONTH: {
        sql: "DATE_TRUNC('MONTH', ${TABLE}.order_date)",
        name: 'order_date_month',
        type: DimensionType.DATE,
        group: 'order_date',
        index: 3,
        label: 'Order date month',
        table: 'orders',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Date (UTC) that the order was placed',
    },
    orders_credit_card_amount: {
        sql: '${TABLE}.credit_card_amount',
        name: 'credit_card_amount',
        type: DimensionType.NUMBER,
        index: 6,
        label: 'Credit card amount',
        table: 'orders',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Amount of the order (AUD) paid for by credit card',
    },
    orders_bank_transfer_amount: {
        sql: '${TABLE}.bank_transfer_amount',
        name: 'bank_transfer_amount',
        type: DimensionType.NUMBER,
        index: 8,
        label: 'Bank transfer amount',
        table: 'orders',
        hidden: true,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Orders',
        description: 'Amount of the order (AUD) paid for by bank transfer',
    },

    // payments table
    payments_amount: {
        sql: '${TABLE}.amount',
        name: 'amount',
        type: DimensionType.NUMBER,
        index: 3,
        label: 'Amount',
        table: 'payments',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Payments',
        description: 'Total amount (AUD) of the individual payment',
    },
    payments_order_id: {
        sql: '${TABLE}.order_id',
        name: 'order_id',
        type: DimensionType.NUMBER,
        index: 1,
        label: 'Order id',
        table: 'payments',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Payments',
        description: 'Foreign key to the orders table',
    },
    payments_payment_id: {
        sql: '${TABLE}.payment_id',
        name: 'payment_id',
        type: DimensionType.NUMBER,
        index: 0,
        label: 'Payment id',
        table: 'payments',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Payments',
        description: 'This is a unique identifier for a payment',
    },
    payments_payment_method: {
        sql: '${TABLE}.payment_method',
        name: 'payment_method',
        type: DimensionType.STRING,
        index: 2,
        label: 'Payment method',
        table: 'payments',
        hidden: false,
        fieldType: FieldType.DIMENSION,
        tableLabel: 'Payments',
        description: 'Method of payment used, for example credit card',
    },
};

export { DIMENSIONS_DUMMY_DATA };
