import type { ASTNode } from '../types';
// parser.js is auto-generated by peggy build step
import * as parserModule from '../grammar/parser';

export function parse(formula: string): ASTNode {
    return (parserModule as { parse: (input: string) => ASTNode }).parse(
        formula,
    );
}
