import type { ASTNode } from '../types';

// parser.ts is auto-generated by peggy build step
// eslint-disable-next-line @typescript-eslint/no-var-requires
let parserModule: { parse: (input: string) => ASTNode } | null = null;

function getParser() {
    if (!parserModule) {
        // Dynamic require so the file only needs to exist at runtime after build
        // eslint-disable-next-line @typescript-eslint/no-var-requires, global-require
        parserModule = require('../grammar/parser');
    }
    return parserModule!;
}

export function parse(formula: string): ASTNode {
    return getParser().parse(formula);
}
