import { Button, Card, InputGroup, Intent, Tab, Tabs } from '@blueprintjs/core';
import { CreatePersonalAccessToken, formatTimestamp } from '@lightdash/common';
import React, { FC, useEffect, useState } from 'react';
import CopyToClipboard from 'react-copy-to-clipboard';
import { useForm } from 'react-hook-form';
import useToaster from '../../../hooks/toaster/useToaster';
import { useCreateAccessToken } from '../../../hooks/useAccessToken';
import {
    AccessTokenForm,
    BackButton,
    ExpireDateSelect,
    InvitedCallout,
    InviteFormGroup,
    Panel,
    ShareLinkCallout,
    SubmitButton,
    TokeDescriptionInput,
} from './CreateTokens.styles';

const CreateTokenPanel: FC<{
    onBackClick: () => void;
}> = ({ onBackClick }) => {
    const { showToastSuccess } = useToaster();
    const { data, mutate, isError, isLoading, isSuccess } =
        useCreateAccessToken();

    const [expireDate, setExpireDate] = useState<Date | undefined>();

    const methods = useForm<CreatePersonalAccessToken>({
        mode: 'onSubmit',
    });

    useEffect(() => {
        if (isError) {
            methods.reset({ ...methods.getValues() }, { keepValues: true });
        }
    }, [isError, methods, isSuccess]);

    const handleSubmit = (formData: CreatePersonalAccessToken) => {
        const currentDate = new Date();
        const expiredValue = !!Number(formData?.expiresAt)
            ? new Date(
                  currentDate.setDate(
                      currentDate.getDate() + Number(formData?.expiresAt),
                  ),
              )
            : undefined;
        setExpireDate(expiredValue);

        mutate({
            description: formData.description,
            expiresAt: expiredValue,
            autoGenerated: false,
        });
    };

    const expireOptions = [
        {
            label: 'No expiration',
            value: '',
        },
        {
            label: '7 days',
            value: 7,
        },
        {
            label: '30 days',
            value: 30,
        },
        {
            label: '60 days',
            value: 60,
        },
        {
            label: '90 days',
            value: 90,
        },
    ];

    return (
        <Panel>
            <BackButton
                icon="chevron-left"
                text="Back to all tokens"
                onClick={onBackClick}
            />
            <Card>
                <AccessTokenForm
                    name="generate-token"
                    methods={methods}
                    onSubmit={handleSubmit}
                >
                    <TokeDescriptionInput
                        name="description"
                        label="What’s this token for?"
                        disabled={isLoading}
                        rules={{
                            required: 'Required field',
                        }}
                    />
                    <ExpireDateSelect
                        name="expiresAt"
                        options={expireOptions}
                    />
                    <SubmitButton
                        intent={Intent.PRIMARY}
                        text={'Generate token'}
                        type="submit"
                        disabled={isLoading}
                    />
                </AccessTokenForm>
            </Card>
            {data && (
                <InviteFormGroup labelFor="invite-link-input">
                    {data.token && (
                        <InvitedCallout intent="success">
                            Your token has been generated.
                        </InvitedCallout>
                    )}

                    <ShareLinkCallout intent="primary" icon={null}>
                        <Tabs
                            animate={true}
                            id="CLI"
                            key="vertical"
                            renderActiveTabPanelOnly={true}
                            vertical={false}
                        >
                            <Tab
                                id="rx"
                                title="Europe Users"
                                panel={
                                    <InputGroup
                                        id="invite-link-input"
                                        className="cohere-block"
                                        type="text"
                                        readOnly
                                        value={`lightdash login https://eu1.lightdash.cloud --token ${data.token}`}
                                        rightElement={
                                            <CopyToClipboard
                                                text={`lightdash login https://eu1.lightdash.cloud --token ${data.token}`}
                                                options={{ message: 'Copied' }}
                                                onCopy={() =>
                                                    showToastSuccess({
                                                        title: 'Token copied',
                                                    })
                                                }
                                            >
                                                <Button
                                                    minimal
                                                    icon="clipboard"
                                                />
                                            </CopyToClipboard>
                                        }
                                    />
                                }
                            />
                            <Tab
                                id="ng"
                                title="United State Users"
                                panel={
                                    <InputGroup
                                        id="invite-link-input"
                                        className="cohere-block"
                                        type="text"
                                        readOnly
                                        value={`lightdash login https://app.lightdash.cloud --token ${data.token}`}
                                        rightElement={
                                            <CopyToClipboard
                                                text={`lightdash login https://app.lightdash.cloud --token ${data.token}`}
                                                options={{ message: 'Copied' }}
                                                onCopy={() =>
                                                    showToastSuccess({
                                                        title: 'Token copied',
                                                    })
                                                }
                                            >
                                                <Button
                                                    minimal
                                                    icon="clipboard"
                                                />
                                            </CopyToClipboard>
                                        }
                                    />
                                }
                            />
                        </Tabs>
                    </ShareLinkCallout>

                    <ShareLinkCallout intent="warning">
                        {expireDate &&
                            `This token will expire on
                        ${formatTimestamp(expireDate)} `}
                        Make sure to copy your personal access token now. You
                        won’t be able to see it again!
                    </ShareLinkCallout>
                </InviteFormGroup>
            )}
        </Panel>
    );
};

export default CreateTokenPanel;
