name: metricflow_cloud_demo
version: '1.0.0'
profile: default

model-paths: ['models']
seed-paths: ['seeds']

seeds:
  metricflow_cloud_demo:
    raw_orders:
      +column_types:
        order_id: int64
        customer_id: int64
        ordered_at: date
        status: string
        amount: numeric
        is_food_order: boolean
