import {
    DimensionType,
    Explore,
    FieldType,
    MetricType,
    SupportedDbtAdapter,
} from '@lightdash/common';
import { MetricFlowJsonResults } from '../../../api/MetricFlowAPI';

export const MOCK_EXPLORE: Explore = {
    name: 'metricflow',
    label: '',
    tags: [],
    baseTable: 'metricflow',
    joinedTables: [],
    tables: {
        metricflow: {
            name: 'metricflow',
            label: '',
            database: '',
            schema: '',
            sqlTable: '',
            dimensions: {
                metricflow_metric_time__day: {
                    fieldType: FieldType.DIMENSION,
                    type: DimensionType.TIMESTAMP,
                    name: 'metric_time__day',
                    description: 'Event time for metrics.',
                    label: 'Metric time',
                    table: 'metricflow',
                    tableLabel: '',
                    sql: '',
                    compiledSql: '',
                    tablesReferences: ['metricflow'],
                    hidden: false,
                },
            },
            metrics: {
                metricflow_spice_tons: {
                    isAutoGenerated: false,
                    fieldType: FieldType.METRIC,
                    type: MetricType.NUMBER,
                    name: 'spice_tons',
                    description: 'All the spice harvested in tons',
                    label: 'Spice tons',
                    table: 'metricflow',
                    tableLabel: '',
                    sql: '',
                    compiledSql: '',
                    tablesReferences: ['metricflow'],
                    hidden: false,
                },
            },
            lineageGraph: {},
        },
    },
    targetDatabase: SupportedDbtAdapter.SNOWFLAKE,
};

export const MOCK_SNOWFLAKE_DATA: MetricFlowJsonResults = {
    schema: {
        fields: [
            {
                name: 'index',
                type: 'integer',
            },
            {
                name: 'METRIC_TIME__DAY',
                type: 'datetime',
            },
            {
                name: 'SPICE_TONS',
                type: 'integer',
            },
        ],
        primaryKey: ['index'],
        pandas_version: '1.4.0',
    },
    data: [
        {
            index: 0,
            METRIC_TIME__DAY: '2016-09-01T00:00:00.000Z',
            SPICE_TONS: 466,
        },
        {
            index: 1,
            METRIC_TIME__DAY: '2022-09-01T00:00:00.000Z',
            SPICE_TONS: 1000,
        },
    ],
};

export const EXPECTED_CONVERTED_SNOWFLAKE_DATA = {
    resultsData: {
        metricQuery: {
            dimensions: ['metricflow_metric_time__day'],
            metrics: ['metricflow_spice_tons'],
            filters: {},
            sorts: [],
            limit: 0,
            tableCalculations: [],
        },
        cacheMetadata: {
            cacheHit: false,
        },
        rows: [
            {
                metricflow_index: {
                    value: {
                        formatted: '0',
                        raw: 0,
                    },
                },
                metricflow_metric_time__day: {
                    value: {
                        formatted: '2016-09-01T00:00:00.000Z',
                        raw: '2016-09-01T00:00:00.000Z',
                    },
                },
                metricflow_spice_tons: {
                    value: {
                        formatted: '466',
                        raw: 466,
                    },
                },
            },
            {
                metricflow_index: {
                    value: {
                        formatted: '1',
                        raw: 1,
                    },
                },
                metricflow_metric_time__day: {
                    value: {
                        formatted: '2022-09-01T00:00:00.000Z',
                        raw: '2022-09-01T00:00:00.000Z',
                    },
                },
                metricflow_spice_tons: {
                    value: {
                        formatted: '1000',
                        raw: 1000,
                    },
                },
            },
        ],
    },
    fieldsMap: {
        metricflow_metric_time__day:
            MOCK_EXPLORE.tables.metricflow.dimensions
                .metricflow_metric_time__day,
        metricflow_spice_tons:
            MOCK_EXPLORE.tables.metricflow.metrics.metricflow_spice_tons,
    },
};
