volumes:
    postgres_data:
    minio_data:

services:
    minio:
        image: bitnami/minio:latest
        ports:
            - '9000:9000'
            - '9001:9001' # for minio console
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
            - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
            - MINIO_BROWSER=${MINIO_BROWSER:-off}
        volumes:
            - minio_data:/bitnami/minio/data

    db-dev:
        image: pgvector/pgvector:pg16
        restart: always
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

    headless-browser:
        image: ghcr.io/browserless/chromium:v2.24.3
        restart: always
        ports:
            - '3001:3000'
