version: '3.8'

volumes:
    postgres_data:

services:
    minio:
        image: bitnami/minio:latest
        ports:
            - '9000:9000'
            - '9001:9001' # for minio console
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
            - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}

    db-dev:
        image: pgvector/pgvector:pg16
        restart: always
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    headless-browser:
        image: ghcr.io/browserless/chromium:v2.24.3
        restart: always
        ports:
            - '3001:3000'
