export const AI_DEEP_RESEARCH_HARD_LIMIT_MS = 60 * 60 * 1_000;
export const AI_DEEP_RESEARCH_CLEANUP_GRACE_MS = 5_000;
const AI_DEEP_RESEARCH_WATCHDOG_BUFFER_MS = 1_000;
export const AI_DEEP_RESEARCH_SCHEDULER_WATCHDOG_MS =
    AI_DEEP_RESEARCH_HARD_LIMIT_MS +
    2 * AI_DEEP_RESEARCH_CLEANUP_GRACE_MS +
    AI_DEEP_RESEARCH_WATCHDOG_BUFFER_MS;
