// eslint-disable-next-line import/prefer-default-export
export enum TimeFrames {
    RAW = 'RAW',
    DAY = 'DAY',
    WEEK = 'WEEK',
    MONTH = 'MONTH',
    QUARTER = 'QUARTER',
    YEAR = 'YEAR',
    HOUR = 'HOUR',
    MINUTE = 'MINUTE',
    SECOND = 'SECOND',
    MILLISECOND = 'MILLISECOND',
    DAY_OF_WEEK_INDEX = 'DAY_OF_WEEK_INDEX',
    DAY_OF_MONTH_NUM = 'DAY_OF_MONTH_NUM',
    DAY_OF_YEAR_NUM = 'DAY_OF_YEAR_NUM',
    MONTH_NUM = 'MONTH_NUM',
    QUARTER_NUM = 'QUARTER_NUM',
    YEAR_NUM = 'YEAR_NUM',
    DAY_OF_WEEK_NAME = 'DAY_OF_WEEK_NAME',
    MONTH_NAME = 'MONTH_NAME',
    QUARTER_NAME = 'QUARTER_NAME',
}
