export type CliGrantOperationInventoryEntry = {
    callSite: string;
    method: string;
    endpoint: string;
    operations: readonly string[];
} & (
    | { disposition: 'allowed' }
    | { disposition: 'refused' | 'external'; reason: string }
);

const allowed = (
    callSite: string,
    method: string,
    endpoint: string,
    operations: readonly string[],
): CliGrantOperationInventoryEntry => ({
    callSite,
    method,
    endpoint,
    operations,
    disposition: 'allowed',
});
const refused = (
    callSite: string,
    method: string,
    endpoint: string,
    operations: readonly string[],
    reason: string,
): CliGrantOperationInventoryEntry => ({
    callSite,
    method,
    endpoint,
    operations,
    disposition: 'refused',
    reason,
});
const external = (
    callSite: string,
    method: string,
    endpoint: string,
    reason: string,
): CliGrantOperationInventoryEntry => ({
    callSite,
    method,
    endpoint,
    operations: [],
    disposition: 'external',
    reason,
});

export const CLI_GRANT_OPERATION_INVENTORY: readonly CliGrantOperationInventoryEntry[] =
    [
        allowed('analytics/analytics.ts:32', 'GET', "'/api/v1/user'", [
            'UserController.getAuthenticatedUser',
        ]),
        external(
            'analytics/analytics.ts:622',
            'POST',
            "'https://analytics.lightdash.com/v1/track'",
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        external(
            'analytics/analytics.ts:647',
            'POST',
            "'https://analytics.lightdash.com/v1/identify'",
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        external(
            'dbt/manifest.ts:94',
            'GET',
            'url',
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        external(
            'dbt/targets/Databricks/oauth.ts:204',
            'POST',
            'tokenUrl.href',
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        allowed(
            'handlers/agentAccess.ts:31',
            'GET',
            '`/api/v2/projects/${projectUuid}/ai-access/me`',
            ['AiAccessController.getMyAccess'],
        ),
        refused(
            'handlers/apps/createApp.ts:366',
            'GET',
            '`/api/v1/ee/projects/${projectUuid}/apps/authoring-context?slug=${encodeURIComponent(slug)}`',
            ['AppGenerateController.getDataAppAuthoringContext'],
            'App authoring, uploads and cross-project references need reviewed destination and effect contracts.',
        ),
        allowed(
            'handlers/apps/validate.ts:551',
            'GET',
            '`/api/v1/projects/${projectUuid}/explores`',
            ['ExploreController.GetExplores'],
        ),
        allowed(
            'handlers/apps/validate.ts:562',
            'GET',
            '`/api/v1/projects/${projectUuid}/explores/${encodeURIComponent(summary.name)}`',
            ['ExploreController.GetExplore'],
        ),
        allowed(
            'handlers/asyncQuery.ts:25',
            'GET',
            '`/api/v2/projects/${projectUuid}/query/${queryUuid}${pageSizeParam}`',
            ['QueryController.getAsyncQueryResults'],
        ),
        allowed('handlers/compile.ts:517', 'GET', 'manifestEndpoint', [
            'ProjectController.getMergedManifest',
        ]),
        refused(
            'handlers/connectSnowflake.ts:486',
            'POST',
            'depositUrl.href',
            ['WarehouseConnectController.deposit'],
            'This endpoint requires a separate single-use warehouse connect code.',
        ),
        refused(
            'handlers/createProject.ts:87',
            'GET',
            "'/api/v1/org/warehouse-credentials?summary=true'",
            ['OrganizationWarehouseCredentialsController.getAll'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        allowed(
            'handlers/createProject.ts:145',
            'GET',
            '`/api/v1/health?skipMigrationCheck=true`',
            ['apiV1Router GET /health'],
        ),
        refused(
            'handlers/createProject.ts:420',
            'POST',
            '`/api/v1/org/projects`',
            ['OrganizationController.createProject'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        external(
            'handlers/dbt/apiClient.ts:65',
            'GET',
            'fullUrl',
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        external(
            'handlers/dbt/apiClient.ts:69',
            'GET',
            'fullUrl',
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        external(
            'handlers/dbt/apiClient.ts:163',
            'GET',
            '{\n        method,\n        url,\n        body: requestBody,\n        headers,\n        signal,\n    }',
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        allowed('handlers/dbt/apiClient.ts:191', 'GET', '`/api/v1/user`', [
            'UserController.getAuthenticatedUser',
        ]),
        allowed(
            'handlers/dbt/apiClient.ts:213',
            'GET',
            '`/api/v1/projects/${projectUuid}`',
            ['ProjectController.getProject'],
        ),
        allowed(
            'handlers/dbt/apiClient.ts:427',
            'GET',
            '`/api/v1/health?skipMigrationCheck=true`',
            ['apiV1Router GET /health'],
        ),
        allowed(
            'handlers/dbt/getWarehouseClient.ts:80',
            'GET',
            '`/api/v1/projects/${projectUuid}/sqlRunner/fields?tableName=${tableName}&schemaName=${schemaName}&databaseName=${databaseName}`',
            ['SqlRunnerController.getTableFields'],
        ),
        allowed(
            'handlers/dbt/refresh.ts:20',
            'GET',
            '`/api/v1/projects/${projectUuid}`',
            ['ProjectController.getProject'],
        ),
        allowed(
            'handlers/dbt/refresh.ts:27',
            'POST',
            '`/api/v1/projects/${projectUuid}/refresh`',
            ['ProjectController.refresh'],
        ),
        refused(
            'handlers/dbt/refresh.ts:34',
            'GET',
            '`/api/v1/jobs/${jobUuid}`',
            ['jobsRouter GET /:jobUuid'],
            'Global job identifiers have no reviewed project resolver; an injected project filter cannot scope them.',
        ),
        allowed(
            'handlers/deploy.ts:189',
            'PUT',
            '`/api/v1/projects/${projectUuid}/tags/yaml`',
            ['ProjectController.replaceYamlTags'],
        ),
        allowed(
            'handlers/deploy.ts:200',
            'PUT',
            '`/api/v2/projects/${projectUuid}/parameters`',
            ['ParametersController.replaceParameters'],
        ),
        allowed(
            'handlers/deploy.ts:212',
            'PUT',
            '`/api/v2/projects/${projectUuid}/defaults`',
            ['ProjectDefaultsController.replaceProjectDefaults'],
        ),
        allowed(
            'handlers/deploy.ts:227',
            'PUT',
            '`/api/v1/projects/${projectUuid}/table-groups`',
            ['ProjectController.replaceProjectTableGroups'],
        ),
        allowed(
            'handlers/deploy.ts:315',
            'POST',
            '`/api/v2/projects/${options.projectUuid}/deploy`',
            ['DeployController.startDeploySession'],
        ),
        allowed(
            'handlers/deploy.ts:355',
            'POST',
            '`/api/v2/projects/${options.projectUuid}/deploy/${sessionUuid}/batch`',
            ['DeployController.addDeployBatch'],
        ),
        allowed(
            'handlers/deploy.ts:404',
            'POST',
            '`/api/v2/projects/${options.projectUuid}/deploy/${sessionUuid}/finalize`',
            ['DeployController.finalizeDeploySession'],
        ),
        allowed(
            'handlers/deploy.ts:539',
            'PUT',
            'options.dbtModelNames === undefined\n                            ? `/api/v1/projects/${options.projectUuid}/explores?complete=${options.complete === true}${deployDestinationQuery(options)}`\n                            : `/api/v2/projects/${options.projectUuid}/deploy`',
            [
                'ExploreController.SetExplores',
                'DeployController.deployExplores',
            ],
        ),
        allowed(
            'handlers/deploy.ts:561',
            'PUT',
            '`/api/v1/projects/${options.projectUuid}/explores?complete=${options.complete === true}${deployDestinationQuery(options)}`',
            ['ExploreController.SetExplores'],
        ),
        allowed(
            'handlers/download.ts:965',
            'GET',
            '`${config.endpoint}${queryParams}`',
            [
                'ProjectCoderController.getChartsAsCode',
                'ProjectCoderController.getDashboardsAsCode',
                'ProjectCoderController.getSqlChartsAsCode',
            ],
        ),
        allowed(
            'handlers/download.ts:1121',
            'GET',
            "`/api/v1/projects/${projectId}/code/virtualViews${\n            query ? `?${query}` : ''\n        }`",
            ['ProjectCoderController.getVirtualViewsAsCode'],
        ),
        allowed(
            'handlers/download.ts:1169',
            'GET',
            '`/api/v1/projects/${projectId}/code/virtualViews?${query}`',
            ['ProjectCoderController.getVirtualViewsAsCode'],
        ),
        allowed(
            'handlers/download.ts:1265',
            'POST',
            '`/api/v1/projects/${projectId}/code/virtualViews/${encodeURIComponent(\n                    virtualView.slug,\n                )}?force=${force}`',
            ['ProjectCoderController.upsertVirtualViewAsCode'],
        ),
        allowed(
            'handlers/download.ts:1335',
            'GET',
            '`/api/v1/projects/${projectId}/code/externalConnections?${query}`',
            ['ProjectCoderController.getExternalConnectionsAsCode'],
        ),
        refused(
            'handlers/download.ts:1458',
            'POST',
            '`/api/v1/projects/${projectId}/code/externalConnections/${encodeURIComponent(\n                    connection.slug,\n                )}?force=${force}`',
            ['ProjectCoderController.upsertExternalConnectionAsCode'],
            'This upload can change access, agent tools, credentials or delivery destinations; v1 has no reviewed effect contract.',
        ),
        allowed(
            'handlers/download.ts:1506',
            'GET',
            "`/api/v1/projects/${projectId}/code/documents?${new URLSearchParams(\n                [\n                    ...slugs.map((slug): [string, string] => ['slugs', slug]),\n                    ['offset', String(offset)],\n                    ['schemaVersion', String(DOCUMENT_SCHEMA_VERSION)],\n                ],\n            ).toString()}`",
            ['ProjectCoderController.getDocumentsAsCode'],
        ),
        refused(
            'handlers/download.ts:1581',
            'POST',
            '`/api/v1/projects/${projectId}/code/documents/${encodeURIComponent(\n                    document.slug,\n                )}`',
            ['ProjectCoderController.upsertDocumentAsCode'],
            'This upload can change access, agent tools, credentials or delivery destinations; v1 has no reviewed effect contract.',
        ),
        allowed(
            'handlers/download.ts:1668',
            'GET',
            '`/api/v1/projects/${projectId}/code/aiAgents?${query}`',
            ['ProjectCoderController.getAiAgentsAsCode'],
        ),
        refused(
            'handlers/download.ts:1758',
            'POST',
            '`/api/v1/projects/${projectId}/code/aiAgents?force=${force}`',
            ['ProjectCoderController.upsertAiAgentsAsCode'],
            'This upload can change access, agent tools, credentials or delivery destinations; v1 has no reviewed effect contract.',
        ),
        allowed(
            'handlers/download.ts:1810',
            'GET',
            "`/api/v1/projects/${projectId}/code/${config.route}${\n            query ? `?${query}` : ''\n        }`",
            [
                'ProjectCoderController.getAlertsAsCode',
                'ProjectCoderController.getGoogleSheetsSyncsAsCode',
                'ProjectCoderController.getScheduledDeliveriesAsCode',
            ],
        ),
        refused(
            'handlers/download.ts:1918',
            'POST',
            '`/api/v1/projects/${projectId}/code/${config.route}/${item.slug}?force=${force}`',
            [
                'ProjectCoderController.upsertAlertAsCode',
                'ProjectCoderController.upsertGoogleSheetsSyncAsCode',
                'ProjectCoderController.upsertScheduledDeliveryAsCode',
            ],
            'This upload can change access, agent tools, credentials or delivery destinations; v1 has no reviewed effect contract.',
        ),
        allowed(
            'handlers/download.ts:1955',
            'GET',
            '`/api/v2/content?projectUuids=${projectId}&contentTypes=data_app&page=${page}&pageSize=100`',
            ['ContentController.listContent'],
        ),
        allowed(
            'handlers/download.ts:2162',
            'GET',
            '`/api/v1/projects/${projectId}`',
            ['ProjectController.getProject'],
        ),
        allowed(
            'handlers/download.ts:2678',
            'GET',
            '`/api/v1/ee/projects/${projectId}/apps`',
            ['AppGenerateController.listProjectApps'],
        ),
        allowed(
            'handlers/download.ts:2761',
            'GET',
            '`/api/v1/ee/projects/${fetchProjectId}/apps/${encodeURIComponent(\n                                appRef,\n                            )}/download`',
            ['AppGenerateController.getAppCode'],
        ),
        allowed(
            'handlers/download.ts:2831',
            'GET',
            '`/api/v1/ee/projects/${projectId}/apps/chart-types`',
            ['AppGenerateController.listProjectChartTypes'],
        ),
        allowed(
            'handlers/download.ts:2919',
            'GET',
            '`/api/v1/ee/projects/${fetchProjectId}/apps/${encodeURIComponent(\n                                appRef,\n                            )}/download`',
            ['AppGenerateController.getAppCode'],
        ),
        allowed(
            'handlers/download.ts:2988',
            'GET',
            '`/api/v1/ee/projects/${fetchProjectId}/apps/${encodeURIComponent(\n                            appRef,\n                        )}/download`',
            ['AppGenerateController.getAppCode'],
        ),
        allowed(
            'handlers/download.ts:3054',
            'GET',
            '`/api/v1/ee/projects/${fetchProjectId}/apps/${encodeURIComponent(\n                            appRef,\n                        )}/download`',
            ['AppGenerateController.getAppCode'],
        ),
        allowed('handlers/download.ts:3290', 'POST', 'endpoint', [
            'ProjectCoderController.upsertChartAsCode',
            'ProjectCoderController.upsertSqlChartAsCode',
            'ProjectCoderController.upsertDashboardAsCode',
        ]),
        refused(
            'handlers/download.ts:3351',
            'POST',
            'validationEndpoint',
            [
                'ValidationController.validateChart',
                'ValidationController.validateDashboard',
            ],
            'Queued validation needs reviewed content selectors and project-scoped job polling contracts.',
        ),
        allowed(
            'handlers/download.ts:3762',
            'GET',
            '`/api/v1/projects/${projectUuid}/code/upload-advisory`',
            ['ProjectCoderController.getContentAsCodeUploadAdvisory'],
        ),
        refused(
            'handlers/download.ts:3958',
            'POST',
            '`/api/v1/projects/${projectId}/code/sync-settings`',
            ['ProjectCoderController.stampContentAsCodeSettings'],
            'This changes the project Git sync configuration; v1 refuses sync configuration changes.',
        ),
        allowed(
            'handlers/download.ts:4311',
            'GET',
            "`/api/v1/ee/projects/${projectId}/apps${\n                            phase.isChartTypes ? '/chart-types' : ''\n                        }`",
            [
                'AppGenerateController.listProjectApps',
                'AppGenerateController.listProjectChartTypes',
            ],
        ),
        allowed(
            'handlers/download.ts:4341',
            'GET',
            '`/api/v1/projects/${projectId}/spaces`',
            ['ProjectController.getSpacesInProject'],
        ),
        refused(
            'handlers/download.ts:4598',
            'POST',
            '`/api/v1/ee/projects/${projectId}/apps/upload`',
            ['AppGenerateController.importAppCode'],
            'App authoring, uploads and cross-project references need reviewed destination and effect contracts.',
        ),
        allowed(
            'handlers/exportChartImage.ts:41',
            'POST',
            '`/api/v1/saved/${chartUuidOrSlug}/export${projectQuery}`',
            ['SavedChartController.exportSavedChartImage'],
        ),
        external(
            'handlers/exportChartImage.ts:55',
            'GET',
            'imageUrl',
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        allowed(
            'handlers/generateExposures.ts:70',
            'GET',
            '`/api/v1/projects/${config.context.project}/dbt-exposures`',
            ['ProjectController.GetDbtExposures'],
        ),
        allowed(
            'handlers/homepagesAsCode.ts:32',
            'GET',
            '`/api/v1/projects/${projectUuid}/code/homepages?${query}`',
            ['ProjectCoderController.getHomepagesAsCode'],
        ),
        refused(
            'handlers/homepagesAsCode.ts:92',
            'POST',
            '`/api/v1/projects/${projectUuid}/code/homepages/${encodeURIComponent(document.name)}?publish=${publish}`',
            ['ProjectCoderController.upsertHomepageAsCode'],
            'This upload can change access, agent tools, credentials or delivery destinations; v1 has no reviewed effect contract.',
        ),
        external(
            'handlers/installSkills.ts:109',
            'GET',
            'url',
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        external(
            'handlers/installSkills.ts:128',
            'GET',
            'downloadUrl',
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        refused(
            'handlers/listProjects.ts:17',
            'GET',
            '`/api/v1/org/projects`',
            ['OrganizationController.getProjects'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/login/pat.ts:21',
            'POST',
            'patUrl',
            ['UserController.createPersonalAccessToken'],
            'Human login and credential issuance cannot use an agent connection grant.',
        ),
        allowed('handlers/login.ts:101', 'GET', 'userInfoUrl', [
            'UserController.getAuthenticatedUser',
        ]),
        refused(
            'handlers/login.ts:129',
            'POST',
            'loginUrl',
            ['authRouter POST /login'],
            'Human login and credential issuance cannot use an agent connection grant.',
        ),
        refused(
            'handlers/login.ts:157',
            'POST',
            'patUrl',
            ['UserController.createPersonalAccessToken'],
            'Human login and credential issuance cannot use an agent connection grant.',
        ),
        allowed('handlers/login.ts:188', 'GET', 'userInfoUrl', [
            'UserController.getAuthenticatedUser',
        ]),
        refused(
            'handlers/oauthLogin.ts:188',
            'POST',
            'tokenUrl.href',
            ['oauthRouter POST /token'],
            'This CLI call exchanges an ordinary login code. Agent consent and issuance remain for a later slice; bound refresh uses lifecycle validation.',
        ),
        allowed('handlers/oauthLogin.ts:232', 'GET', 'userInfoUrl.href', [
            'UserController.getAuthenticatedUser',
        ]),
        refused(
            'handlers/organizationContent/customRoles.ts:90',
            'POST',
            '`/api/v2/orgs/${organizationUuid}/code/roles`',
            ['OrganizationCoderController.upsertCustomRoleAsCode'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/customRoles.ts:110',
            'GET',
            '`/api/v2/orgs/${organizationUuid}/code/roles`',
            ['OrganizationCoderController.getCustomRolesAsCode'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/groups.ts:93',
            'POST',
            '`/api/v2/orgs/${organizationUuid}/code/groups`',
            ['OrganizationCoderController.upsertGroupAsCode'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/groups.ts:114',
            'GET',
            '`/api/v2/orgs/${organizationUuid}/code/groups`',
            ['OrganizationCoderController.getGroupsAsCode'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/themes.ts:72',
            'GET',
            "'/api/v1/org/designs/'",
            ['OrganizationDesignController.listDesigns'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/themes.ts:87',
            'GET',
            '`/api/v1/org/designs/${encodeURIComponent(theme.slug)}/package`',
            ['OrganizationDesignController.downloadPackage'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/themes.ts:125',
            'GET',
            "'/api/v1/org/designs/'",
            ['OrganizationDesignController.listDesigns'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/themes.ts:133',
            'PUT',
            "'/api/v1/org/designs/package'",
            ['OrganizationDesignController.importPackage'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/userAttributes.ts:48',
            'GET',
            '`/api/v2/orgs/${organizationUuid}/code/userAttributes`',
            ['OrganizationCoderController.getUserAttributesAsCode'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/userAttributes.ts:67',
            'POST',
            '`/api/v2/orgs/${organizationUuid}/code/userAttributes`',
            ['OrganizationCoderController.upsertUserAttributeAsCode'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/users.ts:141',
            'GET',
            '`/api/v2/orgs/${organizationUuid}/code/users`',
            ['OrganizationCoderController.getUsersAsCode'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/users.ts:151',
            'POST',
            "`/api/v2/orgs/${organizationUuid}/code/users${sendInvites ? '?sendInvite=true' : ''}`",
            ['OrganizationCoderController.upsertUserAsCode'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/organizationContent/users.ts:225',
            'GET',
            '`/api/v2/orgs/${organizationUuid}/code/users`',
            ['OrganizationCoderController.getUsersAsCode'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/preAggregateAudit.ts:58',
            'GET',
            '`/api/v2/projects/${projectUuid}/pre-aggregates/dashboards/${dashboardUuidOrSlug}/audit`',
            ['PreAggregateController.getDashboardPreAggregateAudit'],
            'The audit loads a dashboard and its query state; v1 has no reviewed resource contract for this operation.',
        ),
        allowed(
            'handlers/preAggregateAudit.ts:205',
            'GET',
            '`/api/v1/projects/${args.projectUuid}/dashboards`',
            ['ProjectController.getDashboards'],
        ),
        refused(
            'handlers/preview.ts:107',
            'DELETE',
            '`/api/v1/org/projects/${projectUuid}`',
            ['organizationRouter DELETE /projects/:projectUuid'],
            'Project lifecycle and warehouse configuration changes are refused in v1.',
        ),
        refused(
            'handlers/preview.ts:159',
            'PATCH',
            '`/api/v1/projects/${projectUuid}/preview-expiration`',
            ['ProjectController.updatePreviewExpiresAt'],
            'Project lifecycle and warehouse configuration changes are refused in v1.',
        ),
        refused(
            'handlers/preview.ts:185',
            'GET',
            '`/api/v1/org/projects/`',
            ['OrganizationController.getProjects'],
            'Project lifecycle and warehouse configuration changes are refused in v1.',
        ),
        allowed(
            'handlers/preview.ts:250',
            'GET',
            '`/api/v1/projects/${config.context.project}`',
            ['ProjectController.getProject'],
        ),
        refused(
            'handlers/renameHandler.ts:152',
            'POST',
            '`/api/v1/projects/${projectUuid}/rename`',
            ['RenameController.rename'],
            'Queued renames select content and rewrite dbt metadata; v1 has no reviewed resource and effect contract.',
        ),
        refused(
            'handlers/renameProject.ts:27',
            'PATCH',
            '`/api/v1/projects/${projectUuid}/details`',
            ['ProjectController.updateProjectDetails'],
            'Project lifecycle and warehouse configuration changes are refused in v1.',
        ),
        refused(
            'handlers/resolveProjectFlag.ts:21',
            'GET',
            '`/api/v1/org/projects`',
            ['OrganizationController.getProjects'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        allowed(
            'handlers/runChart.ts:94',
            'POST',
            '`/api/v2/projects/${projectUuid}/query/metric-query`',
            ['QueryController.executeAsyncMetricQuery'],
        ),
        allowed(
            'handlers/selectProject.ts:22',
            'GET',
            '`/api/v1/projects/${previewProjectUuid}`',
            ['ProjectController.getProject'],
        ),
        refused(
            'handlers/setProject.ts:19',
            'GET',
            '`/api/v1/org/projects`',
            ['OrganizationController.getProjects'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/setProject.ts:102',
            'GET',
            '`/api/v1/org/projects`',
            ['OrganizationController.getProjects'],
            'Organization-wide listing or administration is outside the selected project grant.',
        ),
        refused(
            'handlers/skillsAsCode.ts:176',
            'GET',
            "`/api/v1/aiAgents/skills/code${query ? `?${query}` : ''}`",
            ['AiAgentSkillController.getSkillsAsCode'],
            'Shared skills are organization-wide and have no project-only filtering contract.',
        ),
        refused(
            'handlers/skillsAsCode.ts:259',
            'POST',
            "'/api/v1/aiAgents/skills/code'",
            ['AiAgentSkillController.upsertSkillsAsCode'],
            'Shared skills are organization-wide and have no project-only filtering contract.',
        ),
        refused(
            'handlers/slugUpdate.ts:457',
            'POST',
            '`/api/v1/projects/${projectUuid}/slugs/rename`',
            ['ProjectCoderController.renameContentSlug'],
            'Slug renaming needs reviewed selectors for every supported content type; v1 refuses it.',
        ),
        allowed(
            'handlers/sourceSelection.ts:30',
            'GET',
            '`/api/v1/projects/${projectUuid}/dbt-sources`',
            ['ProjectDbtSourcesController.listProjectDbtSources'],
        ),
        allowed(
            'handlers/spacesAsCode.ts:759',
            'GET',
            '`/api/v1/projects/${projectId}/code/spaces`',
            ['ProjectCoderController.getCodeSpaces'],
        ),
        refused(
            'handlers/spacesAsCode.ts:891',
            'POST',
            '`/api/v1/projects/${projectId}/code/spaces?${params.toString()}`',
            ['ProjectCoderController.upsertCodeSpace'],
            'This upload can change access, agent tools, credentials or delivery destinations; v1 has no reviewed effect contract.',
        ),
        allowed(
            'handlers/sql.ts:61',
            'POST',
            '`/api/v2/projects/${projectUuid}/query/sql`',
            ['QueryController.executeAsyncSqlQuery'],
        ),
        allowed(
            'handlers/timestampConversion.ts:33',
            'GET',
            '`/api/v1/projects/${projectUuid}`',
            ['ProjectController.getProject'],
        ),
        external(
            'handlers/upgradeCheck.ts:151',
            'GET',
            'RELEASE_SAFETY_INDEX_URL',
            'External fetch or API transport delegates authorization to the inventoried Lightdash caller.',
        ),
        refused(
            'handlers/validate.ts:41',
            'POST',
            '`/api/v1/projects/${projectUuid}/validate`',
            ['ValidationController.post'],
            'Queued validation needs reviewed content selectors and project-scoped job polling contracts.',
        ),
        refused(
            'handlers/validate.ts:48',
            'GET',
            '`/api/v1/schedulers/job/${jobUuid}/status`',
            ['SchedulerController.getSchedulerStatus'],
            'Global job identifiers have no reviewed project resolver; an injected project filter cannot scope them.',
        ),
        allowed(
            'handlers/validate.ts:55',
            'GET',
            '`/api/v1/projects/${projectUuid}/validate?jobId=${jobId}`',
            ['ValidationController.get'],
        ),
        allowed(
            'handlers/validate.ts:62',
            'GET',
            '`/api/v1/projects/${projectUuid}/spaces`',
            ['ProjectController.getSpacesInProject'],
        ),
        allowed(
            'handlers/warehouseCatalog.ts:161',
            'POST',
            '`/api/v1/projects/${projectUuid}/sqlRunner/refresh-catalog`',
            ['SqlRunnerController.refreshSqlRunnerCatalog'],
        ),
        allowed(
            'handlers/warehouseCatalog.ts:168',
            'GET',
            '`/api/v1/projects/${projectUuid}/sqlRunner/tables`',
            ['SqlRunnerController.getTables'],
        ),
        allowed(
            'handlers/warehouseCatalog.ts:186',
            'GET',
            '`/api/v1/projects/${projectUuid}/sqlRunner/fields?${query.toString()}`',
            ['SqlRunnerController.getTableFields'],
        ),
        refused(
            'handlers/warehouseConnection.ts:51',
            'PATCH',
            '`/api/v1/projects/${project.projectUuid}`',
            ['projectRouter PATCH /'],
            'Project lifecycle and warehouse configuration changes are refused in v1.',
        ),
    ];
