
### Login
// @no-log
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email": "demo@lightdash.com",
    "password": "demo_password!"
}

### Logout

GET http://localhost:8080/api/v1/logout

### Get project config
GET http://localhost:8080/api/v1/embed/3675b69e-8324-4110-bdca-059031aa8da3/config

### Save project config
POST http://localhost:8080/api/v1/embed/3675b69e-8324-4110-bdca-059031aa8da3/config
Content-Type: application/json

{
    "dashboardUuids": ["fe9ff10c-a314-42f7-bef8-04ec711a13a1"]
}

### Update dashboards on config
PATCH http://localhost:8080/api/v1/embed/3675b69e-8324-4110-bdca-059031aa8da3/config/dashboards
Content-Type: application/json

{
    "dashboardUuids": ["fe9ff10c-a314-42f7-bef8-04ec711a13a1"]
}

### Get embed dashboard
POST http://localhost:8080/api/v1/embed/3675b69e-8324-4110-bdca-059031aa8da3/dashboard
Lightdash-Embed-Token: <embed_token>
Content-Type: application/json

{

}

### Get embed chart
POST http://localhost:8080/api/v1/embed/3675b69e-8324-4110-bdca-059031aa8da3/chart-and-results
Lightdash-Embed-Token: <embed_token>
Content-Type: application/json

{
    "chartUuid": "e6efe2fa-f884-47ea-ac9b-1e3ebe303b30"
}

### Generate dashboard embed url
#### use the dashboardUuid you want to embed

POST http://localhost:8080/api/v1/embed/{{projectUuid}}/get-embed-url
Content-Type: application/json

{
    "user": {
        "externalId": "steve@here.com"
    },
    "content": {
        "type": "dashboard",
        "dashboardUuid": "{{dashboardUuid}}",
        "canExplore": true,
        "canExportCsv": true,
        "canExportImages": true,
        "canDateZoom": true,
        "canExportPagePdf": true,
        "projectUuid": "{{projectUuid}}"
    }
}

### Generate embed url for chart - use the chartUuid you want to embed

POST http://localhost:8080/api/v1/embed/{{projectUuid}}/get-embed-url
Content-Type: application/json

{
    "user": {
        "externalId": "chart-user@example.com",
        "email": "chart-user@example.com"
    },
    "content": {
        "type": "chart",
        "contentId": "{{chartUuid}}",
        "scopes": ["view:Chart"],
        "canExportCsv": true,
        "canExportImages": false,
        "canViewUnderlyingData": true,
        "projectUuid": "{{projectUuid}}"
    },
    "expiresIn": "24h"
}


### We can use JWT token to call some endpoints that support `account` parameters.

### Get chart results using JWT token
GET http://localhost:8080/api/v1/saved/{{chartUuid}}
Lightdash-Embed-Token: {{chartJwtToken}}

# This endpoint should not work, since the chart is not the one in the JWT token
### Get another chart results using JWT token
GET http://localhost:8080/api/v1/saved/868d7c41-2184-4d1d-b5f8-33e00ae1ae96
Lightdash-Embed-Token: {{chartJwtToken}}


### Run SQL query using JWT token
POST http://localhost:8080/api/v1/projects/{{projectUuid}}/sqlQuery
Lightdash-Embed-Token: {{chartJwtToken}}
Content-Type: application/json

{
   "sql": "SELECT * FROM postgres.jaffle.orders LIMIT 10"
}
   

### This calculate total endpoint does not support chart JWT token, only dashboard
@chartJwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImV4dGVybmFsSWQiOiJjaGFydC11c2VyQGV4YW1wbGUuY29tIiwiZW1haWwiOiJjaGFydC11c2VyQGV4YW1wbGUuY29tIn0sImNvbnRlbnQiOnsidHlwZSI6ImNoYXJ0IiwiY29udGVudElkIjoiMDg1NDYxMWEtOTg0Mi00OTM3LTljYWItMzdmYjM1NTdlODUyIiwic2NvcGVzIjpbInZpZXc6Q2hhcnQiXSwiY2FuRXhwb3J0Q3N2Ijp0cnVlLCJjYW5FeHBvcnRJbWFnZXMiOmZhbHNlLCJjYW5WaWV3VW5kZXJseWluZ0RhdGEiOnRydWUsInByb2plY3RVdWlkIjoiMzY3NWI2OWUtODMyNC00MTEwLWJkY2EtMDU5MDMxYWE4ZGEzIn0sImlhdCI6MTc2MTIxNDgxNCwiZXhwIjoxNzYxMzAxMjE0fQ.h1bv99NPtjIICpsmQ0QqZPDJOJYtJ7iJ4-urQqNDXP8
POST http://localhost:8080/api/v1/embed/{{projectUuid}}/chart/{{chartUuid}}/calculate-total
Lightdash-Embed-Token: {{chartJwtToken}}
Content-Type: application/json

{
    "invalidateCache": false
}