
### Login
// @no-log
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email": "demo@lightdash.com",
    "password": "demo_password!"
}

# To get a new scim token, check scim-org-tokens.http

### Create a new user

POST http://localhost:8080/api/v1/scim/v2/Users
Content-Type: application/json
Authorization: Bearer scim_9d95455ef43b7dd9077d9001e1c5b112

{
    "schemas": ["urn:ietf:params:scim:schemas:core:2.0:User"],
    "userName": "new-user@example.com",
    "name": {
        "givenName": "New",
        "familyName": "User"
    },
    "active": true,
    "emails": [
        {
            "value": "new-user@example.com",
            "primary": true
        }
    ]
}


### Update user userName (PUT - full replacement)
PUT http://localhost:8080/api/v1/scim/v2/Users/fdc58e24-906e-4813-a7e7-8522424cb2ce
Content-Type: application/json
Authorization: Bearer scim_9d95455ef43b7dd9077d9001e1c5b112

{
    "schemas": ["urn:ietf:params:scim:schemas:core:2.0:User"],
    "userName": "updated-user@example.com",
    "name": {
        "givenName": "New",
        "familyName": "User"
    },
    "active": true,
    "emails": [
        {
            "value": "updated-user@example.com",
            "primary": true
        }
    ]
}

