### Login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email": "demo@lightdash.com",
    "password": "demo_password!"
}

### List service accounts
GET http://localhost:8080/api/v1/service-accounts

### Create a service account
POST http://localhost:8080/api/v1/service-accounts
Content-Type: application/json

{
    "description": "http test",
    "expiresAt": "2025-06-11T14:00:00.000Z",
    "scopes": ["org:admin"]
}