### Login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email": "demo@lightdash.com",
    "password": "demo_password!"
}

### List service accounts
GET http://localhost:8080/api/v1/service-accounts

### Create a service account
POST http://localhost:8080/api/v1/service-accounts
Content-Type: application/json

{
    "description": "http test",
    "expiresAt": "2025-09-11T14:00:00.000Z",
    "scopes": ["org:admin"]
}

### Logout
GET http://localhost:8080/api/v1/logout

### Make a request using the service account
GET http://localhost:8080/api/v1/org/projects
Authorization: Bearer 9649663ed1f1897221da9d8db09b961f

#### Also test the same endpoint using api token
GET http://localhost:8080/api/v1/org/projects
Authorization: ApiKey 9034a7ef26151167617f9f9b412d5247

### I can't use service account on an unauthorized endpoint (this endpoint does not have allowApiKeyAuthentication middleware)
GET http://localhost:8080/api/v1/org/allowedEmailDomains
Authorization: Bearer 3e3bd56d5f428cfdaaab961dfdac6aef
#Authorization: ApiKey 9034a7ef26151167617f9f9b412d5247

### Do not use any authentication, this should throw an error on the apitoken middleware
GET http://localhost:8080/api/v1/org/projects
