### Login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email": "demo@lightdash.com",
    "password": "demo_password!"
}

#### Get tables
GET http://localhost:8080/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/sqlRunner/tables

#### Get fields
GET http://localhost:8080/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/sqlRunner/tables/orders


#### Run SQL as a job
POST http://localhost:8080/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/sqlRunner/run 
Content-Type: application/json

{
    "sql": "SELECT * FROM postgres.jaffle.payments LIMIT 21"
} 

### Get job status
GET http://localhost:8080/api/v1/schedulers/job/53395/status

### Get results from file
GET http://localhost:8080/api/v1/projects/3675b69e-8324-4110-bdca-059031aa8da3/sqlRunner/results/RerwSgzNaIMtf1NKJ3_9j

