import type { TestCase } from '../types';

export const aggregationCases: TestCase[] = [
    {
        id: 'aggregation/sum',
        formula: '=SUM(A)',
        description: 'SUM aggregate over all rows',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [{ result: 2075.50 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation'],
    },
    {
        id: 'aggregation/avg',
        formula: '=AVG(A)',
        description: 'AVG aggregate over all rows',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [{ result: 207.55 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation'],
    },
    {
        id: 'aggregation/count-column',
        formula: '=COUNT(A)',
        description: 'COUNT of non-null values in column',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [{ result: 10 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation'],
    },
    {
        id: 'aggregation/count-all',
        formula: '=COUNT()',
        description: 'COUNT all rows',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [{ result: 10 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation'],
    },
    {
        id: 'aggregation/min',
        formula: '=MIN(A)',
        description: 'MIN aggregate (single argument)',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [{ result: 30.00 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation'],
    },
    {
        id: 'aggregation/max',
        formula: '=MAX(A)',
        description: 'MAX aggregate (single argument)',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [{ result: 500.00 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation'],
    },
    {
        id: 'aggregation/sum-with-nulls',
        formula: '=SUM(A)',
        description: 'SUM skips NULL values (10 + 30 + 50 = 90)',
        columns: { A: 'val_a' },
        sourceTable: 'test_nulls',
        expectedRows: [{ result: 90.00 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation', 'null'],
    },
    {
        id: 'aggregation/avg-with-nulls',
        formula: '=AVG(A)',
        description: 'AVG skips NULL values (90 / 3 = 30)',
        columns: { A: 'val_a' },
        sourceTable: 'test_nulls',
        expectedRows: [{ result: 30.00 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation', 'null'],
    },
    {
        id: 'aggregation/count-with-nulls',
        formula: '=COUNT(A)',
        description: 'COUNT skips NULL values (3 non-null out of 5)',
        columns: { A: 'val_a' },
        sourceTable: 'test_nulls',
        expectedRows: [{ result: 3 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation', 'null'],
    },
    {
        id: 'aggregation/count-all-with-nulls',
        formula: '=COUNT()',
        description: 'COUNT() counts all rows including those with NULLs',
        columns: {},
        sourceTable: 'test_nulls',
        expectedRows: [{ result: 5 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation', 'null'],
    },
    {
        id: 'aggregation/sum-expression',
        formula: '=SUM(A) + SUM(B)',
        description: 'Arithmetic on aggregate results',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        expectedRows: [{ result: 2283.05 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation', 'arithmetic'],
    },
    {
        id: 'aggregation/avg-vs-sum-count',
        formula: '=SUM(A) / COUNT(A)',
        description: 'Manual average via SUM/COUNT matches AVG behavior',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [{ result: 207.55 }],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['aggregation'],
    },
];
