import { ALL_WAREHOUSES } from '../config';
import type { TestCase } from '../types';

export const arithmeticCases: TestCase[] = [
    {
        id: 'arithmetic/add-two-columns',
        formula: '=A + B',
        description: 'Add two numeric columns',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 110.00 },
            { result: 275.55 },
            { result: 82.50 },
            { result: 550.00 },
            { result: 33.00 },
            { result: 198.00 },
            { result: 462.00 },
            { result: 66.00 },
            { result: 341.00 },
            { result: 165.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/subtract',
        formula: '=A - B',
        description: 'Subtract two numeric columns',
        columns: { A: 'order_amount', B: 'discount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 95.00 },
            { result: 238.00 },
            { result: 75.00 },
            { result: 475.00 },
            { result: 28.50 },
            { result: 171.00 },
            { result: 399.00 },
            { result: 57.00 },
            { result: 294.50 },
            { result: 142.50 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/multiply',
        formula: '=A * B',
        description: 'Multiply two numeric columns',
        columns: { A: 'order_amount', B: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 200.00 },
            { result: 250.50 },
            { result: 225.00 },
            { result: 500.00 },
            { result: 150.00 },
            { result: 360.00 },
            { result: 420.00 },
            { result: 240.00 },
            { result: 620.00 },
            { result: 450.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/divide',
        formula: '=A / B',
        description: 'Divide two numeric columns (safe division)',
        columns: { A: 'order_amount', B: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 50.00 },
            { result: 250.50 },
            { result: 25.00 },
            { result: 500.00 },
            { result: 6.00 },
            { result: 90.00 },
            { result: 420.00 },
            { result: 15.00 },
            { result: 155.00 },
            { result: 50.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/literal-addition',
        formula: '=A + 10',
        description: 'Add a literal number to a column',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 110.00 },
            { result: 260.50 },
            { result: 85.00 },
            { result: 510.00 },
            { result: 40.00 },
            { result: 190.00 },
            { result: 430.00 },
            { result: 70.00 },
            { result: 320.00 },
            { result: 160.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/complex-expression',
        formula: '=(A + B) * C',
        description: 'Complex expression with parentheses',
        columns: { A: 'order_amount', B: 'tax', C: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 220.00 },
            { result: 275.55 },
            { result: 247.50 },
            { result: 550.00 },
            { result: 165.00 },
            { result: 396.00 },
            { result: 462.00 },
            { result: 264.00 },
            { result: 682.00 },
            { result: 495.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/unary-minus',
        formula: '=-A',
        description: 'Negate a column',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: -100.00 },
            { result: -250.50 },
            { result: -75.00 },
            { result: -500.00 },
            { result: -30.00 },
            { result: -180.00 },
            { result: -420.00 },
            { result: -60.00 },
            { result: -310.00 },
            { result: -150.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/power',
        formula: '=A ^ 2',
        description: 'Raise column to a power',
        columns: { A: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 4 },
            { result: 1 },
            { result: 9 },
            { result: 1 },
            { result: 25 },
            { result: 4 },
            { result: 1 },
            { result: 16 },
            { result: 4 },
            { result: 9 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/modulo',
        formula: '=A % B',
        description: 'Modulo operator',
        columns: { A: 'order_amount', B: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 0 },
            { result: 0.50 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/divide-by-zero',
        formula: '=A / 0',
        description: 'Division by zero should return NULL via NULLIF',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: null },
            { result: null },
            { result: null },
            { result: null },
            { result: null },
            { result: null },
            { result: null },
            { result: null },
            { result: null },
            { result: null },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/chained-operations',
        formula: '=A + B - C + D',
        description: 'Chained add/subtract across four columns',
        columns: { A: 'order_amount', B: 'tax', C: 'discount', D: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 107.00 },
            { result: 264.05 },
            { result: 85.50 },
            { result: 526.00 },
            { result: 36.50 },
            { result: 191.00 },
            { result: 442.00 },
            { result: 67.00 },
            { result: 327.50 },
            { result: 160.50 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
    {
        id: 'arithmetic/nested-parentheses',
        formula: '=(A - B) * (C + 1)',
        description: 'Nested parentheses with multiple operators',
        columns: { A: 'order_amount', B: 'discount', C: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 285.00 },
            { result: 476.00 },
            { result: 300.00 },
            { result: 950.00 },
            { result: 171.00 },
            { result: 513.00 },
            { result: 798.00 },
            { result: 285.00 },
            { result: 883.50 },
            { result: 570.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['arithmetic'],
    },
];
