import { ALL_WAREHOUSES } from '../config';
import type { TestCase } from '../types';

export const dateCases: TestCase[] = [
    {
        id: 'date/year',
        formula: '=YEAR(A)',
        description: 'Extract year from date column',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/month',
        formula: '=MONTH(A)',
        description: 'Extract month from date column',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 1 },
            { result: 2 },
            { result: 3 },
            { result: 4 },
            { result: 5 },
            { result: 6 },
            { result: 7 },
            { result: 8 },
            { result: 9 },
            { result: 10 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/day',
        formula: '=DAY(A)',
        description: 'Extract day of month from date column',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 15 },
            { result: 20 },
            { result: 10 },
            { result: 5 },
            { result: 12 },
            { result: 18 },
            { result: 22 },
            { result: 30 },
            { result: 14 },
            { result: 1 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/year-in-expression',
        formula: '=YEAR(A) * 100 + MONTH(A)',
        description: 'Date extraction used in arithmetic expression (YYYYMM-style)',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 202401 },
            { result: 202402 },
            { result: 202403 },
            { result: 202404 },
            { result: 202405 },
            { result: 202406 },
            { result: 202407 },
            { result: 202408 },
            { result: 202409 },
            { result: 202410 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date', 'arithmetic'],
    },
    {
        id: 'date/last-day',
        formula: '=YEAR(LAST_DAY(A)) * 10000 + MONTH(LAST_DAY(A)) * 100 + DAY(LAST_DAY(A))',
        description:
            'LAST_DAY compared as YYYYMMDD integer — dialect-neutral serialisation, pins year+month+day (covers leap-year Feb 2024)',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20240131 },
            { result: 20240229 },
            { result: 20240331 },
            { result: 20240430 },
            { result: 20240531 },
            { result: 20240630 },
            { result: 20240731 },
            { result: 20240831 },
            { result: 20240930 },
            { result: 20241031 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-trunc-month',
        formula: '=YEAR(DATE_TRUNC("month", A)) * 10000 + MONTH(DATE_TRUNC("month", A)) * 100 + DAY(DATE_TRUNC("month", A))',
        description: 'DATE_TRUNC month boundary as YYYYMMDD integer',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20240101 },
            { result: 20240201 },
            { result: 20240301 },
            { result: 20240401 },
            { result: 20240501 },
            { result: 20240601 },
            { result: 20240701 },
            { result: 20240801 },
            { result: 20240901 },
            { result: 20241001 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-trunc-quarter',
        formula: '=YEAR(DATE_TRUNC("quarter", A)) * 10000 + MONTH(DATE_TRUNC("quarter", A)) * 100 + DAY(DATE_TRUNC("quarter", A))',
        description: 'DATE_TRUNC quarter pins to 01-Jan / 01-Apr / 01-Jul / 01-Oct',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20240101 },
            { result: 20240101 },
            { result: 20240101 },
            { result: 20240401 },
            { result: 20240401 },
            { result: 20240401 },
            { result: 20240701 },
            { result: 20240701 },
            { result: 20240701 },
            { result: 20241001 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-trunc-year',
        formula: '=YEAR(DATE_TRUNC("year", A)) * 10000 + MONTH(DATE_TRUNC("year", A)) * 100 + DAY(DATE_TRUNC("year", A))',
        description: 'DATE_TRUNC year pins to 01-Jan',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20240101 },
            { result: 20240101 },
            { result: 20240101 },
            { result: 20240101 },
            { result: 20240101 },
            { result: 20240101 },
            { result: 20240101 },
            { result: 20240101 },
            { result: 20240101 },
            { result: 20240101 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-trunc-week-monday',
        formula: '=YEAR(DATE_TRUNC("week", A)) * 10000 + MONTH(DATE_TRUNC("week", A)) * 100 + DAY(DATE_TRUNC("week", A))',
        description: 'DATE_TRUNC week defaults to Monday-start across all dialects',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20240115 }, // 2024-01-15 Mon
            { result: 20240219 }, // 2024-02-20 Tue → Mon 19
            { result: 20240304 }, // 2024-03-10 Sun → Mon 4
            { result: 20240401 }, // 2024-04-05 Fri → Mon 1
            { result: 20240506 }, // 2024-05-12 Sun → Mon 6
            { result: 20240617 }, // 2024-06-18 Tue → Mon 17
            { result: 20240722 }, // 2024-07-22 Mon
            { result: 20240826 }, // 2024-08-30 Fri → Mon 26
            { result: 20240909 }, // 2024-09-14 Sat → Mon 9
            { result: 20240930 }, // 2024-10-01 Tue → Mon 30 (prev month)
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-add-month',
        formula: '=YEAR(DATE_ADD(A, 3, "month")) * 10000 + MONTH(DATE_ADD(A, 3, "month")) * 100 + DAY(DATE_ADD(A, 3, "month"))',
        description: 'DATE_ADD +3 months as YYYYMMDD integer',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20240415 },
            { result: 20240520 },
            { result: 20240610 },
            { result: 20240705 },
            { result: 20240812 },
            { result: 20240918 },
            { result: 20241022 },
            { result: 20241130 },
            { result: 20241214 },
            { result: 20250101 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-sub-year',
        formula: '=YEAR(DATE_SUB(A, 1, "year")) * 10000 + MONTH(DATE_SUB(A, 1, "year")) * 100 + DAY(DATE_SUB(A, 1, "year"))',
        description: 'DATE_SUB -1 year as YYYYMMDD integer (exercises parse-time negation)',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20230115 },
            { result: 20230220 },
            { result: 20230310 },
            { result: 20230405 },
            { result: 20230512 },
            { result: 20230618 },
            { result: 20230722 },
            { result: 20230830 },
            { result: 20230914 },
            { result: 20231001 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-add-day',
        formula: '=YEAR(DATE_ADD(A, 7, "day")) * 10000 + MONTH(DATE_ADD(A, 7, "day")) * 100 + DAY(DATE_ADD(A, 7, "day"))',
        description: 'DATE_ADD +7 days — crosses month boundaries',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20240122 },
            { result: 20240227 },
            { result: 20240317 },
            { result: 20240412 },
            { result: 20240519 },
            { result: 20240625 },
            { result: 20240729 },
            { result: 20240906 },
            { result: 20240921 },
            { result: 20241008 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-diff-day',
        formula: '=DATE_DIFF(A, DATE_ADD(A, 100, "day"), "day")',
        description: 'DATE_DIFF in days — always 100 regardless of the starting date',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 100 },
            { result: 100 },
            { result: 100 },
            { result: 100 },
            { result: 100 },
            { result: 100 },
            { result: 100 },
            { result: 100 },
            { result: 100 },
            { result: 100 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-diff-month',
        formula: '=DATE_DIFF(DATE_SUB(A, 5, "month"), A, "month")',
        description: 'DATE_DIFF in months between A and 5 months before A',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 5 },
            { result: 5 },
            { result: 5 },
            { result: 5 },
            { result: 5 },
            { result: 5 },
            { result: 5 },
            { result: 5 },
            { result: 5 },
            { result: 5 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-diff-year-negative',
        formula: '=DATE_DIFF(A, DATE_SUB(A, 2, "year"), "year")',
        description: 'DATE_DIFF returns negative when end < start (2 years back)',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: -2 },
            { result: -2 },
            { result: -2 },
            { result: -2 },
            { result: -2 },
            { result: -2 },
            { result: -2 },
            { result: -2 },
            { result: -2 },
            { result: -2 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/day-in-if',
        formula: '=IF(DAY(A) > 15, "late", "early")',
        description: 'Date extraction combined with IF condition',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'early' },
            { result: 'late' },
            { result: 'early' },
            { result: 'early' },
            { result: 'early' },
            { result: 'late' },
            { result: 'late' },
            { result: 'late' },
            { result: 'early' },
            { result: 'early' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date', 'logical'],
    },
    {
        id: 'date/date-trunc-day',
        formula: '=YEAR(DATE_TRUNC("day", A)) * 10000 + MONTH(DATE_TRUNC("day", A)) * 100 + DAY(DATE_TRUNC("day", A))',
        description:
            'DATE_TRUNC day on a date column is a no-op — round-trips to YYYYMMDD',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20240115 },
            { result: 20240220 },
            { result: 20240310 },
            { result: 20240405 },
            { result: 20240512 },
            { result: 20240618 },
            { result: 20240722 },
            { result: 20240830 },
            { result: 20240914 },
            { result: 20241001 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-trunc-week-sunday',
        formula: '=YEAR(DATE_TRUNC("week", A)) * 10000 + MONTH(DATE_TRUNC("week", A)) * 100 + DAY(DATE_TRUNC("week", A))',
        description:
            'DATE_TRUNC week with weekStartDay=6 (Sunday) — exercises BigQuery WEEK(SUNDAY), Databricks/ClickHouse offset shift, Postgres composition',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        weekStartDay: 6,
        expectedRows: [
            { result: 20240114 }, // 2024-01-15 Mon → Sun 14
            { result: 20240218 }, // 2024-02-20 Tue → Sun 18
            { result: 20240310 }, // 2024-03-10 Sun → itself
            { result: 20240331 }, // 2024-04-05 Fri → Sun 03-31
            { result: 20240512 }, // 2024-05-12 Sun → itself
            { result: 20240616 }, // 2024-06-18 Tue → Sun 16
            { result: 20240721 }, // 2024-07-22 Mon → Sun 21
            { result: 20240825 }, // 2024-08-30 Fri → Sun 25
            { result: 20240908 }, // 2024-09-14 Sat → Sun 09-08
            { result: 20240929 }, // 2024-10-01 Tue → Sun 09-29
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-add-week',
        formula: '=YEAR(DATE_ADD(A, 2, "week")) * 10000 + MONTH(DATE_ADD(A, 2, "week")) * 100 + DAY(DATE_ADD(A, 2, "week"))',
        description:
            'DATE_ADD +2 weeks (= +14 days) — exercises Databricks date_add and ClickHouse addWeeks',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20240129 },
            { result: 20240305 },
            { result: 20240324 },
            { result: 20240419 },
            { result: 20240526 },
            { result: 20240702 },
            { result: 20240805 },
            { result: 20240913 },
            { result: 20240928 },
            { result: 20241015 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-add-quarter',
        formula: '=YEAR(DATE_ADD(A, 1, "quarter")) * 10000 + MONTH(DATE_ADD(A, 1, "quarter")) * 100 + DAY(DATE_ADD(A, 1, "quarter"))',
        description:
            'DATE_ADD +1 quarter (= +3 months) — exercises Databricks add_months path and ClickHouse addQuarters',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20240415 },
            { result: 20240520 },
            { result: 20240610 },
            { result: 20240705 },
            { result: 20240812 },
            { result: 20240918 },
            { result: 20241022 },
            { result: 20241130 },
            { result: 20241214 },
            { result: 20250101 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-sub-week',
        formula: '=YEAR(DATE_SUB(A, 3, "week")) * 10000 + MONTH(DATE_SUB(A, 3, "week")) * 100 + DAY(DATE_SUB(A, 3, "week"))',
        description:
            'DATE_SUB -3 weeks (= -21 days) — exercises week unit through the parse-time negation',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 20231225 },
            { result: 20240130 },
            { result: 20240218 },
            { result: 20240315 },
            { result: 20240421 },
            { result: 20240528 },
            { result: 20240701 },
            { result: 20240809 },
            { result: 20240824 },
            { result: 20240910 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-diff-week',
        formula: '=DATE_DIFF(A, DATE_ADD(A, 14, "day"), "week")',
        description:
            'DATE_DIFF in weeks — 14 days = 2 weeks, alignment-stable across dialects',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-diff-week-sunday',
        formula: '=DATE_DIFF(A, DATE_ADD(A, 14, "day"), "week")',
        description:
            'DATE_DIFF in weeks with weekStartDay=6 — exercises the non-Monday composition path (day-diff between week-truncated endpoints)',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        weekStartDay: 6,
        expectedRows: [
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
            { result: 2 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/date-diff-quarter',
        formula: '=DATE_DIFF(A, DATE_ADD(A, 1, "quarter"), "quarter")',
        description: 'DATE_DIFF in quarters — DATE_ADD +1 quarter is exactly 1 quarter back',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 1 },
            { result: 1 },
            { result: 1 },
            { result: 1 },
            { result: 1 },
            { result: 1 },
            { result: 1 },
            { result: 1 },
            { result: 1 },
            { result: 1 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['date'],
    },
];
