import type { TestCase } from '../types';

export const dateCases: TestCase[] = [
    {
        id: 'date/year',
        formula: '=YEAR(A)',
        description: 'Extract year from date column',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
            { result: 2024 },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/month',
        formula: '=MONTH(A)',
        description: 'Extract month from date column',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 1 },
            { result: 2 },
            { result: 3 },
            { result: 4 },
            { result: 5 },
            { result: 6 },
            { result: 7 },
            { result: 8 },
            { result: 9 },
            { result: 10 },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/day',
        formula: '=DAY(A)',
        description: 'Extract day of month from date column',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 15 },
            { result: 20 },
            { result: 10 },
            { result: 5 },
            { result: 12 },
            { result: 18 },
            { result: 22 },
            { result: 30 },
            { result: 14 },
            { result: 1 },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['date'],
    },
    {
        id: 'date/year-in-expression',
        formula: '=YEAR(A) * 100 + MONTH(A)',
        description: 'Date extraction used in arithmetic expression (YYYYMM-style)',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 202401 },
            { result: 202402 },
            { result: 202403 },
            { result: 202404 },
            { result: 202405 },
            { result: 202406 },
            { result: 202407 },
            { result: 202408 },
            { result: 202409 },
            { result: 202410 },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['date', 'arithmetic'],
    },
    {
        id: 'date/day-in-if',
        formula: '=IF(DAY(A) > 15, "late", "early")',
        description: 'Date extraction combined with IF condition',
        columns: { A: 'order_date' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'early' },
            { result: 'late' },
            { result: 'early' },
            { result: 'early' },
            { result: 'early' },
            { result: 'late' },
            { result: 'late' },
            { result: 'late' },
            { result: 'early' },
            { result: 'early' },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['date', 'logical'],
    },
];
