import { ALL_WAREHOUSES } from '../config';
import type { TestCase } from '../types';

export const edgeCases: TestCase[] = [
    {
        id: 'edge/large-number',
        formula: '=A * 1000000',
        description: 'Multiplication with large literal',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 100000000 },
            { result: 250500000 },
            { result: 75000000 },
            { result: 500000000 },
            { result: 30000000 },
            { result: 180000000 },
            { result: 420000000 },
            { result: 60000000 },
            { result: 310000000 },
            { result: 150000000 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge'],
    },
    {
        id: 'edge/multiply-by-zero',
        formula: '=A * 0',
        description: 'Multiply column by zero',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge'],
    },
    {
        id: 'edge/negative-literal',
        formula: '=A + (-5)',
        description: 'Addition with negative literal in parentheses',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 95.00 },
            { result: 245.50 },
            { result: 70.00 },
            { result: 495.00 },
            { result: 25.00 },
            { result: 175.00 },
            { result: 415.00 },
            { result: 55.00 },
            { result: 305.00 },
            { result: 145.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge'],
    },
    {
        id: 'edge/error-empty-formula',
        formula: '=',
        description: 'Empty formula should produce a parse error',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge', 'error'],
    },
    {
        id: 'edge/error-malformed-syntax',
        formula: '=A +* B',
        description: 'Malformed syntax should produce a parse error',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge', 'error'],
    },
    {
        id: 'edge/error-unclosed-paren',
        formula: '=(A + B',
        description: 'Unclosed parenthesis should produce a parse error',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge', 'error'],
    },
    {
        id: 'edge/error-unknown-function',
        formula: '=FAKEFUNC(A)',
        description: 'Unknown function name should produce an error',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [],
        expectedError: 'unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge', 'error'],
    },
    {
        id: 'edge/error-extra-close-paren',
        formula: '=(A + B))',
        description: 'Extra closing parenthesis should produce a parse error',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge', 'error'],
    },
    {
        id: 'edge/literal-only',
        formula: '=42',
        description: 'Formula with only a numeric literal',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 42 },
            { result: 42 },
            { result: 42 },
            { result: 42 },
            { result: 42 },
            { result: 42 },
            { result: 42 },
            { result: 42 },
            { result: 42 },
            { result: 42 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge'],
    },
    {
        id: 'edge/string-literal-only',
        formula: '="hello"',
        description: 'Formula with only a string literal',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'hello' },
            { result: 'hello' },
            { result: 'hello' },
            { result: 'hello' },
            { result: 'hello' },
            { result: 'hello' },
            { result: 'hello' },
            { result: 'hello' },
            { result: 'hello' },
            { result: 'hello' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge'],
    },
    {
        id: 'edge/column-passthrough',
        formula: '=A',
        description: 'Formula that just references a column returns it unchanged',
        columns: { A: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 2 },
            { result: 1 },
            { result: 3 },
            { result: 1 },
            { result: 5 },
            { result: 2 },
            { result: 1 },
            { result: 4 },
            { result: 2 },
            { result: 3 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge'],
    },
    {
        id: 'edge/deeply-nested',
        formula: '=ABS(ROUND(IF(A > 100, A / 3, A * 2), 1))',
        description: 'Deeply nested function calls — ABS(ROUND(IF(...)))',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 200.0 },
            { result: 83.5 },
            { result: 150.0 },
            { result: 166.7 },
            { result: 60.0 },
            { result: 60.0 },
            { result: 140.0 },
            { result: 120.0 },
            { result: 103.3 },
            { result: 50.0 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['edge'],
    },
];
