import { ALL_WAREHOUSES } from '../config';
import type { TestCase } from '../types';

export const logicalCases: TestCase[] = [
    {
        id: 'logical/if-greater-than',
        formula: '=IF(A > 100, "high", "low")',
        description: 'IF with comparison — classify orders by amount',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'low' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'high' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/if-numeric',
        formula: '=IF(A > 200, A * 2, A)',
        description: 'IF with numeric result — double large orders',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 100.00 },
            { result: 501.00 },
            { result: 75.00 },
            { result: 1000.00 },
            { result: 30.00 },
            { result: 180.00 },
            { result: 840.00 },
            { result: 60.00 },
            { result: 620.00 },
            { result: 150.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/nested-if',
        formula: '=IF(A > 200, "high", IF(A > 100, "medium", "low"))',
        description: 'Nested IF for multi-tier classification',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'low' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'low' },
            { result: 'medium' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'medium' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/case-when-with-else',
        formula: '=CASE WHEN A > 100 THEN "high" ELSE "low" END',
        description: 'CASE WHEN with ELSE — classify orders by amount',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'low' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'high' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/case-when-multi-branch',
        formula:
            '=CASE WHEN A > 200 THEN "high" WHEN A > 100 THEN "medium" ELSE "low" END',
        description: 'Multi-branch CASE WHEN — three-tier classification',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'low' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'low' },
            { result: 'medium' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'medium' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/case-when-numeric',
        formula: '=CASE WHEN A > 200 THEN A * 2 ELSE A END',
        description: 'CASE WHEN with numeric result — double large orders',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 100.0 },
            { result: 501.0 },
            { result: 75.0 },
            { result: 1000.0 },
            { result: 30.0 },
            { result: 180.0 },
            { result: 840.0 },
            { result: 60.0 },
            { result: 620.0 },
            { result: 150.0 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/comparison-gte',
        formula: '=A >= 100',
        description: 'Greater-than-or-equal comparison returning boolean',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: true },
            { result: true },
            { result: false },
            { result: true },
            { result: false },
            { result: true },
            { result: true },
            { result: false },
            { result: true },
            { result: true },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical', 'comparison'],
    },
    {
        id: 'logical/comparison-lte',
        formula: '=A <= 100',
        description: 'Less-than-or-equal comparison returning boolean',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: true },
            { result: false },
            { result: true },
            { result: false },
            { result: true },
            { result: false },
            { result: false },
            { result: true },
            { result: false },
            { result: false },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical', 'comparison'],
    },
    {
        id: 'logical/comparison-neq',
        formula: '=A <> 100',
        description: 'Not-equal comparison returning boolean',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: false },
            { result: true },
            { result: true },
            { result: true },
            { result: true },
            { result: true },
            { result: true },
            { result: true },
            { result: true },
            { result: true },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical', 'comparison'],
    },
    {
        id: 'logical/and-operator',
        formula: '=IF(A > 100 AND B > 10, "yes", "no")',
        description: 'AND operator combining two comparisons',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'no' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'yes' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/or-operator',
        formula: '=IF(A > 400 OR B < 5, "yes", "no")',
        description: 'OR operator combining two comparisons',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'no' },
            { result: 'no' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'no' },
            { result: 'no' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/not-operator',
        formula: '=NOT(A > 100)',
        description: 'NOT operator negating a comparison',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: true },
            { result: false },
            { result: true },
            { result: false },
            { result: true },
            { result: false },
            { result: false },
            { result: true },
            { result: false },
            { result: false },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/boolean-literal-true',
        formula: '=IF(TRUE, A, B)',
        description: 'Boolean literal TRUE always selects first branch',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 100.00 },
            { result: 250.50 },
            { result: 75.00 },
            { result: 500.00 },
            { result: 30.00 },
            { result: 180.00 },
            { result: 420.00 },
            { result: 60.00 },
            { result: 310.00 },
            { result: 150.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/boolean-literal-false',
        formula: '=IF(FALSE, A, B)',
        description: 'Boolean literal FALSE always selects second branch',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 10.00 },
            { result: 25.05 },
            { result: 7.50 },
            { result: 50.00 },
            { result: 3.00 },
            { result: 18.00 },
            { result: 42.00 },
            { result: 6.00 },
            { result: 31.00 },
            { result: 15.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/if-two-args',
        formula: '=IF(A > 200, "big")',
        description: 'IF with only 2 arguments — false branch returns NULL',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: null },
            { result: 'big' },
            { result: null },
            { result: 'big' },
            { result: null },
            { result: null },
            { result: 'big' },
            { result: null },
            { result: 'big' },
            { result: null },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/equality',
        formula: '=A = 100',
        description: 'Equality comparison returning boolean',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: true },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical', 'comparison'],
    },
    {
        id: 'logical/string-comparison',
        formula: '=IF(A = "Electronics", "yes", "no")',
        description: 'IF with string equality comparison',
        columns: { A: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'yes' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'no' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical', 'string'],
    },
    {
        id: 'logical/nested-and-or',
        formula: '=IF((A > 100 AND A < 300) OR B > 30, "yes", "no")',
        description: 'Nested AND/OR with parentheses for precedence',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'no' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'yes' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical'],
    },
    {
        id: 'logical/if-with-arithmetic',
        formula: '=IF(A > 100, A - 100, 0)',
        description: 'IF with arithmetic in result branches',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 0 },
            { result: 150.50 },
            { result: 0 },
            { result: 400.00 },
            { result: 0 },
            { result: 80.00 },
            { result: 320.00 },
            { result: 0 },
            { result: 210.00 },
            { result: 50.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['logical', 'arithmetic'],
    },
];
