import { ALL_WAREHOUSES } from '../config';
import type { TestCase } from '../types';

export const mathCases: TestCase[] = [
    {
        id: 'math/abs',
        formula: '=ABS(A - B)',
        description: 'Absolute value of difference',
        columns: { A: 'tax', B: 'discount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 5.00 },
            { result: 12.55 },
            { result: 7.50 },
            { result: 25.00 },
            { result: 1.50 },
            { result: 9.00 },
            { result: 21.00 },
            { result: 3.00 },
            { result: 15.50 },
            { result: 7.50 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/round',
        formula: '=ROUND(A / B, 1)',
        description: 'Round division result to 1 decimal place',
        columns: { A: 'order_amount', B: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 50.0 },
            { result: 250.5 },
            { result: 25.0 },
            { result: 500.0 },
            { result: 6.0 },
            { result: 90.0 },
            { result: 420.0 },
            { result: 15.0 },
            { result: 155.0 },
            { result: 50.0 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/floor',
        formula: '=FLOOR(A / B)',
        description: 'Floor division result',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/ceil',
        formula: '=CEIL(A / B)',
        description: 'Ceiling of division result',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
            { result: 10 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/scalar-min',
        formula: '=MIN(A, B)',
        description: 'Scalar MIN of two columns (LEAST)',
        columns: { A: 'tax', B: 'discount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 5.00 },
            { result: 12.50 },
            { result: 0.00 },
            { result: 25.00 },
            { result: 1.50 },
            { result: 9.00 },
            { result: 21.00 },
            { result: 3.00 },
            { result: 15.50 },
            { result: 7.50 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/scalar-max',
        formula: '=MAX(A, B)',
        description: 'Scalar MAX of two columns (GREATEST)',
        columns: { A: 'tax', B: 'discount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 10.00 },
            { result: 25.05 },
            { result: 7.50 },
            { result: 50.00 },
            { result: 3.00 },
            { result: 18.00 },
            { result: 42.00 },
            { result: 6.00 },
            { result: 31.00 },
            { result: 15.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/nested-abs-floor-ceil',
        formula: '=ABS(FLOOR(A / B) - CEIL(A / B))',
        description: 'Nested math functions: ABS of FLOOR minus CEIL',
        columns: { A: 'order_amount', B: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 0 },
            { result: 1 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
            { result: 0 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/round-no-precision',
        formula: '=ROUND(A / B)',
        description: 'ROUND with no precision argument defaults to 0 decimal places',
        columns: { A: 'order_amount', B: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 50 },
            { result: 251 },
            { result: 25 },
            { result: 500 },
            { result: 6 },
            { result: 90 },
            { result: 420 },
            { result: 15 },
            { result: 155 },
            { result: 50 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/round-two-decimals',
        formula: '=ROUND(A / B, 2)',
        description: 'ROUND to 2 decimal places',
        columns: { A: 'tax', B: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 5.00 },
            { result: 25.05 },
            { result: 2.50 },
            { result: 50.00 },
            { result: 0.60 },
            { result: 9.00 },
            { result: 42.00 },
            { result: 1.50 },
            { result: 15.50 },
            { result: 5.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/abs-of-negative',
        formula: '=ABS(B - A)',
        description: 'ABS of expression that produces negative values',
        columns: { A: 'order_amount', B: 'discount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 95.00 },
            { result: 238.00 },
            { result: 75.00 },
            { result: 475.00 },
            { result: 28.50 },
            { result: 171.00 },
            { result: 399.00 },
            { result: 57.00 },
            { result: 294.50 },
            { result: 142.50 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/min-max-same-value',
        formula: '=MIN(A, A)',
        description: 'Scalar MIN with same column twice returns the value unchanged',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 100.00 },
            { result: 250.50 },
            { result: 75.00 },
            { result: 500.00 },
            { result: 30.00 },
            { result: 180.00 },
            { result: 420.00 },
            { result: 60.00 },
            { result: 310.00 },
            { result: 150.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/floor-of-integer',
        formula: '=FLOOR(A)',
        description: 'FLOOR of integer value returns the same integer',
        columns: { A: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 2 },
            { result: 1 },
            { result: 3 },
            { result: 1 },
            { result: 5 },
            { result: 2 },
            { result: 1 },
            { result: 4 },
            { result: 2 },
            { result: 3 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
    {
        id: 'math/ceil-of-integer',
        formula: '=CEIL(A)',
        description: 'CEIL of integer value returns the same integer',
        columns: { A: 'quantity' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 2 },
            { result: 1 },
            { result: 3 },
            { result: 1 },
            { result: 5 },
            { result: 2 },
            { result: 1 },
            { result: 4 },
            { result: 2 },
            { result: 3 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['math'],
    },
];
