import { ALL_WAREHOUSES } from '../config';
import type { TestCase } from '../types';

export const nullHandlingCases: TestCase[] = [
    {
        id: 'null/last-day',
        formula: '=DAY(LAST_DAY(A))',
        description:
            'LAST_DAY propagates NULL end-to-end: for NULL inputs, downstream DAY() also yields NULL',
        columns: { A: 'val_d' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 31 },
            { result: null },
            { result: 31 },
            { result: null },
            { result: 31 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null', 'date'],
    },
    {
        id: 'null/date-trunc',
        formula: '=YEAR(DATE_TRUNC("month", A))',
        description:
            'DATE_TRUNC propagates NULL end-to-end: for NULL inputs, downstream YEAR() also yields NULL',
        columns: { A: 'val_d' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 2024 },
            { result: null },
            { result: 2024 },
            { result: null },
            { result: 2024 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null', 'date'],
    },
    {
        id: 'null/coalesce-two',
        formula: '=COALESCE(A, 0)',
        description: 'Replace NULL with default value',
        columns: { A: 'val_a' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 10.00 },
            { result: 0 },
            { result: 30.00 },
            { result: 0 },
            { result: 50.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null'],
    },
    {
        id: 'null/isnull',
        formula: '=ISNULL(A)',
        description: 'Check if value is NULL',
        columns: { A: 'val_a' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: false },
            { result: true },
            { result: false },
            { result: true },
            { result: false },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null'],
    },
    {
        id: 'null/arithmetic-with-null',
        formula: '=A + C',
        description: 'Arithmetic with NULL propagates NULL',
        columns: { A: 'val_a', C: 'val_c' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 110.00 },
            { result: null },
            { result: 330.00 },
            { result: null },
            { result: 550.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null', 'arithmetic'],
    },
    {
        id: 'null/coalesce-three-args',
        formula: '=COALESCE(A, C, -1)',
        description: 'COALESCE with three arguments',
        columns: { A: 'val_a', C: 'val_c' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 10.00 },
            { result: 200 },
            { result: 30.00 },
            { result: 400 },
            { result: 50.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null'],
    },
    {
        id: 'null/isnull-with-if',
        formula: '=IF(ISNULL(A), 0, A)',
        description: 'IF combined with ISNULL to replace NULLs',
        columns: { A: 'val_a' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 10.00 },
            { result: 0 },
            { result: 30.00 },
            { result: 0 },
            { result: 50.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null', 'logical'],
    },
    {
        id: 'null/division-with-null-divisor',
        formula: '=C / A',
        description: 'Division where divisor can be NULL propagates NULL',
        columns: { A: 'val_a', C: 'val_c' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 10.00 },
            { result: null },
            { result: 10.00 },
            { result: null },
            { result: 10.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null', 'arithmetic'],
    },
    {
        id: 'null/multiply-with-null',
        formula: '=A * 2',
        description: 'Multiplication with NULL propagates NULL',
        columns: { A: 'val_a' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 20.00 },
            { result: null },
            { result: 60.00 },
            { result: null },
            { result: 100.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null', 'arithmetic'],
    },
    {
        id: 'null/isnull-string-column',
        formula: '=ISNULL(A)',
        description: 'ISNULL on string column with NULLs',
        columns: { A: 'val_b' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: false },
            { result: false },
            { result: true },
            { result: true },
            { result: false },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null', 'string'],
    },
    {
        id: 'null/coalesce-string',
        formula: '=COALESCE(A, "unknown")',
        description: 'COALESCE on string column replaces NULL with default',
        columns: { A: 'val_b' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 'hello' },
            { result: 'world' },
            { result: 'unknown' },
            { result: 'unknown' },
            { result: 'test' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null', 'string'],
    },
    {
        id: 'null/if-null-comparison',
        formula: '=IF(ISNULL(A) AND ISNULL(B), "both null", "has value")',
        description: 'Combining ISNULL checks with AND',
        columns: { A: 'val_a', B: 'val_b' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 'has value' },
            { result: 'has value' },
            { result: 'has value' },
            { result: 'both null' },
            { result: 'has value' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['null', 'logical'],
    },
];
