import { ALL_WAREHOUSES } from '../config';
import type { TestCase } from '../types';

// Helper: 10 rows all returning the same value (test_orders has 10 rows)
const tenRows = (value: any) =>
    Array.from({ length: 10 }, () => ({ result: value }));

export const parenthesesCases: TestCase[] = [
    // ── Pure literal arithmetic with parens ──────────────────────────
    {
        id: 'parens/literal-nested',
        formula: '=(5 * (1 + 3))',
        description: 'Nested parentheses with pure literals',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows(20),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['parentheses'],
    },
    {
        id: 'parens/literal-triple-nested',
        formula: '=(((1 + 2)))',
        description: 'Redundant triple-nested parentheses with literals',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows(3),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['parentheses'],
    },
    {
        id: 'parens/literal-complex',
        formula: '=((2 + 3) * (4 - 1)) / 3',
        description: 'Complex literal expression with multiple paren groups',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows(5),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['parentheses'],
    },

    // ── Parens changing operator precedence ──────────────────────────
    {
        id: 'parens/precedence-add-before-multiply',
        formula: '=A * (B + C)',
        description: 'Parens force addition before multiplication',
        columns: { A: 'order_amount', B: 'tax', C: 'discount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 1500 },
            { result: 9406.275 },
            { result: 562.5 },
            { result: 37500 },
            { result: 135 },
            { result: 4860 },
            { result: 26460 },
            { result: 540 },
            { result: 14415 },
            { result: 3375 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['parentheses'],
    },

    // ── Deeply nested column expressions ─────────────────────────────
    {
        id: 'parens/deeply-nested-columns',
        formula: '=((A + B) * (A - C)) / 2',
        description: 'Deeply nested grouping with columns',
        columns: { A: 'order_amount', B: 'tax', C: 'discount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 5225 },
            { result: 32790.45 },
            { result: 3093.75 },
            { result: 130625 },
            { result: 470.25 },
            { result: 16929 },
            { result: 92169 },
            { result: 1881 },
            { result: 50212.25 },
            { result: 11756.25 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['parentheses'],
    },

    // ── Redundant parens around columns ──────────────────────────────
    {
        id: 'parens/redundant-column',
        formula: '=((A))',
        description: 'Redundant parentheses around a single column',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 100.00 },
            { result: 250.50 },
            { result: 75.00 },
            { result: 500.00 },
            { result: 30.00 },
            { result: 180.00 },
            { result: 420.00 },
            { result: 60.00 },
            { result: 310.00 },
            { result: 150.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['parentheses'],
    },

    // ── Parens with comparisons and logical ops ──────────────────────
    {
        id: 'parens/logical-grouping',
        formula: '=IF((A > 100) AND (B < 20), "yes", "no")',
        description: 'Parentheses around comparison operands in logical expression',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'no' },
            { result: 'no' },
            { result: 'no' },
            { result: 'no' },
            { result: 'no' },
            { result: 'yes' },
            { result: 'no' },
            { result: 'no' },
            { result: 'no' },
            { result: 'yes' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['parentheses'],
    },

    // ── Parens with functions ────────────────────────────────────────
    {
        id: 'parens/around-function-result',
        formula: '=(ABS(A) + ABS(B)) * 2',
        description: 'Parentheses grouping function results',
        columns: { A: 'order_amount', B: 'tax' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 220.00 },
            { result: 551.10 },
            { result: 165.00 },
            { result: 1100.00 },
            { result: 66.00 },
            { result: 396.00 },
            { result: 924.00 },
            { result: 132.00 },
            { result: 682.00 },
            { result: 330.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['parentheses'],
    },

    // ── Parens with unary minus ──────────────────────────────────────
    {
        id: 'parens/unary-minus-in-expression',
        formula: '=(-A) * (B + C)',
        description: 'Unary minus inside parentheses combined with grouped addition',
        columns: { A: 'order_amount', B: 'tax', C: 'discount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: -1500 },
            { result: -9406.275 },
            { result: -562.5 },
            { result: -37500 },
            { result: -135 },
            { result: -4860 },
            { result: -26460 },
            { result: -540 },
            { result: -14415 },
            { result: -3375 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['parentheses'],
    },
];
