import { ALL_WAREHOUSES } from '../config';
import type { TestCase } from '../types';

export const stringCases: TestCase[] = [
    {
        id: 'string/concat-two-columns',
        formula: '=CONCAT(A, B)',
        description: 'Concatenate two string columns',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'AliceElectronics' },
            { result: 'BobClothing' },
            { result: 'CharlieElectronics' },
            { result: 'DianaFurniture' },
            { result: 'EveClothing' },
            { result: 'FrankElectronics' },
            { result: 'GraceFurniture' },
            { result: 'HenryClothing' },
            { result: 'IvyElectronics' },
            { result: 'JackFurniture' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/lower',
        formula: '=LOWER(A)',
        description: 'Convert to lowercase',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'alice' },
            { result: 'bob' },
            { result: 'charlie' },
            { result: 'diana' },
            { result: 'eve' },
            { result: 'frank' },
            { result: 'grace' },
            { result: 'henry' },
            { result: 'ivy' },
            { result: 'jack' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/upper',
        formula: '=UPPER(A)',
        description: 'Convert to uppercase',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'ALICE' },
            { result: 'BOB' },
            { result: 'CHARLIE' },
            { result: 'DIANA' },
            { result: 'EVE' },
            { result: 'FRANK' },
            { result: 'GRACE' },
            { result: 'HENRY' },
            { result: 'IVY' },
            { result: 'JACK' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/length',
        formula: '=LEN(A)',
        description: 'String length',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 5 },
            { result: 3 },
            { result: 7 },
            { result: 5 },
            { result: 3 },
            { result: 5 },
            { result: 5 },
            { result: 5 },
            { result: 3 },
            { result: 4 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/trim',
        formula: '=TRIM(A)',
        description: 'Trim whitespace from string',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice' },
            { result: 'Bob' },
            { result: 'Charlie' },
            { result: 'Diana' },
            { result: 'Eve' },
            { result: 'Frank' },
            { result: 'Grace' },
            { result: 'Henry' },
            { result: 'Ivy' },
            { result: 'Jack' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/concat-with-literal',
        formula: '=CONCAT(A, " - ", B)',
        description: 'Concatenate columns with literal separator',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice - Electronics' },
            { result: 'Bob - Clothing' },
            { result: 'Charlie - Electronics' },
            { result: 'Diana - Furniture' },
            { result: 'Eve - Clothing' },
            { result: 'Frank - Electronics' },
            { result: 'Grace - Furniture' },
            { result: 'Henry - Clothing' },
            { result: 'Ivy - Electronics' },
            { result: 'Jack - Furniture' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/concat-three-args',
        formula: '=CONCAT(A, " ", B)',
        description: 'Concatenate with three arguments including literal space',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice Electronics' },
            { result: 'Bob Clothing' },
            { result: 'Charlie Electronics' },
            { result: 'Diana Furniture' },
            { result: 'Eve Clothing' },
            { result: 'Frank Electronics' },
            { result: 'Grace Furniture' },
            { result: 'Henry Clothing' },
            { result: 'Ivy Electronics' },
            { result: 'Jack Furniture' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/nested-upper-trim',
        formula: '=UPPER(TRIM(A))',
        description: 'Nested string functions — UPPER of TRIM',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'ALICE' },
            { result: 'BOB' },
            { result: 'CHARLIE' },
            { result: 'DIANA' },
            { result: 'EVE' },
            { result: 'FRANK' },
            { result: 'GRACE' },
            { result: 'HENRY' },
            { result: 'IVY' },
            { result: 'JACK' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/lower-concat',
        formula: '=LOWER(CONCAT(A, B))',
        description: 'LOWER applied to concatenated string',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'aliceelectronics' },
            { result: 'bobclothing' },
            { result: 'charlieelectronics' },
            { result: 'dianafurniture' },
            { result: 'eveclothing' },
            { result: 'frankelectronics' },
            { result: 'gracefurniture' },
            { result: 'henryclothing' },
            { result: 'ivyelectronics' },
            { result: 'jackfurniture' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/len-of-concat',
        formula: '=LEN(CONCAT(A, B))',
        description: 'Length of concatenated string',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 16 },
            { result: 11 },
            { result: 18 },
            { result: 14 },
            { result: 11 },
            { result: 16 },
            { result: 14 },
            { result: 13 },
            { result: 14 },
            { result: 13 },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/left',
        formula: '=LEFT(A, 3)',
        description: 'Leftmost N characters; returns the whole string when N >= length',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Ali' },
            { result: 'Bob' },
            { result: 'Cha' },
            { result: 'Dia' },
            { result: 'Eve' },
            { result: 'Fra' },
            { result: 'Gra' },
            { result: 'Hen' },
            { result: 'Ivy' },
            { result: 'Jac' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/right',
        formula: '=RIGHT(A, 3)',
        description: 'Rightmost N characters',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'ice' },
            { result: 'Bob' },
            { result: 'lie' },
            { result: 'ana' },
            { result: 'Eve' },
            { result: 'ank' },
            { result: 'ace' },
            { result: 'nry' },
            { result: 'Ivy' },
            { result: 'ack' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/substring',
        formula: '=SUBSTRING(A, 2, 3)',
        description: 'Extract substring by 1-indexed start and length',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'lic' },
            { result: 'ob' },
            { result: 'har' },
            { result: 'ian' },
            { result: 've' },
            { result: 'ran' },
            { result: 'rac' },
            { result: 'enr' },
            { result: 'vy' },
            { result: 'ack' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/replace',
        formula: '=REPLACE(A, "a", "X")',
        description: 'Case-sensitive replace of all occurrences',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice' },
            { result: 'Bob' },
            { result: 'ChXrlie' },
            { result: 'DiXnX' },
            { result: 'Eve' },
            { result: 'FrXnk' },
            { result: 'GrXce' },
            { result: 'Henry' },
            { result: 'Ivy' },
            { result: 'JXck' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/replace-empty-replacement',
        formula: '=REPLACE(A, "o", "")',
        description: 'Empty replacement removes every occurrence of the needle',
        columns: { A: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Electrnics' },
            { result: 'Clthing' },
            { result: 'Electrnics' },
            { result: 'Furniture' },
            { result: 'Clthing' },
            { result: 'Electrnics' },
            { result: 'Furniture' },
            { result: 'Clthing' },
            { result: 'Electrnics' },
            { result: 'Furniture' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/replace-url-prefix',
        formula: '=REPLACE(CONCAT("https://", A), "https://", "")',
        description: 'REPLACE composed with CONCAT — strip a known prefix (the use case the AI generator hits most)',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice' },
            { result: 'Bob' },
            { result: 'Charlie' },
            { result: 'Diana' },
            { result: 'Eve' },
            { result: 'Frank' },
            { result: 'Grace' },
            { result: 'Henry' },
            { result: 'Ivy' },
            { result: 'Jack' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/replace-of-lower',
        formula: '=REPLACE(LOWER(A), "a", "X")',
        description: 'REPLACE composed with LOWER — replace lowercased chars',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Xlice' },
            { result: 'bob' },
            { result: 'chXrlie' },
            { result: 'diXnX' },
            { result: 'eve' },
            { result: 'frXnk' },
            { result: 'grXce' },
            { result: 'henry' },
            { result: 'ivy' },
            { result: 'jXck' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/left-of-concat',
        formula: '=LEFT(CONCAT(A, "-", B), 7)',
        description: 'LEFT applied to a CONCAT result',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice-E' },
            { result: 'Bob-Clo' },
            { result: 'Charlie' },
            { result: 'Diana-F' },
            { result: 'Eve-Clo' },
            { result: 'Frank-E' },
            { result: 'Grace-F' },
            { result: 'Henry-C' },
            { result: 'Ivy-Ele' },
            { result: 'Jack-Fu' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/split-part-first',
        formula: '=SPLIT_PART(CONCAT(A, "@", B), "@", 1)',
        description: 'SPLIT_PART returns the part before the delimiter',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice' },
            { result: 'Bob' },
            { result: 'Charlie' },
            { result: 'Diana' },
            { result: 'Eve' },
            { result: 'Frank' },
            { result: 'Grace' },
            { result: 'Henry' },
            { result: 'Ivy' },
            { result: 'Jack' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/split-part-second',
        formula: '=SPLIT_PART(CONCAT(A, "@", B), "@", 2)',
        description: 'SPLIT_PART returns the part after the delimiter',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Electronics' },
            { result: 'Clothing' },
            { result: 'Electronics' },
            { result: 'Furniture' },
            { result: 'Clothing' },
            { result: 'Electronics' },
            { result: 'Furniture' },
            { result: 'Clothing' },
            { result: 'Electronics' },
            { result: 'Furniture' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/strpos-found',
        formula: '=STRPOS(A, "e")',
        description: 'STRPOS returns 1-indexed position of substring (0 when not found)',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 5 }, // Alic[e]
            { result: 0 }, // Bob — no e
            { result: 7 }, // Charli[e]
            { result: 0 }, // Diana — no lowercase e
            { result: 3 }, // Ev[e]
            { result: 0 }, // Frank — no e
            { result: 5 }, // Grac[e]
            { result: 2 }, // H[e]nry
            { result: 0 }, // Ivy — no e
            { result: 0 }, // Jack — no e
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/starts-with-true-and-false',
        formula: '=STARTS_WITH(A, "J")',
        description: 'STARTS_WITH returns boolean — only Jack starts with J',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: false },
            { result: true },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/starts-with-inside-if',
        formula:
            '=IF(STARTS_WITH(A, "J"), "j-name", "other")',
        description: 'STARTS_WITH inside IF condition returns string per branch',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'other' },
            { result: 'other' },
            { result: 'other' },
            { result: 'other' },
            { result: 'other' },
            { result: 'other' },
            { result: 'other' },
            { result: 'other' },
            { result: 'other' },
            { result: 'j-name' },
        ],
        warehouses: ALL_WAREHOUSES,
        tier: 1,
        tags: ['string'],
    },
];
