import type { TestCase } from '../types';

export const stringCases: TestCase[] = [
    {
        id: 'string/concat-two-columns',
        formula: '=CONCAT(A, B)',
        description: 'Concatenate two string columns',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'AliceElectronics' },
            { result: 'BobClothing' },
            { result: 'CharlieElectronics' },
            { result: 'DianaFurniture' },
            { result: 'EveClothing' },
            { result: 'FrankElectronics' },
            { result: 'GraceFurniture' },
            { result: 'HenryClothing' },
            { result: 'IvyElectronics' },
            { result: 'JackFurniture' },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/lower',
        formula: '=LOWER(A)',
        description: 'Convert to lowercase',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'alice' },
            { result: 'bob' },
            { result: 'charlie' },
            { result: 'diana' },
            { result: 'eve' },
            { result: 'frank' },
            { result: 'grace' },
            { result: 'henry' },
            { result: 'ivy' },
            { result: 'jack' },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/upper',
        formula: '=UPPER(A)',
        description: 'Convert to uppercase',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'ALICE' },
            { result: 'BOB' },
            { result: 'CHARLIE' },
            { result: 'DIANA' },
            { result: 'EVE' },
            { result: 'FRANK' },
            { result: 'GRACE' },
            { result: 'HENRY' },
            { result: 'IVY' },
            { result: 'JACK' },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/length',
        formula: '=LEN(A)',
        description: 'String length',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 5 },
            { result: 3 },
            { result: 7 },
            { result: 5 },
            { result: 3 },
            { result: 5 },
            { result: 5 },
            { result: 5 },
            { result: 3 },
            { result: 4 },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/trim',
        formula: '=TRIM(A)',
        description: 'Trim whitespace from string',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice' },
            { result: 'Bob' },
            { result: 'Charlie' },
            { result: 'Diana' },
            { result: 'Eve' },
            { result: 'Frank' },
            { result: 'Grace' },
            { result: 'Henry' },
            { result: 'Ivy' },
            { result: 'Jack' },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/concat-with-literal',
        formula: '=CONCAT(A, " - ", B)',
        description: 'Concatenate columns with literal separator',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice - Electronics' },
            { result: 'Bob - Clothing' },
            { result: 'Charlie - Electronics' },
            { result: 'Diana - Furniture' },
            { result: 'Eve - Clothing' },
            { result: 'Frank - Electronics' },
            { result: 'Grace - Furniture' },
            { result: 'Henry - Clothing' },
            { result: 'Ivy - Electronics' },
            { result: 'Jack - Furniture' },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/concat-three-args',
        formula: '=CONCAT(A, " ", B)',
        description: 'Concatenate with three arguments including literal space',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'Alice Electronics' },
            { result: 'Bob Clothing' },
            { result: 'Charlie Electronics' },
            { result: 'Diana Furniture' },
            { result: 'Eve Clothing' },
            { result: 'Frank Electronics' },
            { result: 'Grace Furniture' },
            { result: 'Henry Clothing' },
            { result: 'Ivy Electronics' },
            { result: 'Jack Furniture' },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/nested-upper-trim',
        formula: '=UPPER(TRIM(A))',
        description: 'Nested string functions — UPPER of TRIM',
        columns: { A: 'customer_name' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'ALICE' },
            { result: 'BOB' },
            { result: 'CHARLIE' },
            { result: 'DIANA' },
            { result: 'EVE' },
            { result: 'FRANK' },
            { result: 'GRACE' },
            { result: 'HENRY' },
            { result: 'IVY' },
            { result: 'JACK' },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/lower-concat',
        formula: '=LOWER(CONCAT(A, B))',
        description: 'LOWER applied to concatenated string',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 'aliceelectronics' },
            { result: 'bobclothing' },
            { result: 'charlieelectronics' },
            { result: 'dianafurniture' },
            { result: 'eveclothing' },
            { result: 'frankelectronics' },
            { result: 'gracefurniture' },
            { result: 'henryclothing' },
            { result: 'ivyelectronics' },
            { result: 'jackfurniture' },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['string'],
    },
    {
        id: 'string/len-of-concat',
        formula: '=LEN(CONCAT(A, B))',
        description: 'Length of concatenated string',
        columns: { A: 'customer_name', B: 'category' },
        sourceTable: 'test_orders',
        orderBy: 'id',
        expectedRows: [
            { result: 16 },
            { result: 11 },
            { result: 18 },
            { result: 14 },
            { result: 11 },
            { result: 16 },
            { result: 14 },
            { result: 13 },
            { result: 14 },
            { result: 13 },
        ],
        warehouses: ['duckdb', 'postgres', 'bigquery', 'snowflake'],
        tier: 1,
        tags: ['string'],
    },
];
