name: Setup Node, PNPM, and Cypress

description: Sets up Node.js, PNPM, and Cypress.

runs:
    using: 'composite'
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - uses: pnpm/action-setup@v4
          with:
              version: 9

        - uses: actions/setup-node@v4
          with:
              node-version: '20'
              cache: 'pnpm'
              cache-dependency-path: 'pnpm-lock.yaml'

        - name: Install Dependencies
          run: pnpm install --frozen-lockfile --prefer-offline
          shell: bash

        - uses: actions/cache@v4
          with:
              path: ~/.cache/Cypress
              key: cypress-${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}

        - uses: cypress-io/github-action@v6
          with:
              runTests: false

        - run: pnpm cypress verify || pnpm cypress install
          working-directory: packages/e2e
          shell: bash
