name: Setup Node, PNPM, and Cypress

description: Sets up Node.js, PNPM, and Cypress.

runs:
    using: 'composite'
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup PNPM
          uses: pnpm/action-setup@v4
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
              node-version: '20'
              cache: 'pnpm'
              cache-dependency-path: 'pnpm-lock.yaml'

        - name: Install Dependencies
          run: pnpm install --frozen-lockfile --prefer-offline
          shell: bash

        - name: Install Cypress
          run: pnpm exec cypress install
          working-directory: packages/e2e
          shell: bash
