name: Setup Node, PNPM, and Playwright

description: Sets up Node.js, PNPM, and Playwright browsers.

runs:
    using: 'composite'
    steps:
        - name: Checkout
          uses: actions/checkout@v6

        - name: Setup PNPM
          uses: pnpm/action-setup@v5
        - name: Setup Node
          uses: actions/setup-node@v6
          with:
              node-version-file: '.nvmrc'
              cache: 'pnpm'
              cache-dependency-path: 'pnpm-lock.yaml'

        - name: Install Dependencies
          run: pnpm install --frozen-lockfile --prefer-offline
          shell: bash

        - name: Install Playwright Browsers
          run: pnpm exec playwright install --with-deps chromium
          working-directory: packages/e2e
          shell: bash
