name: Setup Node, PNPM, and Playwright

description: Sets up Node.js, PNPM, and Playwright browsers.

runs:
    using: 'composite'
    steps:
        - name: Checkout
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

        - name: Setup Socket Firewall
          uses: socketdev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
          with:
              mode: firewall-free

        - name: Setup PNPM
          uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        - name: Setup Node
          uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
          with:
              node-version-file: '.nvmrc'
              cache: 'pnpm'
              cache-dependency-path: 'pnpm-lock.yaml'

        - name: Install Dependencies
          run: sfw pnpm install --frozen-lockfile --prefer-offline
          shell: bash

        - name: Install Playwright Browsers
          run: sfw pnpm exec playwright install --with-deps chromium
          working-directory: packages/e2e
          shell: bash
