import {
    SEED_ORG_1_ADMIN_EMAIL,
    SEED_ORG_1_ADMIN_PASSWORD,
    SEED_PROJECT,
    type CreateChartInSpace,
    type CreateEmbedJwt,
    type CreatePersonalAccessToken,
    type CreateWarehouseCredentials,
    type DashboardBasicDetails,
    type OrganizationProject,
    type SavedChart,
} from '@lightdash/common';
import type { APIRequestContext } from '@playwright/test';
import { expect } from '@playwright/test';

/**
 * Get a personal access token.
 * Equivalent to cy.getApiToken()
 */
export async function getApiToken(request: APIRequestContext): Promise<string> {
    const createToken: CreatePersonalAccessToken = {
        description: 'e2e',
        autoGenerated: true,
        expiresAt: null,
    };
    const response = await request.post(
        'api/v1/user/me/personal-access-tokens',
        {
            headers: { 'Content-type': 'application/json' },
            data: createToken,
        },
    );
    expect(response.status()).toBe(200);
    const body = await response.json();
    return body.results.token;
}

/**
 * Get a JWT token for embedded dashboards.
 * Equivalent to cy.getJwtToken(projectUuid, options)
 */
export async function getJwtToken(
    request: APIRequestContext,
    projectUuid: string,
    options: {
        userEmail?: string;
        userExternalId?: string | null;
        canExportCsv?: boolean;
        canExportImages?: boolean;
        canExportPagePdf?: boolean;
        canDateZoom?: boolean;
        canExplore?: boolean;
    } = {},
): Promise<string> {
    const {
        userEmail = 'test@example.com',
        userExternalId = 'test-user-123',
        canExportCsv = false,
        canExportImages = false,
        canExportPagePdf = false,
        canDateZoom = false,
        canExplore = false,
    } = options;

    // First login as admin to get embed configuration
    const loginResponse = await request.post('api/v1/login', {
        data: {
            email: SEED_ORG_1_ADMIN_EMAIL.email,
            password: SEED_ORG_1_ADMIN_PASSWORD.password,
        },
    });
    expect(loginResponse.status()).toBe(200);

    // Get a dashboard UUID from the project
    const dashboardsResponse = await request.get(
        `api/v1/projects/${projectUuid}/dashboards`,
    );
    expect(dashboardsResponse.status()).toBe(200);
    const dashboardsBody = await dashboardsResponse.json();
    expect(dashboardsBody.results.length).toBeGreaterThan(0);
    const dashboardUuid = dashboardsBody.results[0].uuid;

    // Get embed configuration
    const configResponse = await request.get(
        `api/v1/embed/${projectUuid}/config`,
    );
    expect(configResponse.status()).toBe(200);

    // Create JWT data structure
    const jwtData: CreateEmbedJwt = {
        content: {
            type: 'dashboard',
            projectUuid,
            dashboardUuid,
            canExportCsv,
            canExportImages,
            canExportPagePdf,
            canDateZoom,
            canExplore,
        },
        userAttributes: {
            email: userEmail,
            externalId: userExternalId || '',
        },
        user: {
            email: userEmail,
            externalId: userExternalId || undefined,
        },
        expiresIn: '1h',
    };

    // Create embed URL to get the JWT token
    const embedUrlResponse = await request.post(
        `api/v1/embed/${projectUuid}/get-embed-url`,
        {
            headers: { 'Content-Type': 'application/json' },
            data: jwtData,
        },
    );
    expect(embedUrlResponse.status()).toBe(200);
    const embedBody = await embedUrlResponse.json();
    const { url } = embedBody.results;
    const jwtToken = url.split('#')[1];

    // Logout to clear session
    await request.get('api/v1/logout');

    return jwtToken;
}

/**
 * Delete projects by name.
 * Equivalent to cy.deleteProjectsByName(names)
 */
export async function deleteProjectsByName(
    request: APIRequestContext,
    names: string[],
): Promise<void> {
    const response = await request.get('api/v1/org/projects', {
        headers: { 'Content-type': 'application/json' },
    });
    expect(response.status()).toBe(200);
    const body = await response.json();

    // eslint-disable-next-line no-restricted-syntax
    for (const { projectUuid, name } of body.results as OrganizationProject[]) {
        if (names.includes(name)) {
            // eslint-disable-next-line no-await-in-loop
            const deleteResponse = await request.delete(
                `api/v1/org/projects/${projectUuid}`,
                { headers: { 'Content-type': 'application/json' } },
            );
            expect(deleteResponse.status()).toBe(200);
        }
    }
}

/**
 * Delete dashboards by name.
 * Equivalent to cy.deleteDashboardsByName(names)
 */
export async function deleteDashboardsByName(
    request: APIRequestContext,
    names: string[],
): Promise<void> {
    const response = await request.get(
        `api/v1/projects/${SEED_PROJECT.project_uuid}/dashboards`,
    );
    expect(response.status()).toBe(200);
    const body = await response.json();

    // eslint-disable-next-line no-restricted-syntax
    for (const { uuid, name } of body.results as DashboardBasicDetails[]) {
        if (names.includes(name)) {
            // eslint-disable-next-line no-await-in-loop
            const deleteResponse = await request.delete(
                `api/v1/dashboards/${uuid}`,
                { headers: { 'Content-type': 'application/json' } },
            );
            expect(deleteResponse.status()).toBe(200);
        }
    }
}

/**
 * Delete charts by name.
 * Equivalent to cy.deleteChartsByName(names)
 */
export async function deleteChartsByName(
    request: APIRequestContext,
    names: string[],
): Promise<void> {
    const response = await request.get(
        `api/v1/projects/${SEED_PROJECT.project_uuid}/charts`,
        { headers: { 'Content-type': 'application/json' } },
    );
    expect(response.status()).toBe(200);
    const body = await response.json();

    // eslint-disable-next-line no-restricted-syntax
    for (const { uuid, name } of body.results) {
        if (names.includes(name)) {
            // eslint-disable-next-line no-await-in-loop
            const deleteResponse = await request.delete(
                `api/v1/saved/${uuid}`,
                { headers: { 'Content-type': 'application/json' } },
            );
            expect(deleteResponse.status()).toBe(200);
        }
    }
}

/**
 * Create a project.
 * Equivalent to cy.createProject(projectName, warehouseConfig)
 */
export async function createProject(
    request: APIRequestContext,
    projectName: string,
    warehouseConfig: CreateWarehouseCredentials,
): Promise<string> {
    const response = await request.post('api/v1/org/projects', {
        headers: { 'Content-type': 'application/json' },
        data: {
            name: projectName,
            type: 'DEFAULT',
            dbtConnection: {
                target: '',
                environment: [],
                type: 'dbt',
                project_dir: process.env.DBT_PROJECT_DIR || '',
            },
            dbtVersion: 'v1.7',
            warehouseConnection: warehouseConfig || {
                host: process.env.PGHOST || 'localhost',
                user: 'postgres',
                password: process.env.PGPASSWORD || 'password',
                dbname: 'postgres',
                searchPath: '',
                role: '',
                sshTunnelHost: '',
                sshTunnelUser: '',
                schema: 'jaffle',
                port: 5432,
                keepalivesIdle: 0,
                sslmode: 'disable',
                sshTunnelPort: 22,
                requireUserCredentials: false,
                type: 'postgres',
            },
        },
    });
    expect(response.status()).toBe(200);
    const body = await response.json();
    return body.results.project.projectUuid;
}

/**
 * Create a space in a project.
 * Equivalent to cy.createSpace(projectUuid, spaceName)
 */
export async function createSpace(
    request: APIRequestContext,
    projectUuid: string,
    spaceName: string,
): Promise<string> {
    const response = await request.post(
        `api/v1/projects/${projectUuid}/spaces/`,
        {
            headers: { 'Content-type': 'application/json' },
            data: { name: spaceName },
        },
    );
    expect(response.status()).toBe(200);
    const body = await response.json();
    return body.results.uuid;
}

/**
 * Create a chart in a space.
 * Equivalent to cy.createChartInSpace(projectUuid, body)
 */
export async function createChartInSpace(
    request: APIRequestContext,
    projectUuid: string,
    body: CreateChartInSpace,
): Promise<SavedChart> {
    const response = await request.post(
        `api/v1/projects/${projectUuid}/saved`,
        { data: body },
    );
    expect(response.status()).toBe(200);
    const responseBody = await response.json();
    return responseBody.results;
}
