export const legacyProfiles: Record<string, string> = {
    'BigQuery private_key':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: bigquery\n      project: billing-project\n      dataset: analytics\n      threads: 1\n      timeout_seconds: 120\n      priority: batch\n      retries: 3\n      maximum_bytes_billed: 12345\n      execution_project: execution-project\n      method: service-account-json\n      keyfile_json:\n        type: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_TYPE'') }}'\n        project_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PROJECT_ID'') }}'\n        private_key: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PRIVATE_KEY'') }}'\n        client_email: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CLIENT_EMAIL'') }}'\n        token_uri: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_TOKEN_URI'') }}'\n",
    'BigQuery undefined':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: bigquery\n      project: billing-project\n      dataset: analytics\n      threads: 1\n      timeout_seconds: 120\n      priority: batch\n      retries: 3\n      maximum_bytes_billed: 12345\n      execution_project: execution-project\n      method: service-account-json\n      keyfile_json:\n        type: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_TYPE'') }}'\n        project_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PROJECT_ID'') }}'\n        private_key: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PRIVATE_KEY'') }}'\n        client_email: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CLIENT_EMAIL'') }}'\n        token_uri: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_TOKEN_URI'') }}'\n",
    'BigQuery resolved SSO':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: bigquery\n      project: billing-project\n      dataset: analytics\n      threads: 1\n      timeout_seconds: 120\n      priority: batch\n      retries: 3\n      maximum_bytes_billed: 12345\n      execution_project: execution-project\n      method: service-account-json\n      keyfile_json:\n        type: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_TYPE'') }}'\n        client_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CLIENT_ID'') }}'\n        client_secret: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CLIENT_SECRET'') }}'\n        refresh_token: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_REFRESH_TOKEN'') }}'\n",
    'BigQuery ADC':
        'lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: bigquery\n      project: billing-project\n      dataset: analytics\n      threads: 1\n      timeout_seconds: 120\n      priority: batch\n      retries: 3\n      maximum_bytes_billed: 12345\n      execution_project: execution-project\n      method: oauth\n',
    'Postgres password':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: postgres\n      host: db.example.test\n      user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_USER'') }}'\n      password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PASSWORD'') }}'\n      port: 5432\n      dbname: warehouse\n      schema: analytics\n      threads: 1\n      keepalives_idle: 15\n      search_path: public,analytics\n      role: reader\n      sslmode: verify-full\n",
    'Postgres RDS CA':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: postgres\n      host: cluster.rds.amazonaws.com\n      user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_USER'') }}'\n      password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PASSWORD'') }}'\n      port: 5432\n      dbname: warehouse\n      schema: analytics\n      threads: 1\n      keepalives_idle: 15\n      sslmode: verify-full\n      sslrootcert: >-\n        <CA_BUNDLE_DIR>/ca-bundle-aws-rds-global.pem\n",
    'Redshift password':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: redshift\n      host: db.example.test\n      port: 5432\n      dbname: warehouse\n      schema: analytics\n      threads: 1\n      keepalives_idle: 15\n      sslmode: verify-full\n      sslrootcert: >-\n        <CA_BUNDLE_DIR>/ca-bundle-aws-redshift.crt\n      ra3_node: true\n      user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_USER'') }}'\n      password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PASSWORD'') }}'\n",
    'Redshift IAM with keys':
        'lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: redshift\n      host: db.example.test\n      port: 5432\n      dbname: warehouse\n      schema: analytics\n      threads: 1\n      keepalives_idle: 15\n      sslmode: verify-full\n      sslrootcert: >-\n        <CA_BUNDLE_DIR>/ca-bundle-aws-redshift.crt\n      ra3_node: true\n      method: iam\n      region: eu-west-1\n      cluster_id: cluster\n      user: warehouse-user\n      autocreate: true\n      db_groups:\n        - readers\n',
    'Redshift IAM with session keys':
        'lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: redshift\n      host: db.example.test\n      port: 5432\n      dbname: warehouse\n      schema: analytics\n      threads: 1\n      keepalives_idle: 15\n      sslmode: verify-full\n      sslrootcert: >-\n        <CA_BUNDLE_DIR>/ca-bundle-aws-redshift.crt\n      ra3_node: true\n      method: iam\n      region: eu-west-1\n      cluster_id: cluster\n      user: warehouse-user\n      autocreate: true\n      db_groups:\n        - readers\n',
    'Redshift IAM without keys':
        'lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: redshift\n      host: db.example.test\n      port: 5432\n      dbname: warehouse\n      schema: analytics\n      threads: 1\n      keepalives_idle: 15\n      sslmode: verify-full\n      sslrootcert: >-\n        <CA_BUNDLE_DIR>/ca-bundle-aws-redshift.crt\n      ra3_node: true\n      method: iam\n      region: eu-west-1\n      cluster_id: cluster\n      user: warehouse-user\n      autocreate: true\n      db_groups:\n        - readers\n',
    'Redshift IAM_BROWSER without keys':
        'lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: redshift\n      host: db.example.test\n      port: 5432\n      dbname: warehouse\n      schema: analytics\n      threads: 1\n      keepalives_idle: 15\n      sslmode: verify-full\n      sslrootcert: >-\n        <CA_BUNDLE_DIR>/ca-bundle-aws-redshift.crt\n      ra3_node: true\n      method: iam\n      region: eu-west-1\n      cluster_id: cluster\n      user: warehouse-user\n      autocreate: true\n      db_groups:\n        - readers\n',
    'Redshift IAM_BROWSER resolved keys':
        'lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: redshift\n      host: db.example.test\n      port: 5432\n      dbname: warehouse\n      schema: analytics\n      threads: 1\n      keepalives_idle: 15\n      sslmode: verify-full\n      sslrootcert: >-\n        <CA_BUNDLE_DIR>/ca-bundle-aws-redshift.crt\n      ra3_node: true\n      method: iam\n      region: eu-west-1\n      cluster_id: cluster\n      user: warehouse-user\n      autocreate: true\n      db_groups:\n        - readers\n',
    'Redshift serverless IAM':
        'lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: redshift\n      host: db.example.test\n      port: 5432\n      dbname: warehouse\n      schema: analytics\n      threads: 1\n      keepalives_idle: 15\n      sslmode: verify-full\n      sslrootcert: >-\n        <CA_BUNDLE_DIR>/ca-bundle-aws-redshift.crt\n      ra3_node: true\n      method: iam\n      region: eu-west-1\n      user: iam\n',
    'Trino LDAP':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: trino\n      host: db.example.test\n      method: ldap\n      user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_USER'') }}'\n      password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PASSWORD'') }}'\n      port: 5432\n      database: warehouse\n      schema: analytics\n      http_scheme: https\n",
    'Snowflake password':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: snowflake\n      account: account\n      user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_USER'') }}'\n      password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PASSWORD'') }}'\n      role: reader\n      database: warehouse\n      warehouse: compute\n      schema: analytics\n      threads: 1\n      client_session_keep_alive: false\n      query_tag: dbt-test\n",
    'Snowflake private key':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: snowflake\n      account: account\n      user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_USER'') }}'\n      password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PASSWORD'') }}'\n      role: reader\n      database: warehouse\n      warehouse: compute\n      schema: analytics\n      threads: 1\n      client_session_keep_alive: false\n      query_tag: dbt-test\n      private_key: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PRIVATEKEY'') }}'\n",
    'Snowflake private key with passphrase':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: snowflake\n      account: account\n      user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_USER'') }}'\n      password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PASSWORD'') }}'\n      role: reader\n      database: warehouse\n      warehouse: compute\n      schema: analytics\n      threads: 1\n      client_session_keep_alive: false\n      query_tag: dbt-test\n      private_key: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PRIVATEKEY'') }}'\n      private_key_passphrase: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PRIVATEKEYPASS'') }}'\n",
    'Snowflake resolved SSO':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: snowflake\n      account: account\n      user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_USER'') }}'\n      password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PASSWORD'') }}'\n      role: reader\n      database: warehouse\n      warehouse: compute\n      schema: analytics\n      threads: 1\n      client_session_keep_alive: false\n      query_tag: dbt-test\n",
    'Databricks PAT':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: databricks\n      catalog: catalog\n      schema: analytics\n      host: workspace.example.test\n      token: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_TOKEN'') }}'\n      http_path: /sql/endpoint\n",
    'Databricks oauth_m2m':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: databricks\n      catalog: catalog\n      schema: analytics\n      host: workspace.example.test\n      token: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_TOKEN'') }}'\n      http_path: /sql/endpoint\n",
    'Databricks oauth_u2m':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: databricks\n      catalog: catalog\n      schema: analytics\n      host: workspace.example.test\n      token: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_TOKEN'') }}'\n      http_path: /sql/endpoint\n",
    'Databricks PAT takes precedence over OAuth token':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: databricks\n      catalog: catalog\n      schema: analytics\n      host: workspace.example.test\n      token: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_TOKEN'') }}'\n      http_path: /sql/endpoint\n",
    'ClickHouse password':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: clickhouse\n      host: clickhouse.example.test\n      port: 8443\n      user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_USER'') }}'\n      password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_PASSWORD'') }}'\n      schema: analytics\n      secure: true\n",
    'MotherDuck token':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: md:warehouse\n      schema: analytics\n      threads: 4\n      extensions:\n        - motherduck\n      settings:\n        motherduck_token: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_TOKEN'') }}'\n",
    'Athena access_key':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: athena\n      region_name: eu-west-1\n      database: catalog\n      schema: analytics\n      s3_staging_dir: s3://staging/\n      s3_data_dir: s3://data/\n      work_group: workgroup\n      threads: 4\n      num_retries: 2\n      aws_assume_role_arn: arn:aws:iam::123456789012:role/query\n      aws_assume_role_external_id: external-id\n      aws_access_key_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_ACCESSKEYID'') }}'\n      aws_secret_access_key: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_SECRETACCESSKEY'') }}'\n",
    'Athena undefined':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: athena\n      region_name: eu-west-1\n      database: catalog\n      schema: analytics\n      s3_staging_dir: s3://staging/\n      s3_data_dir: s3://data/\n      work_group: workgroup\n      threads: 4\n      num_retries: 2\n      aws_assume_role_arn: arn:aws:iam::123456789012:role/query\n      aws_assume_role_external_id: external-id\n      aws_access_key_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_ACCESSKEYID'') }}'\n      aws_secret_access_key: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_SECRETACCESSKEY'') }}'\n",
    'Athena IAM_ROLE':
        'lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: athena\n      region_name: eu-west-1\n      database: catalog\n      schema: analytics\n      s3_staging_dir: s3://staging/\n      s3_data_dir: s3://data/\n      work_group: workgroup\n      threads: 4\n      num_retries: 2\n      aws_assume_role_arn: arn:aws:iam::123456789012:role/query\n      aws_assume_role_external_id: external-id\n',
    'Athena WEB_IDENTITY':
        'lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: athena\n      region_name: eu-west-1\n      database: catalog\n      schema: analytics\n      s3_staging_dir: s3://staging/\n      s3_data_dir: s3://data/\n      work_group: workgroup\n      threads: 4\n      num_retries: 2\n',
    'DuckLake postgres / local':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - postgres\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          path: ducklake:ld_ducklake\n      secrets:\n        - name: ld_ducklake_catalog\n          type: postgres\n          host: catalog.example.test\n          port: 5433\n          database: metadata\n          user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_USER'') }}'\n          password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_PASSWORD'') }}'\n        - name: ld_ducklake\n          type: ducklake\n          metadata_path: ''\n          data_path: /data/lake\n          metadata_parameters:\n            TYPE: postgres\n            SECRET: ld_ducklake_catalog\n",
    'DuckLake postgres / S3 with keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - postgres\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          path: ducklake:ld_ducklake\n      secrets:\n        - name: ld_ducklake_catalog\n          type: postgres\n          host: catalog.example.test\n          port: 5433\n          database: metadata\n          user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_USER'') }}'\n          password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_PASSWORD'') }}'\n        - name: ld_ducklake_data\n          type: s3\n          scope: s3://lake/\n          region: eu-west-1\n          endpoint: s3.example.test\n          url_style: path\n          use_ssl: false\n          key_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_S3_KEY'') }}'\n          secret: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_S3_SECRET'') }}'\n        - name: ld_ducklake\n          type: ducklake\n          metadata_path: ''\n          data_path: s3://lake/\n          metadata_parameters:\n            TYPE: postgres\n            SECRET: ld_ducklake_catalog\n",
    'DuckLake postgres / S3 without keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - postgres\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          path: ducklake:ld_ducklake\n      secrets:\n        - name: ld_ducklake_catalog\n          type: postgres\n          host: catalog.example.test\n          port: 5433\n          database: metadata\n          user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_USER'') }}'\n          password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_PASSWORD'') }}'\n        - name: ld_ducklake_data\n          type: s3\n          scope: s3://lake/\n          url_style: vhost\n          use_ssl: true\n          provider: credential_chain\n        - name: ld_ducklake\n          type: ducklake\n          metadata_path: ''\n          data_path: s3://lake/\n          metadata_parameters:\n            TYPE: postgres\n            SECRET: ld_ducklake_catalog\n",
    'DuckLake postgres / GCS with HMAC keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - postgres\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          path: ducklake:ld_ducklake\n      secrets:\n        - name: ld_ducklake_catalog\n          type: postgres\n          host: catalog.example.test\n          port: 5433\n          database: metadata\n          user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_USER'') }}'\n          password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_PASSWORD'') }}'\n        - name: ld_ducklake_data\n          type: gcs\n          scope: gs://lake/\n          key_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_GCS_KEY'') }}'\n          secret: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_GCS_SECRET'') }}'\n        - name: ld_ducklake\n          type: ducklake\n          metadata_path: ''\n          data_path: gs://lake/\n          metadata_parameters:\n            TYPE: postgres\n            SECRET: ld_ducklake_catalog\n",
    'DuckLake postgres / GCS without keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - postgres\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          path: ducklake:ld_ducklake\n      secrets:\n        - name: ld_ducklake_catalog\n          type: postgres\n          host: catalog.example.test\n          port: 5433\n          database: metadata\n          user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_USER'') }}'\n          password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_PASSWORD'') }}'\n        - name: ld_ducklake_data\n          type: gcs\n          scope: gs://lake/\n          provider: credential_chain\n        - name: ld_ducklake\n          type: ducklake\n          metadata_path: ''\n          data_path: gs://lake/\n          metadata_parameters:\n            TYPE: postgres\n            SECRET: ld_ducklake_catalog\n",
    'DuckLake postgres / Azure connection string':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - postgres\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          path: ducklake:ld_ducklake\n      secrets:\n        - name: ld_ducklake_catalog\n          type: postgres\n          host: catalog.example.test\n          port: 5433\n          database: metadata\n          user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_USER'') }}'\n          password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_PASSWORD'') }}'\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n          connection_string: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_AZURE_CONNECTION_STRING'') }}'\n        - name: ld_ducklake\n          type: ducklake\n          metadata_path: ''\n          data_path: az://lake/\n          metadata_parameters:\n            TYPE: postgres\n            SECRET: ld_ducklake_catalog\n",
    'DuckLake postgres / Azure account key':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - postgres\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          path: ducklake:ld_ducklake\n      secrets:\n        - name: ld_ducklake_catalog\n          type: postgres\n          host: catalog.example.test\n          port: 5433\n          database: metadata\n          user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_USER'') }}'\n          password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_PASSWORD'') }}'\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n          account_name: azure-account\n          account_key: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_AZURE_ACCOUNT_KEY'') }}'\n        - name: ld_ducklake\n          type: ducklake\n          metadata_path: ''\n          data_path: az://lake/\n          metadata_parameters:\n            TYPE: postgres\n            SECRET: ld_ducklake_catalog\n",
    'DuckLake postgres / Azure account without key':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - postgres\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          path: ducklake:ld_ducklake\n      secrets:\n        - name: ld_ducklake_catalog\n          type: postgres\n          host: catalog.example.test\n          port: 5433\n          database: metadata\n          user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_USER'') }}'\n          password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_PASSWORD'') }}'\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n          account_name: azure-account\n          provider: credential_chain\n        - name: ld_ducklake\n          type: ducklake\n          metadata_path: ''\n          data_path: az://lake/\n          metadata_parameters:\n            TYPE: postgres\n            SECRET: ld_ducklake_catalog\n",
    'DuckLake postgres / Azure without account or secrets':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - postgres\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          path: ducklake:ld_ducklake\n      secrets:\n        - name: ld_ducklake_catalog\n          type: postgres\n          host: catalog.example.test\n          port: 5433\n          database: metadata\n          user: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_USER'') }}'\n          password: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_CATALOG_PASSWORD'') }}'\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n        - name: ld_ducklake\n          type: ducklake\n          metadata_path: ''\n          data_path: az://lake/\n          metadata_parameters:\n            TYPE: postgres\n            SECRET: ld_ducklake_catalog\n",
    'DuckLake sqlite / local':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - sqlite\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: /data/lake\n          path: ducklake:sqlite:/catalog.sqlite\n",
    'DuckLake sqlite / S3 with keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - sqlite\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: s3://lake/\n          path: ducklake:sqlite:/catalog.sqlite\n      secrets:\n        - name: ld_ducklake_data\n          type: s3\n          scope: s3://lake/\n          region: eu-west-1\n          endpoint: s3.example.test\n          url_style: path\n          use_ssl: false\n          key_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_S3_KEY'') }}'\n          secret: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_S3_SECRET'') }}'\n",
    'DuckLake sqlite / S3 without keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - sqlite\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: s3://lake/\n          path: ducklake:sqlite:/catalog.sqlite\n      secrets:\n        - name: ld_ducklake_data\n          type: s3\n          scope: s3://lake/\n          url_style: vhost\n          use_ssl: true\n          provider: credential_chain\n",
    'DuckLake sqlite / GCS with HMAC keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - sqlite\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: gs://lake/\n          path: ducklake:sqlite:/catalog.sqlite\n      secrets:\n        - name: ld_ducklake_data\n          type: gcs\n          scope: gs://lake/\n          key_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_GCS_KEY'') }}'\n          secret: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_GCS_SECRET'') }}'\n",
    'DuckLake sqlite / GCS without keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - sqlite\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: gs://lake/\n          path: ducklake:sqlite:/catalog.sqlite\n      secrets:\n        - name: ld_ducklake_data\n          type: gcs\n          scope: gs://lake/\n          provider: credential_chain\n",
    'DuckLake sqlite / Azure connection string':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - sqlite\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: az://lake/\n          path: ducklake:sqlite:/catalog.sqlite\n      secrets:\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n          connection_string: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_AZURE_CONNECTION_STRING'') }}'\n",
    'DuckLake sqlite / Azure account key':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - sqlite\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: az://lake/\n          path: ducklake:sqlite:/catalog.sqlite\n      secrets:\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n          account_name: azure-account\n          account_key: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_AZURE_ACCOUNT_KEY'') }}'\n",
    'DuckLake sqlite / Azure account without key':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - sqlite\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: az://lake/\n          path: ducklake:sqlite:/catalog.sqlite\n      secrets:\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n          account_name: azure-account\n          provider: credential_chain\n",
    'DuckLake sqlite / Azure without account or secrets':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - sqlite\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: az://lake/\n          path: ducklake:sqlite:/catalog.sqlite\n      secrets:\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n",
    'DuckLake duckdb / local':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: /data/lake\n          path: ducklake:/catalog.duckdb\n",
    'DuckLake duckdb / S3 with keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: s3://lake/\n          path: ducklake:/catalog.duckdb\n      secrets:\n        - name: ld_ducklake_data\n          type: s3\n          scope: s3://lake/\n          region: eu-west-1\n          endpoint: s3.example.test\n          url_style: path\n          use_ssl: false\n          key_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_S3_KEY'') }}'\n          secret: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_S3_SECRET'') }}'\n",
    'DuckLake duckdb / S3 without keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: s3://lake/\n          path: ducklake:/catalog.duckdb\n      secrets:\n        - name: ld_ducklake_data\n          type: s3\n          scope: s3://lake/\n          url_style: vhost\n          use_ssl: true\n          provider: credential_chain\n",
    'DuckLake duckdb / GCS with HMAC keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: gs://lake/\n          path: ducklake:/catalog.duckdb\n      secrets:\n        - name: ld_ducklake_data\n          type: gcs\n          scope: gs://lake/\n          key_id: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_GCS_KEY'') }}'\n          secret: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_GCS_SECRET'') }}'\n",
    'DuckLake duckdb / GCS without keys':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - httpfs\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: gs://lake/\n          path: ducklake:/catalog.duckdb\n      secrets:\n        - name: ld_ducklake_data\n          type: gcs\n          scope: gs://lake/\n          provider: credential_chain\n",
    'DuckLake duckdb / Azure connection string':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: az://lake/\n          path: ducklake:/catalog.duckdb\n      secrets:\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n          connection_string: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_AZURE_CONNECTION_STRING'') }}'\n",
    'DuckLake duckdb / Azure account key':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: az://lake/\n          path: ducklake:/catalog.duckdb\n      secrets:\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n          account_name: azure-account\n          account_key: '{{ env_var(''LIGHTDASH_DBT_PROFILE_VAR_AZURE_ACCOUNT_KEY'') }}'\n",
    'DuckLake duckdb / Azure account without key':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: az://lake/\n          path: ducklake:/catalog.duckdb\n      secrets:\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n          account_name: azure-account\n          provider: credential_chain\n",
    'DuckLake duckdb / Azure without account or secrets':
        "lightdash_profile:\n  target: prod\n  outputs:\n    prod:\n      type: duckdb\n      path: ':memory:'\n      database: lake_alias\n      schema: analytics\n      threads: 3\n      extensions:\n        - ducklake\n        - azure\n      settings:\n        autoinstall_known_extensions: true\n        autoload_known_extensions: true\n      attach:\n        - alias: lake_alias\n          options:\n            data_path: az://lake/\n          path: ducklake:/catalog.duckdb\n      secrets:\n        - name: ld_ducklake_data\n          type: azure\n          scope: az://lake/\n",
};
