import { formatDate, WarehouseTypes } from '@lightdash/common';
import moment from 'moment';
import { FC, useEffect } from 'react';
import { Redirect, useParams } from 'react-router-dom';
import Page from '../components/common/Page/Page';
import PageSpinner from '../components/PageSpinner';
import ConnectManually from '../components/ProjectConnection/ProjectConnectFlow/ConnectManually';
import ConnectSuccess from '../components/ProjectConnection/ProjectConnectFlow/ConnectSuccess';
import ConnectUsingCLI from '../components/ProjectConnection/ProjectConnectFlow/ConnectUsingCLI';
import { ProjectFormProvider } from '../components/ProjectConnection/ProjectFormProvider';
import { useOrganisation } from '../hooks/organisation/useOrganisation';
import { useCreateAccessToken } from '../hooks/useAccessToken';
import useSearchParams from '../hooks/useSearchParams';
import { useApp } from '../providers/AppProvider';

export type SelectedWarehouse = {
    label: string;
    key: WarehouseTypes;
    icon: string;
};

enum ConnectMethod {
    CLI = 'cli',
    MANUAL = 'manual',
}

const CreateProject: FC = () => {
    const {
        health: { data: health, isLoading: isLoadingHealth },
    } = useApp();

    const { isLoading: isLoadingOrganisation, data: organisation } =
        useOrganisation({
            staleTime: Infinity,
            cacheTime: Infinity,
        });

    const {
        mutate: mutateAccessToken,
        data: tokenData,
        isLoading: isTokenLoading,
    } = useCreateAccessToken();

    const isSSO = true;

    useEffect(() => {
        if (!isSSO) return;

        const expiresAt = moment().add(30, 'days').toDate();

        mutateAccessToken({
            expiresAt,
            description: `Generated by the Lightdash UI on ${formatDate(
                new Date(),
            )}`,
        });
    }, [isSSO, mutateAccessToken]);

    const { method } = useParams<{ method: ConnectMethod }>();
    const projectUuid = useSearchParams('projectUuid');

    if (
        isLoadingHealth ||
        !health ||
        isLoadingOrganisation ||
        !organisation ||
        isTokenLoading ||
        (isSSO && !tokenData)
    ) {
        return <PageSpinner />;
    }

    if (method && projectUuid) {
        return <ConnectSuccess projectUuid={projectUuid} />;
    }

    return (
        <ProjectFormProvider>
            <Page noContentPadding>
                {method === ConnectMethod.CLI && (
                    <ConnectUsingCLI
                        isSSO={true}
                        loginToken={tokenData?.token}
                        siteUrl={health.siteUrl}
                        needsProject={!!organisation.needsProject}
                    />
                )}
                {method === ConnectMethod.MANUAL && (
                    <ConnectManually
                        needsProject={!!organisation.needsProject}
                    />
                )}

                {!method && (
                    <Redirect to={`/createProject/${ConnectMethod.CLI}`} />
                )}
            </Page>
        </ProjectFormProvider>
    );
};

export default CreateProject;
