name: Setup Node and PNPM

description: Sets up Node.js, PNPM, and installs dependencies.

runs:
    using: 'composite'
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - uses: pnpm/action-setup@v4
          with:
              version: 9
              run_install: false

        - uses: actions/setup-node@v4
          with:
              node-version: '20'
              cache: 'pnpm'
              cache-dependency-path: 'pnpm-lock.yaml'

        - name: Get pnpm store directory
          id: pnpm-store
          run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
          shell: bash

        - name: Use pnpm store
          uses: actions/cache@v4
          id: pnpm-cache
          with:
              path: |
                  ~/.cache/Cypress
                  ${{ steps.pnpm-store.outputs.pnpm_cache_dir }}
              key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  ${{ runner.os }}-pnpm-

        - name: Install Dependencies
          run: pnpm install --frozen-lockfile --prefer-offline
          shell: bash