import {
    isToolName,
    type AiAgentToolName,
    type ToolName,
} from '@lightdash/common';
import {
    IconAppWindow,
    IconChartDots3,
    IconChartHistogram,
    IconDatabase,
    IconFileCode,
    IconFileDiff,
    IconFileText,
    IconGitPullRequest,
    IconGitPullRequestClosed,
    IconMessages,
    IconFolders,
    IconLayoutDashboard,
    IconLink,
    IconListDetails,
    IconBook2,
    IconBooks,
    IconPencil,
    IconPlayerPlay,
    IconPlugConnected,
    IconRefresh,
    IconSearch,
    IconSelector,
    IconSend,
    IconStack2,
    IconUserEdit,
    IconTable,
    IconTerminal2,
    IconVocabulary,
    type TablerIconsProps,
} from '@tabler/icons-react';
import type { JSX } from 'react';

export const getToolIcon = (toolName: AiAgentToolName) => {
    const iconMap: Record<ToolName, (props: TablerIconsProps) => JSX.Element> =
        {
            findExplores: IconDatabase,
            findCustomChartTypes: IconChartDots3,
            findFields: IconSearch,
            searchSemanticLayer: IconBooks,
            analyzeFieldImpact: IconChartDots3,
            discoverFields: IconSearch,
            grepFields: IconTerminal2,
            getMetadata: IconListDetails,
            searchFieldValues: IconSelector,
            generateDashboard: IconLayoutDashboard,
            generateHashes: IconSelector,
            generateUuids: IconSelector,
            findContent: IconSearch,
            listContent: IconSearch,
            findDashboards: IconLayoutDashboard,
            findCharts: IconChartDots3,
            getDashboardCharts: IconLayoutDashboard,
            readContent: IconFileCode,
            resolveUrl: IconLink,
            editContent: IconPencil,
            createContent: IconPencil,
            createScheduledDelivery: IconSend,
            listProjects: IconFolders,
            getProjectInfo: IconPlugConnected,
            loadSkill: IconBook2,
            loadProjectContext: IconVocabulary,
            loadMcpTools: IconPlugConnected,
            generateDataApp: IconAppWindow,
            iterateDataApp: IconAppWindow,
            editDbtProject: IconPencil,
            editProjectContext: IconVocabulary,
            editRepo: IconPencil,
            updateUserName: IconUserEdit,
            syncDbtProject: IconRefresh,
            exploreRepo: IconTerminal2,
            discoverRepos: IconFolders,
            listWorkstreams: IconGitPullRequest,
            closePullRequest: IconGitPullRequestClosed,
            getPullRequestDiff: IconFileDiff,
            generateVisualization: IconTable,
            setupPreviewDeploy: IconPlugConnected,
            runQuery: IconTable,
            runContentQuery: IconPlayerPlay,
            runSavedChart: IconChartHistogram,
            runSql: IconTerminal2,
            runComposerQueries: IconStack2,
            listWarehouseTables: IconDatabase,
            describeWarehouseTable: IconDatabase,
            listKnowledgeDocuments: IconBooks,
            getKnowledgeDocumentContent: IconFileText,
            readPinnedThread: IconMessages,
            submitResearchReport: IconFileText,
            delegateResearchTask: IconListDetails,
            submitWorkerFindings: IconFileText,
        };

    return isToolName(toolName) ? iconMap[toolName] : IconPlugConnected;
};
