import { Ability } from '@casl/ability';
import {
    AuthTokenPrefix,
    ForbiddenError,
    OrganizationMemberRole,
    PossibleAbilities,
    RequestMethod,
} from '@lightdash/common';
import { lightdashConfigMock } from '../../config/lightdashConfig.mock';
import { ServiceAccountService } from '../../ee/services/ServiceAccountService/ServiceAccountService';
import Logger from '../../logging/logger';
import { OAuthService } from '../../services/OAuthService/OAuthService';
import { PersonalAccessTokenService } from '../../services/PersonalAccessTokenService';
import { fromOauth, toSessionUser } from '../account/account';
import { defaultSessionUser } from '../account/account.mock';

const user = {
    ...defaultSessionUser,
    role: OrganizationMemberRole.ADMIN,
    ability: new Ability<PossibleAbilities>([
        { action: 'manage', subject: 'all' },
    ]),
};

const build = (mode: 'log' | 'enforce') => {
    const account = fromOauth(
        user,
        {
            accessToken: 'secret',
            client: { id: 'client' },
            scope: ['write', 'mcp:write'],
        },
        {
            mode,
            getRequest: () => ({
                method: 'POST',
                routeTemplate: '/credentials',
            }),
        },
    );
    const write = vi.fn().mockRejectedValue(new Error('Mutation reached'));
    const read = vi.fn().mockRejectedValue(new Error('Read reached'));
    const analytics = { track: vi.fn() };
    const pat = new PersonalAccessTokenService({
        lightdashConfig: lightdashConfigMock,
        analytics,
        personalAccessTokenModel: {
            create: write,
            rotate: write,
            getUserToken: read,
        },
    } as unknown as ConstructorParameters<
        typeof PersonalAccessTokenService
    >[0]);
    const serviceAccount = new ServiceAccountService({
        lightdashConfig: lightdashConfigMock,
        analytics,
        serviceAccountModel: {
            create: write,
            rotate: write,
            getTokenbyUuid: read,
        },
        rolesModel: { getOrganizationUserRoleSet: read },
    } as unknown as ConstructorParameters<typeof ServiceAccountService>[0]);
    const oauth = new OAuthService({
        lightdashConfig: lightdashConfigMock,
        oauthModel: {
            createClient: write,
            updateClient: write,
            deleteClient: write,
        },
    } as unknown as ConstructorParameters<typeof OAuthService>[0]);
    const sessionUser = toSessionUser(account);
    const expiresAt = new Date(Date.now() + 86400000);
    const client = {
        clientName: 'client',
        redirectUris: ['https://example.com/callback'],
    };
    const calls = {
        createPersonalAccessToken: () =>
            pat.createPersonalAccessToken(
                account,
                { description: 'token', expiresAt, autoGenerated: false },
                RequestMethod.UNKNOWN,
            ),
        rotatePersonalAccessToken: () =>
            pat.rotatePersonalAccessToken(account, 'token', { expiresAt }),
        createServiceAccount: () =>
            serviceAccount.create({
                user: sessionUser,
                tokenDetails: {
                    organizationUuid: user.organizationUuid!,
                    description: 'service',
                    expiresAt,
                    scopes: [],
                },
                prefix: AuthTokenPrefix.SERVICE_ACCOUNT,
            }),
        rotateServiceAccount: () =>
            serviceAccount.rotate({
                user: sessionUser,
                tokenUuid: 'token',
                update: { expiresAt },
                prefix: AuthTokenPrefix.SERVICE_ACCOUNT,
            }),
        createScimToken: () =>
            serviceAccount.create({
                user: sessionUser,
                tokenDetails: {
                    organizationUuid: user.organizationUuid!,
                    description: 'scim',
                    expiresAt,
                    scopes: [],
                },
                prefix: AuthTokenPrefix.SCIM,
            }),
        rotateScimToken: () =>
            serviceAccount.rotate({
                user: sessionUser,
                tokenUuid: 'token',
                update: { expiresAt },
                prefix: AuthTokenPrefix.SCIM,
            }),
        createOAuthClient: () => oauth.createAdminClient(account, client),
        updateOAuthClient: () => oauth.updateClient(account, 'client', client),
        deleteOAuthClient: () => oauth.deleteClient(account, 'client'),
    };
    return { calls, write, read, analytics };
};

const operations = [
    'createPersonalAccessToken',
    'rotatePersonalAccessToken',
    'createServiceAccount',
    'rotateServiceAccount',
    'createScimToken',
    'rotateScimToken',
    'createOAuthClient',
    'updateOAuthClient',
    'deleteOAuthClient',
] as const;

describe.each(['log', 'enforce'] as const)(
    'Credential services in %s mode',
    (mode) => {
        beforeEach(() => {
            vi.spyOn(Logger, 'warn').mockImplementation(() => Logger);
        });
        afterEach(() => vi.restoreAllMocks());
        it.each(operations)(
            'refuses %s before model reads, writes or analytics',
            async (operation) => {
                const { calls, write, read, analytics } = build(mode);
                await expect(calls[operation]()).rejects.toBeInstanceOf(
                    ForbiddenError,
                );
                expect(write).not.toHaveBeenCalled();
                expect(read).not.toHaveBeenCalled();
                expect(analytics.track).not.toHaveBeenCalled();
                expect(Logger.warn).toHaveBeenCalledTimes(1);
            },
        );
    },
);
