import {
    Account,
    ForbiddenError,
    isAccount,
    SessionUser,
} from '@lightdash/common';
import { RequestHandler } from 'express';
import { getOAuthScopeContext } from './scopedAbility';

export const OAUTH_UNCHECKED_OPERATIONS = {
    'ProjectCoderController.rebaseContentDraft': 'write',
    'ProjectCoderController.reopenContentDraft': 'write',
    'ExploreController.GetExplore': 'read',
    'ProjectController.CompileMergeQuery': 'read',
    'ProjectController.RunMergeQuery': 'read',
    'QueryController.getAsyncQueryResults': 'read',
    'QueryController.executeAsyncMergeQuery': 'read',
    'QueryController.executeAsyncComposeMergeQuery': 'read',
    'QueryController.executeAsyncDashboardChartQuery': 'read',
    'QueryController.getResultsStream': 'read',
    'QueryController.downloadResults': 'read',
    'QueryController.scheduleDownloadResults': 'read',
    'DocumentController.executeChartQuery': 'read',
    'DocumentController.verify': 'write',
    'DocumentController.unverify': 'write',
    'DocumentController.duplicate': 'write',
    'DocumentController.exportPdf': 'read',
    'DocumentController.promote': 'write',
    'DocumentController.updateMetadata': 'write',
    'DocumentController.updateContent': 'write',
    'DocumentController.list': 'read',
    'OrganizationRolesController.getOrganizationRoles': 'read',
    'OrganizationRolesController.getOrganizationRoleAssignments': 'read',
    'BigquerySSOController.get': 'read',
    'CatalogController.getMetricsTree': 'read',
    'CommentsController.deleteComment': 'write',
    'DashboardController.updateDashboardCustomMetric': 'write',
    'DashboardController.deleteDashboardCustomMetric': 'write',
    'DashboardController.getDashboardSchedulers': 'read',
    'ExploreController.CompileQuery': 'read',
    'ExploreController.CheckPreAggregate': 'read',
    'ExploreController.ValidateFormula': 'read',
    'FavoritesController.toggleFavorite': 'write',
    'FileController.getFile': 'read',
    'GeoJsonProxyController.get': 'read',
    'MapTileController.getTile': 'read',
    'MetricsExplorerController.runMetricTotal': 'read',
    'MetricsExplorerController.runMetricSeries': 'read',
    'MetricsExplorerController.compileMetricTotalQuery': 'read',
    'OrganizationController.getOrganization': 'read',
    'OrganizationController.createOrganization': 'write',
    'OrganizationController.getProjects': 'read',
    'OrganizationController.getUserSchedulersSummary': 'read',
    'OrganizationController.getUserDashboardsSummary': 'read',
    'OrganizationController.reassignUserDashboards': 'write',
    'OrganizationController.listGroupsInOrganization': 'read',
    'OrganizationController.createProject': 'write',
    'OrganizationController.getLearnAccess': 'read',
    'OrganizationController.getImpersonationSettings': 'read',
    'ProjectController.updateUserWarehouseCredentialsPreference': 'write',
    'ProjectController.getDashboards': 'read',
    'ProjectController.createDashboard': 'write',
    'ProjectController.updateDashboards': 'write',
    'ProjectController.createPreview': 'write',
    'ProjectController.updateSchedulerSettings': 'write',
    'ProjectDbtSourcesController.getProjectDbtSource': 'read',
    'RunViewChartQueryController.postUnderlyingData': 'read',
    'SavedChartController.postChartResults': 'read',
    'SavedChartController.postDashboardTile': 'read',
    'SavedChartController.getChartVersionResults': 'read',
    'SavedChartController.calculateTotalFromSavedChart': 'read',
    'SavedChartController.getSavedChartSchedulers': 'read',
    'SavedChartController.exportSavedChartImage': 'read',
    'SchedulerController.patchEnabled': 'write',
    'SchedulerController.delete': 'write',
    'SchedulerController.getJobs': 'read',
    'SchedulerController.postByUuid': 'write',
    'SpaceController.getSpaceServiceAccountCandidates': 'read',
    'SpaceController.getSpace': 'read',
    'SpaceController.getSpaceAccessList': 'read',
    'SpaceController.getDeleteImpact': 'read',
    'SpaceController.deleteSpace': 'write',
    'SpaceController.updateSpace': 'write',
    'SpaceController.addSpaceUserAccess': 'write',
    'SpaceController.revokeSpaceAccessForUser': 'write',
    'SpaceController.addSpaceGroupAccess': 'write',
    'SpaceController.revokeGroupSpaceAccess': 'write',
    'SqlRunnerController.getSavedSqlResultsJob': 'read',
    'SqlRunnerController.getSavedSqlResultsJobByUuid': 'read',
    'SqlRunnerController.getSqlChartSchedulers': 'read',
    'UserActivityController.exportUserActivityCsv': 'read',
    'UserController.getAuthenticatedUser': 'read',
    'UserController.getUserOnboarding': 'read',
    'UserController.getUserLearnProgress': 'read',
    'UserController.getAccount': 'read',
    'WarehouseConnectionController.updateWarehouseConnectionUserCredentials':
        'write',
    'AiServiceAccountController.get': 'read',
    'ContentController.listContent': 'read',
    'ContentController.moveContent': 'write',
    'ContentController.bulkMoveContent': 'write',
    'ContentController.deleteContent': 'write',
    'ContentController.bulkDeleteContent': 'write',
    'ContentController.restoreContent': 'write',
    'ContentController.permanentlyDeleteContent': 'write',
    'DashboardControllerV2.exportDashboardContent': 'read',
    'DashboardControllerV2.getDashboardSchedulers': 'read',
    'DirectAccessController.listDirectAccessGroups': 'read',
    'DirectAccessController.listDirectAccessUsers': 'read',
    'DirectAccessController.listDirectAccessAssignments': 'read',
    'DirectAccessController.upsertDirectAccessAssignment': 'write',
    'DirectAccessController.revokeDirectAccessAssignment': 'write',
    'DirectAccessController.resetDirectAccessAssignments': 'write',
    'OrganizationAgentIdentityController.getSettings': 'read',
    'ProjectDashboardControllerV2.update': 'write',
    'QueryController.cancelAsyncQuery': 'read',
    'QueryController.executeAsyncMetricQuery': 'read',
    'QueryController.executeAsyncFieldValueSearch': 'read',
    'QueryController.executeAsyncSavedChartQuery': 'read',
    'QueryController.executeAsyncUnderlyingDataQuery': 'read',
    'QueryController.executeAsyncDashboardSqlChartQuery': 'read',
    'QuerySourceController.scanQuerySourceSchema': 'read',
    'SavedChartControllerV2.getSavedChartSchedulers': 'read',
    'AiAgentAdminController.getAllThreads': 'read',
    'AiAgentAdminController.deleteThread': 'write',
    'AiAgentAdminController.getAllEvals': 'read',
    'AiAgentAdminController.getAdminEvalPrompts': 'read',
    'AiAgentAdminController.getMcpActivity': 'read',
    'AiAgentAdminController.getMcpActivityStats': 'read',
    'AiAgentAdminController.getProjectPromptActivity': 'read',
    'AiAgentAdminController.getAllAgents': 'read',
    'AiAgentAdminController.getAllAiAgentMemories': 'read',
    'AiAgentAdminController.getReviewItems': 'read',
    'AiAgentAdminController.getReviewItem': 'read',
    'AiAgentAdminController.getReviewItemActivity': 'read',
    'AiAgentAdminController.getReviewItemPrDiff': 'read',
    'AiAgentAdminController.getReviewItemByPreviewThread': 'read',
    'AiAgentAdminController.getReviewItemWritebackPreview': 'read',
    'AiAgentAdminController.getSettings': 'read',
    'AiAgentAdminController.upsertSettings': 'write',
    'AiAgentMemoryController.promoteAiAgentMemory': 'write',
    'AiAgentMemoryController.updateAiAgentMemoryStatus': 'write',
    'AiCreditController.getUsage': 'read',
    'AiCreditController.getDailyUsage': 'read',
    'AiDeepResearchController.createRun': 'write',
    'AiDeepResearchController.refreshChart': 'write',
    'AiDeepResearchController.cancelRun': 'write',
    'AiProviderCredentialController.listCredentials': 'read',
    'AiProviderCredentialController.createCredential': 'write',
    'AiProviderCredentialController.adoptLegacyCredential': 'write',
    'AiProviderCredentialController.updateCredential': 'write',
    'AiProviderCredentialController.replaceCredential': 'write',
    'AiProviderCredentialController.deleteCredential': 'write',
    'AiProviderCredentialController.setDefaultCredential': 'write',
    'AiProviderCredentialController.getProjectCredential': 'read',
    'AiProviderCredentialController.setProjectCredential': 'write',
    'AiWritebackController.runAiWriteback': 'write',
    'ContentReviewRequestController.updateSettings': 'write',
    'ContentReviewRequestController.compareSimilar': 'read',
    'ContentReviewRequestController.submit': 'write',
    'ContentReviewRequestController.approve': 'write',
    'ContentReviewRequestController.reject': 'write',
    'ContentReviewRequestController.cancel': 'write',
    'OnboardingAgentController.cancelRun': 'write',
    'PreAggregateController.runDashboardPreAggregateAudit': 'read',
    'AiAgentController.listAgents': 'read',
    'AiAgentController.setUserDefaultAgent': 'write',
    'AiAgentController.deleteUserAgentPreferences': 'write',
    'AiAgentController.getGithubMcpAvailability': 'read',
    'AiAgentController.listProjectThreads': 'read',
    'AiAgentController.getAgentThreadLiveStatuses': 'read',
    'AiAgentController.getAgent': 'read',
    'AiAgentController.listAgentMcpServers': 'read',
    'AiAgentController.getModelOptions': 'read',
    'AiAgentController.getAgentSuggestions': 'read',
    'AiAgentController.getVerifiedArtifacts': 'read',
    'AiAgentController.listAgentThreads': 'read',
    'AiAgentController.getAgentThread': 'read',
    'AiAgentController.getAgentThreadPullRequest': 'read',
    'AiAgentController.listAgentThreadWorkstreams': 'read',
    'AiAgentController.createAgentThread': 'write',
    'AiAgentController.createAgentThreadMessage': 'write',
    'AiAgentController.streamAgentThreadResponse': 'write',
    'AiAgentController.interruptAgentThreadMessage': 'write',
    'AiAgentController.createAgentThreadMessageSteer': 'write',
    'AiAgentController.generateAgentThreadResponse': 'write',
    'AiAgentController.generateAgentThreadTitle': 'write',
    'AiAgentController.cloneAgentThread': 'write',
    'AiAgentController.updateAgentThreadMessageSavedQuery': 'write',
    'AiAgentController.updatePromptFeedback': 'write',
    'AiAgentController.getArtifact': 'read',
    'AiAgentController.getArtifactVersion': 'read',
    'AiAgentController.getArtifactVizQuery': 'read',
    'AiAgentController.createAiAgentThreadShare': 'write',
    'AiAgentController.updateArtifactVersionSavedDashboard': 'write',
    'AiAgentController.updateArtifactVersionSavedSql': 'write',
    'AiAgentController.updateArtifactVersionVizConfig': 'write',
    'AiAgentController.createEvaluation': 'write',
    'AiAgentController.runEvaluation': 'write',
    'AiAgentController.getEvaluations': 'read',
    'AiAgentController.getEvaluation': 'read',
    'AiAgentController.getEvaluationRuns': 'read',
    'AiAgentController.getEvaluationRunResults': 'read',
    'AiAgentController.updateEvaluation': 'write',
    'AiAgentController.appendToEvaluation': 'write',
    'AiAgentController.deleteEvaluation': 'write',
    'AiAgentScopedSkillController.listAgentSkills': 'read',
    'AiAgentSkillController.listSkills': 'read',
    'AiAgentSkillController.getSkillsAsCode': 'read',
    'AiAgentSkillController.validateSkill': 'read',
    'AiAgentSkillController.getSkill': 'read',
    'AiAgentSkillController.listVersions': 'read',
    'AiAgentSkillController.getVersion': 'read',
    'AiRouterController.route': 'write',
    'AiRouterController.commit': 'write',
    'AppGenerateController.getChartDataAppVizRenderMetadata': 'read',
    'AppGenerateController.getChartDataAppVizPreviewToken': 'read',
    'AppGenerateController.getApp': 'read',
    'AppGenerateController.getPreviewToken': 'read',
    'AppGenerateController.importAppCode': 'write',
    'AppGenerateController.getAppSchedulers': 'read',
    'DataAppAnalysisController.detect': 'write',
    'DataAppAnalysisController.lookup': 'read',
    'DataAppAnalysisController.prompt': 'write',
    'DataAppAnalysisController.investigate': 'write',
    'DataAppAnalysisController.getAnalysis': 'read',
    'ExternalConnectionController.externalFetch': 'write',
    'MobilePushNotificationController.getMobilePushNotificationStatus': 'read',
    'SchedulerAiAugmentationController.upsertAugmentation': 'write',
    'SchedulerAiAugmentationController.deleteAugmentation': 'write',
    'SnowflakeController.ssoIsAuthenticated': 'read',
    'SupportController.shareSupport': 'write',
    'apiV1Router GET /health': 'read',
    'dashboardRouter PATCH /:dashboardUuidOrSlug': 'write',
    'dashboardRouter POST /availableFilters': 'read',
    'dashboardRouter POST /:dashboardUuid/export': 'read',
    'mcpRouter.handle': 'read',
    'oauthRouter GET /userinfo': 'read',
    'organizationRouter POST /projects/precompiled': 'write',
    'projectRouter POST /field/:fieldId/search': 'read',
    'projectRouter PATCH /saved': 'write',
    'chartRegistryAssetRouter GET /assets': 'read',
    'OrganizationHomepageSettingsController.getSettings': 'read',
    'UserController.completeUserOnboardingTour': 'write',
    'UserController.markUserLearnScopeStarted': 'write',
    'UserController.markUserLearnScopeCompleted': 'write',
    'UserController.mergeUserLearnProgress': 'write',
    'UserController.joinOrganization': 'write',
    'UserController.getOrganizationsUserCanJoin': 'read',
    'UserController.getWarehouseCredentials': 'read',
    'UserController.createWarehouseCredentials': 'write',
    'UserController.startRedshiftAwsSsoWarehouseCredentials': 'write',
    'UserController.completeRedshiftAwsSsoWarehouseCredentials': 'write',
    'UserController.updateWarehouseCredentials': 'write',
    'UserController.deleteWarehouseCredentials': 'write',
    'UserAvatarController.updateMyAvatar': 'write',
    'UserAvatarController.deleteMyAvatar': 'write',
    'UsersAvatarController.getUserAvatar': 'read',
    'GoogleDriveController.get': 'read',
    'DeployController.addDeployBatch': 'write',
    'DeployController.finalizeDeploySession': 'write',
    'QuerySourceController.getSourceQueryStatus': 'read',
    'FeatureFlagController.getFeatureFlag': 'read',
    'ShareController.create': 'write',
    'SlackController.get': 'read',
    'SlackController.getChannelById': 'read',
    'SlackController.updateCustomSettings': 'write',
    'BigquerySSOController.getBigQueryDatabases': 'read',
    'BigquerySSOController.getBigQueryProjects': 'read',
    'BigquerySSOController.getBigQueryProjectRecommendation': 'read',
    'NotificationsController.getNotifications': 'read',
    'NotificationsController.updateNotification': 'write',
    'OrganizationController.getColorPalettes': 'read',
    'AiOrganizationSettingsController.getRuntimeSettings': 'read',
    'AiAgentController.getAgentExploreAccessSummary': 'read',
    'AiThreadFileController.upload': 'write',
    'AiThreadFileController.delete': 'write',
    'MobilePushNotificationController.registerInstallation': 'write',
    'MobilePushNotificationController.registerLiveActivityPushToStartToken':
        'write',
    'MobilePushNotificationController.revokeInstallation': 'write',
    'AiAgentLiveActivityController.registerLiveActivity': 'write',
    'AiAgentLiveActivityController.revokeLiveActivity': 'write',
    'organizationRouter.getOrganizationAccess': 'read',
    'organizationRouter.getActiveCreateProjectJob': 'read',
    'organizationRouter.getOnboarding': 'read',
    'organizationRouter.setOnboardingSuccessDate': 'write',
    'dashboardRouter.getDashboardViews': 'read',
    'UserService.verifyEmail': 'write',
} as const;

export const assertOAuthScopeOperation = (
    actor: Account | SessionUser,
    operation: keyof typeof OAUTH_UNCHECKED_OPERATIONS,
): void => {
    if (isAccount(actor) && actor.authentication.type !== 'oauth') return;
    const context = getOAuthScopeContext(
        isAccount(actor) ? actor.user.ability : actor.ability,
    );
    if (context === null) return;
    const classification = Object.hasOwn(OAUTH_UNCHECKED_OPERATIONS, operation)
        ? OAUTH_UNCHECKED_OPERATIONS[operation]
        : null;
    const allowed =
        classification !== null &&
        context.scopes.some(
            (scope) =>
                scope === 'write' ||
                scope === 'mcp:write' ||
                (classification === 'read' &&
                    (scope === 'read' || scope === 'mcp:read')),
        );
    if (allowed) return;
    context.record(classification ?? 'unknown', operation, null);
    if (context.mode === 'enforce') {
        throw new ForbiddenError('OAuth scope does not allow this operation');
    }
};

export const requireOAuthScopeOperation =
    (operation: keyof typeof OAUTH_UNCHECKED_OPERATIONS): RequestHandler =>
    (req, _res, next) => {
        try {
            if (req.account) {
                assertOAuthScopeOperation(req.account, operation);
            }
            next();
        } catch (error) {
            next(error);
        }
    };
