import {
    getTotalFilterRules,
    isSlackPrompt,
    toolTimeSeriesArgsSchema,
    toolTimeSeriesArgsSchemaTransformed,
} from '@lightdash/common';
import { tool } from 'ai';
import type {
    GetExploreFn,
    GetPromptFn,
    RunMiniMetricQueryFn,
    SendFileFn,
    UpdateProgressFn,
    UpdatePromptFn,
} from '../types/aiAgentDependencies';
import { renderEcharts } from '../utils/renderEcharts';
import { toolErrorHandler } from '../utils/toolErrorHandler';
import { validateFilterRules } from '../utils/validators';
import { renderTimeSeriesViz } from '../visualizations/vizTimeSeries';

type Dependencies = {
    getExplore: GetExploreFn;
    updateProgress: UpdateProgressFn;
    runMiniMetricQuery: RunMiniMetricQueryFn;
    getPrompt: GetPromptFn;
    updatePrompt: UpdatePromptFn;
    sendFile: SendFileFn;
    maxLimit: number;
};
export const getGenerateTimeSeriesVizConfig = ({
    getExplore,
    updateProgress,
    runMiniMetricQuery,
    getPrompt,
    sendFile,
    updatePrompt,
    maxLimit,
}: Dependencies) => {
    const schema = toolTimeSeriesArgsSchema;

    return tool({
        description: `Generate Time Series Chart Visualization and show it to the user.
This tool works well for questions about data over time, e.g. "per day/week/month".

Example questions:
- "Show me the revenue per day for the last 30 days."
- "Show me the number of orders per week for the last 6 months."

Rules for generating the time series chart visualization:
- The dimension and metric "fieldIds" must come from an explore. If you haven't used "findFieldsInExplore" tool, please do so before using this tool.
- If the data needs to be filtered, generate the filters using the "generateQueryFilters" tool before using this tool.`,
        parameters: schema,
        execute: async (toolArgs) => {
            try {
                await updateProgress('📈 Generating your line chart...');

                // TODO: common for all viz tools. find a way to reuse this code.
                const vizTool =
                    toolTimeSeriesArgsSchemaTransformed.parse(toolArgs);

                const filterRules = getTotalFilterRules(vizTool.filters);
                const explore = await getExplore({
                    exploreName: vizTool.vizConfig.exploreName,
                });
                validateFilterRules(explore, filterRules);
                // end of TODO

                const prompt = await getPrompt();
                await updatePrompt({
                    promptUuid: prompt.promptUuid,
                    vizConfigOutput: toolArgs,
                });

                if (isSlackPrompt(prompt)) {
                    const { chartOptions } = await renderTimeSeriesViz({
                        runMetricQuery: (q) => runMiniMetricQuery(q, maxLimit),
                        vizTool,
                        maxLimit,
                    });

                    const file = await renderEcharts(chartOptions);
                    await updateProgress('✅ Done.');

                    const sentfileArgs = {
                        channelId: prompt.slackChannelId,
                        threadTs: prompt.slackThreadTs,
                        organizationUuid: prompt.organizationUuid,
                        title: 'Generated by Lightdash',
                        comment: `Line chart generated by Lightdash`,
                        filename: 'lightdash-query-results.png',
                        file,
                    };
                    await sendFile(sentfileArgs);
                }

                return `Success`;
            } catch (e) {
                return toolErrorHandler(e, `Error generating line chart.`);
            }
        },
    });
};
