import {
    getTotalFilterRules,
    isSlackPrompt,
    toolTableVizArgsSchema,
    toolTableVizArgsSchemaTransformed,
} from '@lightdash/common';
import { tool } from 'ai';
import type {
    GetExploreFn,
    GetPromptFn,
    RunMiniMetricQueryFn,
    SendFileFn,
    UpdateProgressFn,
    UpdatePromptFn,
} from '../types/aiAgentDependencies';
import { toolErrorHandler } from '../utils/toolErrorHandler';
import { validateFilterRules } from '../utils/validators';
import { renderTableViz } from '../visualizations/vizTable';

type Dependencies = {
    getExplore: GetExploreFn;
    updateProgress: UpdateProgressFn;
    runMiniMetricQuery: RunMiniMetricQueryFn;
    getPrompt: GetPromptFn;
    updatePrompt: UpdatePromptFn;
    sendFile: SendFileFn;
    maxLimit: number;
};
export const getGenerateTableVizConfig = ({
    getExplore,
    runMiniMetricQuery,
    getPrompt,
    sendFile,
    updatePrompt,
    updateProgress,
    maxLimit,
}: Dependencies) => {
    const schema = toolTableVizArgsSchema;

    return tool({
        description: `Use this tool to generate a Table.`,
        parameters: schema,
        execute: async (toolArgs) => {
            try {
                await updateProgress('🔢 Generating your table...');

                // TODO: common for all viz tools. find a way to reuse this code.
                const vizTool =
                    toolTableVizArgsSchemaTransformed.parse(toolArgs);

                const filterRules = getTotalFilterRules(vizTool.filters);
                const explore = await getExplore({
                    exploreName: vizTool.vizConfig.exploreName,
                });
                validateFilterRules(explore, filterRules);
                // end of TODO

                const prompt = await getPrompt();
                await updatePrompt({
                    promptUuid: prompt.promptUuid,
                    vizConfigOutput: toolArgs,
                });

                if (isSlackPrompt(prompt)) {
                    const { csv } = await renderTableViz({
                        runMetricQuery: (q) => runMiniMetricQuery(q, maxLimit),
                        vizTool,
                        maxLimit,
                    });

                    const file = Buffer.from(csv, 'utf8');
                    await updateProgress('✅ Done.');

                    const sentfileArgs = {
                        channelId: prompt.slackChannelId,
                        threadTs: prompt.slackThreadTs,
                        organizationUuid: prompt.organizationUuid,
                        title: 'Generated by Lightdash',
                        comment: `CSV results generated by Lightdash`,
                        filename: 'lightdash-query-results.csv',
                        file,
                    };

                    await sendFile(sentfileArgs);
                }

                return `Success`;
            } catch (e) {
                return toolErrorHandler(e, `Error generating CSV.`);
            }
        },
    });
};
