import {
    Explore,
    getTotalFilterRules,
    isSlackPrompt,
    toolVerticalBarArgsSchema,
    toolVerticalBarArgsSchemaTransformed,
    ToolVerticalBarArgsTransformed,
} from '@lightdash/common';
import { tool } from 'ai';
import type {
    CreateOrUpdateArtifactFn,
    GetExploreFn,
    GetPromptFn,
    RunMiniMetricQueryFn,
    SendFileFn,
    UpdateProgressFn,
    UpdatePromptFn,
} from '../types/aiAgentDependencies';
import { renderEcharts } from '../utils/renderEcharts';
import { toolErrorHandler } from '../utils/toolErrorHandler';
import { validateBarVizConfig } from '../utils/validateBarVizConfig';
import { renderVerticalBarViz } from '../visualizations/vizVerticalBar';

type Dependencies = {
    getExplore: GetExploreFn;
    updateProgress: UpdateProgressFn;
    runMiniMetricQuery: RunMiniMetricQueryFn;
    getPrompt: GetPromptFn;
    updatePrompt: UpdatePromptFn;
    sendFile: SendFileFn;
    createOrUpdateArtifact: CreateOrUpdateArtifactFn;
    maxLimit: number;
};

export const getGenerateBarVizConfig = ({
    getExplore,
    updateProgress,
    runMiniMetricQuery,
    getPrompt,
    sendFile,
    updatePrompt,
    createOrUpdateArtifact,
    maxLimit,
}: Dependencies) => {
    const schema = toolVerticalBarArgsSchema;

    return tool({
        description: toolVerticalBarArgsSchema.description,
        parameters: schema,
        execute: async (toolArgs) => {
            try {
                await updateProgress('📊 Generating your bar chart...');

                // TODO: common for all viz tools. find a way to reuse this code.
                const vizTool =
                    toolVerticalBarArgsSchemaTransformed.parse(toolArgs);
                const explore = await getExplore({
                    exploreName: vizTool.vizConfig.exploreName,
                });
                validateBarVizConfig(vizTool, explore);
                // end of TODO

                const prompt = await getPrompt();

                await createOrUpdateArtifact({
                    threadUuid: prompt.threadUuid,
                    promptUuid: prompt.promptUuid,
                    artifactType: 'chart',
                    title: toolArgs.title,
                    description: toolArgs.description,
                    vizConfig: toolArgs,
                });

                // TODO :: keeping this for now, until the front-end is under feature-flag
                await updatePrompt({
                    promptUuid: prompt.promptUuid,
                    vizConfigOutput: toolArgs,
                });

                if (isSlackPrompt(prompt)) {
                    const { chartOptions } = await renderVerticalBarViz({
                        runMetricQuery: (q) => runMiniMetricQuery(q, maxLimit),
                        vizTool,
                        maxLimit,
                    });

                    const file = await renderEcharts(chartOptions);
                    await updateProgress('✅ Done.');

                    const sentfileArgs = {
                        channelId: prompt.slackChannelId,
                        threadTs: prompt.slackThreadTs,
                        organizationUuid: prompt.organizationUuid,
                        title: 'Generated by Lightdash',
                        comment: `Bar chart generated by Lightdash`,
                        filename: 'lightdash-query-results.png',
                        file,
                    };
                    await sendFile(sentfileArgs);
                }

                return `Success`;
            } catch (e) {
                return toolErrorHandler(e, `Error generating bar chart.`);
            }
        },
    });
};
