import {
    buildChartAsCodeArtifact,
    generateVisualizationToolDefinition,
    getChartAsCodeEchartsConfig,
    getChartAsCodeMetricQuery,
    getTotalFilterRules,
    isPeriodOverPeriodAdditionalMetric,
    isSlackPrompt,
    toolGenerateVisualizationArgsSchemaTransformed,
    type ChartAsCode,
    type ChartAsCodeMetricQueryInput,
} from '@lightdash/common';
import { tool } from 'ai';
import { NO_RESULTS_RETRY_PROMPT } from '../prompts/noResultsRetry';
import type {
    CreateOrUpdateArtifactFn,
    GetPromptFn,
    RunAsyncQueryFn,
    SendFileFn,
    UpdateProgressFn,
    ValidateContentFn,
} from '../types/aiAgentDependencies';
import { AgentContext } from '../utils/AgentContext';
import { convertQueryResultsToCsv } from '../utils/convertQueryResultsToCsv';
import { getPivotedResults } from '../utils/getPivotedResults';
import { renderEcharts } from '../utils/renderEcharts';
import { serializeData } from '../utils/serializeData';
import { toModelOutput } from '../utils/toModelOutput';
import { toolErrorHandler } from '../utils/toolErrorHandler';
import {
    validateCustomMetricsDefinition,
    validateFilterRules,
    validatePivotColumnsAreSelectedDimensions,
    validateSelectedFieldsExistence,
    validateSortFieldsAreSelected,
} from '../utils/validators';

type Dependencies = {
    updateProgress: UpdateProgressFn;
    runAsyncQuery: RunAsyncQueryFn;
    getPrompt: GetPromptFn;
    sendFile: SendFileFn;
    createOrUpdateArtifact: CreateOrUpdateArtifactFn;
    validateContent: ValidateContentFn;
    maxLimit: number;
    enableDataAccess: boolean;
};

const toolDefinition = generateVisualizationToolDefinition.for('agent');

export const getGenerateVisualization = ({
    updateProgress,
    runAsyncQuery,
    getPrompt,
    sendFile,
    createOrUpdateArtifact,
    validateContent,
    maxLimit,
    enableDataAccess,
}: Dependencies) =>
    tool({
        ...toolDefinition,
        execute: async (toolArgs, { experimental_context: context }) => {
            try {
                await updateProgress('Running your query...');

                const parsedToolArgs =
                    toolGenerateVisualizationArgsSchemaTransformed.parse(
                        toolArgs,
                    );
                const title = parsedToolArgs.title || 'Generated by Lightdash';
                const chartAsCodeArtifact = buildChartAsCodeArtifact({
                    name: title,
                    description: parsedToolArgs.description,
                    tableName: parsedToolArgs.tableName,
                    // Boundary casts: validated against chart-as-code-1.0 below.
                    metricQuery:
                        parsedToolArgs.metricQuery as ChartAsCodeMetricQueryInput,
                    chartConfig:
                        parsedToolArgs.chartConfig as ChartAsCode['chartConfig'],
                    pivotConfig: parsedToolArgs.pivotConfig,
                    tableConfig: parsedToolArgs.tableConfig,
                    maxLimit,
                });
                validateContent({
                    type: 'chart',
                    content: chartAsCodeArtifact,
                });

                const metricQuery = getChartAsCodeMetricQuery(
                    chartAsCodeArtifact,
                    maxLimit,
                );
                const ctx = AgentContext.from(context);
                const explore = ctx.getExplore(metricQuery.exploreName);

                const { additionalMetrics, tableCalculations } = metricQuery;
                const aggregationCustomMetrics = additionalMetrics.filter(
                    (metric) => !isPeriodOverPeriodAdditionalMetric(metric),
                );

                validateSelectedFieldsExistence(
                    explore,
                    [...metricQuery.dimensions, ...metricQuery.metrics],
                    additionalMetrics,
                    tableCalculations,
                );
                validateCustomMetricsDefinition(
                    explore,
                    aggregationCustomMetrics,
                );
                validateFilterRules(
                    explore,
                    getTotalFilterRules(metricQuery.filters),
                    aggregationCustomMetrics,
                    tableCalculations,
                );
                validateSelectedFieldsExistence(
                    explore,
                    metricQuery.sorts.map((sort) => sort.fieldId),
                    additionalMetrics,
                    tableCalculations,
                );
                validateSortFieldsAreSelected(
                    metricQuery.sorts,
                    metricQuery.dimensions,
                    metricQuery.metrics,
                    additionalMetrics,
                    tableCalculations,
                );
                validatePivotColumnsAreSelectedDimensions(
                    chartAsCodeArtifact.pivotConfig?.columns,
                    metricQuery.dimensions,
                );

                const prompt = await getPrompt();
                const createOrUpdateArtifactHook = () =>
                    createOrUpdateArtifact({
                        threadUuid: prompt.threadUuid,
                        promptUuid: prompt.promptUuid,
                        artifactType: 'chart',
                        title: parsedToolArgs.title,
                        description: parsedToolArgs.description,
                        vizConfig: chartAsCodeArtifact,
                    });

                if (!enableDataAccess && !isSlackPrompt(prompt)) {
                    await createOrUpdateArtifactHook();
                    return {
                        result: 'Success',
                        metadata: { status: 'success' },
                    };
                }

                const queryResults = await runAsyncQuery(metricQuery);

                if (queryResults.rows.length === 0) {
                    return {
                        result: NO_RESULTS_RETRY_PROMPT,
                        metadata: { status: 'success' },
                    };
                }

                await createOrUpdateArtifactHook();

                // Render chart as image for Slack, or send CSV for tables
                if (isSlackPrompt(prompt)) {
                    const echartsOptions = await getChartAsCodeEchartsConfig({
                        chartAsCode: chartAsCodeArtifact,
                        queryResults,
                        getPivotedResults,
                        maxLimit,
                    });

                    if (echartsOptions) {
                        const chartImage = await renderEcharts(echartsOptions);
                        await sendFile({
                            channelId: prompt.slackChannelId,
                            threadTs: prompt.slackThreadTs,
                            organizationUuid: prompt.organizationUuid,
                            title,
                            comment:
                                parsedToolArgs.description ||
                                'Chart generated by Lightdash',
                            filename: 'lightdash-chart.png',
                            file: chartImage,
                        });
                    } else {
                        const csvData = convertQueryResultsToCsv(queryResults);
                        await sendFile({
                            channelId: prompt.slackChannelId,
                            threadTs: prompt.slackThreadTs,
                            organizationUuid: prompt.organizationUuid,
                            title,
                            comment:
                                parsedToolArgs.description ||
                                'Table generated by Lightdash',
                            filename: 'lightdash-results.csv',
                            file: Buffer.from(csvData, 'utf-8'),
                        });
                    }
                }

                if (!enableDataAccess) {
                    return {
                        result: 'Success.',
                        metadata: { status: 'success' },
                    };
                }

                const csv = convertQueryResultsToCsv(queryResults);
                return {
                    result: serializeData(csv, 'csv'),
                    metadata: { status: 'success' },
                };
            } catch (e) {
                return {
                    result: toolErrorHandler(
                        e,
                        `Error running query. Please try again with a valid metric query and chart-as-code chartConfig.`,
                    ),
                    metadata: { status: 'error' },
                };
            }
        },
        toModelOutput: ({ output }) => toModelOutput(output),
    });
