import { filtersSchemaTransformed, isSlackPrompt } from '@lightdash/common';
import { tool } from 'ai';
import type {
    GetPromptFn,
    RunMiniMetricQueryFn,
    SendFileFn,
    UpdateProgressFn,
    UpdatePromptFn,
} from '../types/aiAgentDependencies';
import { toolErrorHandler } from '../utils/toolErrorHandler';
import { renderEcharts } from '../visualizations/renderEcharts';
import {
    generateTimeSeriesVizConfigToolSchema,
    renderTimeseriesChart,
} from '../visualizations/timeSeriesChart';

type Dependencies = {
    updateProgress: UpdateProgressFn;
    runMiniMetricQuery: RunMiniMetricQueryFn;
    getPrompt: GetPromptFn;
    updatePrompt: UpdatePromptFn;
    sendFile: SendFileFn;
};
export const getGenerateTimeSeriesVizConfig = ({
    updateProgress,
    runMiniMetricQuery,
    getPrompt,
    sendFile,
    updatePrompt,
}: Dependencies) => {
    const schema = generateTimeSeriesVizConfigToolSchema;

    return tool({
        description: `Generate Time Series Chart Visualization and show it to the user.

This tool works well for questions about data over time, e.g. "per day/week/month".

Example questions:
- "Show me the revenue per day for the last 30 days."
- "Show me the number of orders per week for the last 6 months."

Rules for generating the time series chart visualization:
- The dimension and metric "fieldIds" must come from an explore. If you haven't used "findFieldsInExplore" tool, please do so before using this tool.
- If the data needs to be filtered, generate the filters using the "generateQueryFilters" tool before using this tool.`,
        parameters: schema,
        execute: async ({ filters, vizConfig }) => {
            try {
                // Transform filters to the correct format for the query and keep the original format for the tool call args
                const transformedFilters =
                    filtersSchemaTransformed.parse(filters);
                await updateProgress(
                    '🔍 Running a query for your line chart...',
                );

                const prompt = await getPrompt();

                await updateProgress('📈 Generating your line chart...');

                const { chartOptions, metricQuery } =
                    await renderTimeseriesChart({
                        runMetricQuery: runMiniMetricQuery,
                        vizConfig,
                        filters: transformedFilters ?? undefined,
                    });

                const file = await renderEcharts(chartOptions);

                await updatePrompt({
                    promptUuid: prompt.promptUuid,
                    vizConfigOutput: vizConfig,
                    metricQuery,
                });

                if (isSlackPrompt(prompt)) {
                    const sentfileArgs = {
                        channelId: prompt.slackChannelId,
                        threadTs: prompt.slackThreadTs,
                        organizationUuid: prompt.organizationUuid,
                        title: 'Generated by Lightdash',
                        comment: `Line chart generated by Lightdash`,
                        filename: 'lightdash-query-results.png',
                        file,
                    };
                    await sendFile(sentfileArgs);
                }

                return `A line chart has been successfully generated and shown to the user.`;
            } catch (e) {
                return toolErrorHandler(e, `Error generating line chart.`);
            }
        },
    });
};
