import {
    convertAiTableCalcsSchemaToTableCalcs,
    isSlackPrompt,
    metricQueryTableViz,
    toolTableVizArgsSchema,
    toolTableVizArgsSchemaTransformed,
    toolTableVizOutputSchema,
} from '@lightdash/common';
import { tool } from 'ai';
import type {
    CreateOrUpdateArtifactFn,
    GetExploreFn,
    GetPromptFn,
    RunMiniMetricQueryFn,
    SendFileFn,
    UpdateProgressFn,
} from '../types/aiAgentDependencies';
import { convertQueryResultsToCsv } from '../utils/convertQueryResultsToCsv';
import { populateCustomMetricsSQL } from '../utils/populateCustomMetricsSQL';
import { serializeData } from '../utils/serializeData';
import { toModelOutput } from '../utils/toModelOutput';
import { toolErrorHandler } from '../utils/toolErrorHandler';
import { validateTableVizConfig } from '../utils/validateTableVizConfig';

type Dependencies = {
    getExplore: GetExploreFn;
    updateProgress: UpdateProgressFn;
    runMiniMetricQuery: RunMiniMetricQueryFn;
    getPrompt: GetPromptFn;
    sendFile: SendFileFn;
    createOrUpdateArtifact: CreateOrUpdateArtifactFn;
    maxLimit: number;
    enableDataAccess: boolean;
    enableSelfImprovement: boolean;
};

export const getGenerateTableVizConfig = ({
    getExplore,
    runMiniMetricQuery,
    getPrompt,
    sendFile,
    updateProgress,
    createOrUpdateArtifact,
    maxLimit,
    enableDataAccess,
    enableSelfImprovement,
}: Dependencies) =>
    tool({
        description: toolTableVizArgsSchema.description,
        inputSchema: toolTableVizArgsSchema,
        outputSchema: toolTableVizOutputSchema,
        execute: async (toolArgs) => {
            try {
                await updateProgress('🔢 Querying the data...');

                // TODO: common for all viz tools. find a way to reuse this code.
                const vizTool =
                    toolTableVizArgsSchemaTransformed.parse(toolArgs);

                const explore = await getExplore({
                    exploreName: vizTool.vizConfig.exploreName,
                });

                validateTableVizConfig(vizTool, explore);
                // end of TODO

                const prompt = await getPrompt();

                const createOrUpdateArtifactHook = () =>
                    createOrUpdateArtifact({
                        threadUuid: prompt.threadUuid,
                        promptUuid: prompt.promptUuid,
                        artifactType: 'chart',
                        title: toolArgs.title,
                        description: toolArgs.description,
                        vizConfig: toolArgs,
                    });

                const selfImprovementResultFollowUp =
                    enableSelfImprovement &&
                    vizTool.customMetrics &&
                    vizTool.customMetrics.length > 0
                        ? `\nCan you propose the creation of this metric as a metric to the semantic layer to the user?`
                        : '';

                const metricQuery = metricQueryTableViz({
                    vizConfig: vizTool.vizConfig,
                    filters: vizTool.filters,
                    maxLimit,
                    customMetrics: vizTool.customMetrics ?? null,
                    tableCalculations: convertAiTableCalcsSchemaToTableCalcs(
                        vizTool.tableCalculations,
                    ),
                });
                const queryResults = await runMiniMetricQuery(
                    metricQuery,
                    maxLimit,
                    populateCustomMetricsSQL(vizTool.customMetrics, explore),
                );
                await updateProgress('✅ Done.');

                const rowCount = queryResults.rows.length;
                const csv = convertQueryResultsToCsv(queryResults);

                await createOrUpdateArtifactHook();

                // Always send CSV file to Slack if it's a Slack prompt, unless there are no results
                if (isSlackPrompt(prompt) && rowCount > 0) {
                    await sendFile({
                        channelId: prompt.slackChannelId,
                        threadTs: prompt.slackThreadTs,
                        organizationUuid: prompt.organizationUuid,
                        title: 'Generated by Lightdash',
                        comment: `CSV results generated by Lightdash`,
                        filename: 'lightdash-query-results.csv',
                        file: Buffer.from(csv, 'utf8'),
                    });
                }

                if (rowCount === 0) {
                    return {
                        result: `The query returned no results`,
                        metadata: {
                            status: 'success',
                        },
                    };
                }

                if (!enableDataAccess) {
                    if (rowCount === 1) {
                        return {
                            result: `Here's the result:\n${serializeData(
                                csv,
                                'csv',
                            )} ${selfImprovementResultFollowUp}`,
                            metadata: {
                                status: 'success',
                            },
                        };
                    }

                    return {
                        result: `Success`,
                        metadata: {
                            status: 'success',
                        },
                    };
                }

                return {
                    result: `Here's the result:\n${serializeData(
                        csv,
                        'csv',
                    )} ${selfImprovementResultFollowUp}`,
                    metadata: {
                        status: 'success',
                    },
                };
            } catch (e) {
                return {
                    result: toolErrorHandler(
                        e,
                        `Error generating table visualization`,
                    ),
                    metadata: {
                        status: 'error',
                    },
                };
            }
        },
        toModelOutput: (output) => toModelOutput(output),
    });
