import {
    buildChartAsCodeArtifact,
    generateVisualizationToolDefinition,
    getChartAsCodeMetricQuery,
    isSlackPrompt,
    toolGenerateVisualizationArgsSchemaTransformed,
} from '@lightdash/common';
import { tool } from 'ai';
import { NO_RESULTS_RETRY_PROMPT } from '../prompts/noResultsRetry';
import type {
    CreateOrUpdateArtifactFn,
    GetPromptFn,
    RunAsyncQueryFn,
    SendFileFn,
    UpdateProgressFn,
    ValidateContentFn,
} from '../types/aiAgentDependencies';
import { AgentContext } from '../utils/AgentContext';
import { convertQueryResultsToCsv } from '../utils/convertQueryResultsToCsv';
import { serializeData } from '../utils/serializeData';
import { toModelOutput } from '../utils/toModelOutput';
import { toolErrorHandler } from '../utils/toolErrorHandler';
import { validateSelectedFieldsExistence } from '../utils/validators';

type Dependencies = {
    updateProgress: UpdateProgressFn;
    runAsyncQuery: RunAsyncQueryFn;
    getPrompt: GetPromptFn;
    sendFile: SendFileFn;
    createOrUpdateArtifact: CreateOrUpdateArtifactFn;
    validateContent: ValidateContentFn;
    maxLimit: number;
    enableDataAccess: boolean;
};

const toolDefinition = generateVisualizationToolDefinition.for('agent');

export const getGenerateVisualization = ({
    updateProgress,
    runAsyncQuery,
    getPrompt,
    sendFile,
    createOrUpdateArtifact,
    validateContent,
    maxLimit,
    enableDataAccess,
}: Dependencies) =>
    tool({
        ...toolDefinition,
        execute: async (toolArgs, { experimental_context: context }) => {
            try {
                await updateProgress('Running your query...');

                const parsedToolArgs =
                    toolGenerateVisualizationArgsSchemaTransformed.parse(
                        toolArgs,
                    );
                const title = parsedToolArgs.title || 'Generated by Lightdash';
                const chartAsCodeArtifact = buildChartAsCodeArtifact({
                    name: title,
                    description: parsedToolArgs.description,
                    tableName: parsedToolArgs.tableName,
                    metricQuery: parsedToolArgs.metricQuery,
                    chartConfig: parsedToolArgs.chartConfig,
                    pivotConfig: parsedToolArgs.pivotConfig,
                    tableConfig: parsedToolArgs.tableConfig,
                    maxLimit,
                });
                validateContent({
                    type: 'chart',
                    content: chartAsCodeArtifact,
                });

                const metricQuery = getChartAsCodeMetricQuery(
                    chartAsCodeArtifact,
                    maxLimit,
                );
                const ctx = AgentContext.from(context);
                const explore = ctx.getExplore(metricQuery.exploreName);

                validateSelectedFieldsExistence(
                    explore,
                    [...metricQuery.dimensions, ...metricQuery.metrics],
                    metricQuery.additionalMetrics,
                    metricQuery.tableCalculations,
                );

                const prompt = await getPrompt();
                const createOrUpdateArtifactHook = () =>
                    createOrUpdateArtifact({
                        threadUuid: prompt.threadUuid,
                        promptUuid: prompt.promptUuid,
                        artifactType: 'chart',
                        title: parsedToolArgs.title,
                        description: parsedToolArgs.description,
                        vizConfig: chartAsCodeArtifact,
                    });

                if (!enableDataAccess && !isSlackPrompt(prompt)) {
                    await createOrUpdateArtifactHook();
                    return {
                        result: 'Success',
                        metadata: { status: 'success' },
                    };
                }

                const queryResults = await runAsyncQuery(metricQuery);

                if (queryResults.rows.length === 0) {
                    return {
                        result: NO_RESULTS_RETRY_PROMPT,
                        metadata: { status: 'success' },
                    };
                }

                await createOrUpdateArtifactHook();

                const csv = convertQueryResultsToCsv(queryResults);

                if (isSlackPrompt(prompt)) {
                    await sendFile({
                        channelId: prompt.slackChannelId,
                        threadTs: prompt.slackThreadTs,
                        organizationUuid: prompt.organizationUuid,
                        title: parsedToolArgs.title || 'Generated by Lightdash',
                        comment:
                            parsedToolArgs.description ||
                            'Chart generated by Lightdash',
                        filename: 'lightdash-results.csv',
                        file: Buffer.from(csv, 'utf-8'),
                    });
                }

                if (!enableDataAccess) {
                    return {
                        result: 'Success.',
                        metadata: { status: 'success' },
                    };
                }

                return {
                    result: serializeData(csv, 'csv'),
                    metadata: { status: 'success' },
                };
            } catch (e) {
                return {
                    result: toolErrorHandler(
                        e,
                        `Error running query. Please try again with a valid metric query and chart-as-code chartConfig.`,
                    ),
                    metadata: { status: 'error' },
                };
            }
        },
        toModelOutput: ({ output }) => toModelOutput(output),
    });
