import {
    isSlackPrompt,
    toolTimeSeriesArgsSchema,
    toolTimeSeriesArgsSchemaTransformed,
} from '@lightdash/common';
import { tool } from 'ai';
import type {
    CreateOrUpdateArtifactFn,
    GetExploreFn,
    GetPromptFn,
    RunMiniMetricQueryFn,
    SendFileFn,
    UpdateProgressFn,
} from '../types/aiAgentDependencies';
import { renderEcharts } from '../utils/renderEcharts';
import { toolErrorHandler } from '../utils/toolErrorHandler';
import { validateTimeSeriesVizConfig } from '../utils/validateTimeSeriesVizConfig';
import { renderTimeSeriesViz } from '../visualizations/vizTimeSeries';

type Dependencies = {
    getExplore: GetExploreFn;
    updateProgress: UpdateProgressFn;
    runMiniMetricQuery: RunMiniMetricQueryFn;
    getPrompt: GetPromptFn;
    sendFile: SendFileFn;
    createOrUpdateArtifact: CreateOrUpdateArtifactFn;
    maxLimit: number;
};

export const getGenerateTimeSeriesVizConfig = ({
    getExplore,
    updateProgress,
    runMiniMetricQuery,
    getPrompt,
    sendFile,
    createOrUpdateArtifact,
    maxLimit,
}: Dependencies) =>
    tool({
        description: toolTimeSeriesArgsSchema.description,
        inputSchema: toolTimeSeriesArgsSchema,
        execute: async (toolArgs) => {
            try {
                await updateProgress('📈 Generating your line chart...');

                // TODO: common for all viz tools. find a way to reuse this code.
                const vizTool =
                    toolTimeSeriesArgsSchemaTransformed.parse(toolArgs);
                const explore = await getExplore({
                    exploreName: vizTool.vizConfig.exploreName,
                });
                validateTimeSeriesVizConfig(vizTool, explore);
                // end of TODO

                const prompt = await getPrompt();

                // Create or update artifact
                await createOrUpdateArtifact({
                    threadUuid: prompt.threadUuid,
                    promptUuid: prompt.promptUuid,
                    artifactType: 'chart',
                    title: toolArgs.title,
                    description: toolArgs.description,
                    vizConfig: toolArgs,
                });

                if (isSlackPrompt(prompt)) {
                    const { chartOptions } = await renderTimeSeriesViz({
                        runMetricQuery: (q) => runMiniMetricQuery(q, maxLimit),
                        vizTool,
                        maxLimit,
                    });

                    const file = await renderEcharts(chartOptions);
                    await updateProgress('✅ Done.');

                    const sentfileArgs = {
                        channelId: prompt.slackChannelId,
                        threadTs: prompt.slackThreadTs,
                        organizationUuid: prompt.organizationUuid,
                        title: 'Generated by Lightdash',
                        comment: `Line chart generated by Lightdash`,
                        filename: 'lightdash-query-results.png',
                        file,
                    };
                    await sendFile(sentfileArgs);
                }

                return `Success`;
            } catch (e) {
                return toolErrorHandler(e, `Error generating line chart.`);
            }
        },
    });
