import { Ability } from '@casl/ability';
import {
    ForbiddenError,
    RequestMethod,
    type PersonalAccessTokenWithToken,
    type PossibleAbilities,
} from '@lightdash/common';
import { analyticsMock } from '../analytics/LightdashAnalytics.mock';
import { fromOauth, fromSession } from '../auth/account/account';
import { defaultSessionUser } from '../auth/account/account.mock';
import { lightdashConfigMock } from '../config/lightdashConfig.mock';
import type { PersonalAccessTokenModel } from '../models/DashboardModel/PersonalAccessTokenModel';
import { PersonalAccessTokenService } from './PersonalAccessTokenService';

const tokenResult: PersonalAccessTokenWithToken = {
    uuid: 'token-uuid',
    createdAt: new Date('2026-08-20T00:00:00.000Z'),
    lastUsedAt: null,
    rotatedAt: null,
    expiresAt: null,
    description: 'Test token',
    token: 'token-value',
};

const createDependencies = () => {
    const personalAccessTokenModel = {
        create: vi.fn<PersonalAccessTokenModel['create']>(),
        getUserToken: vi.fn<PersonalAccessTokenModel['getUserToken']>(),
        rotate: vi.fn<PersonalAccessTokenModel['rotate']>(),
    };
    vi.mocked(personalAccessTokenModel.create).mockResolvedValue(tokenResult);
    vi.mocked(personalAccessTokenModel.getUserToken).mockResolvedValue({
        ...tokenResult,
        expiresAt: new Date('2099-01-01T00:00:00.000Z'),
    });
    vi.mocked(personalAccessTokenModel.rotate).mockResolvedValue(tokenResult);

    return {
        personalAccessTokenModel,
        service: new PersonalAccessTokenService({
            analytics: analyticsMock,
            lightdashConfig: lightdashConfigMock,
            personalAccessTokenModel:
                personalAccessTokenModel as unknown as PersonalAccessTokenModel,
        }),
    };
};

const createSessionUser = () => {
    const ability = new Ability<PossibleAbilities>([
        { action: 'create', subject: 'PersonalAccessToken' },
        { action: 'update', subject: 'PersonalAccessToken' },
    ]);
    return {
        ...defaultSessionUser,
        ability,
        abilityRules: ability.rules,
    };
};

const tokenData = {
    autoGenerated: false,
    description: 'Test token',
    expiresAt: null,
};

describe('PersonalAccessTokenService.createPersonalAccessToken', () => {
    it('rejects a self-registered OAuth client', async () => {
        const { personalAccessTokenModel, service } = createDependencies();
        const account = fromOauth(createSessionUser(), {
            accessToken: 'oauth-token',
            client: {
                id: 'mcp-client-id',
                organizationUuid: null,
            },
        });

        await expect(
            service.createPersonalAccessToken(
                account,
                tokenData,
                RequestMethod.WEB_APP,
            ),
        ).rejects.toBeInstanceOf(ForbiddenError);
        expect(personalAccessTokenModel.create).not.toHaveBeenCalled();
    });

    it.each([
        fromOauth(createSessionUser(), {
            accessToken: 'oauth-token',
            client: {
                id: 'oauth-client-id',
                organizationUuid: 'organization-uuid',
            },
        }),
        fromSession(createSessionUser()),
    ])('allows other authenticated accounts', async (account) => {
        const { personalAccessTokenModel, service } = createDependencies();

        await expect(
            service.createPersonalAccessToken(
                account,
                tokenData,
                RequestMethod.WEB_APP,
            ),
        ).resolves.toEqual(tokenResult);
        expect(personalAccessTokenModel.create).toHaveBeenCalledOnce();
    });
});

describe('PersonalAccessTokenService.rotatePersonalAccessToken', () => {
    const rotation = { expiresAt: new Date('2099-02-01T00:00:00.000Z') };

    it('rejects a self-registered OAuth client', async () => {
        const { personalAccessTokenModel, service } = createDependencies();
        const account = fromOauth(createSessionUser(), {
            accessToken: 'oauth-token',
            client: {
                id: 'mcp-client-id',
                organizationUuid: null,
            },
        });

        await expect(
            service.rotatePersonalAccessToken(
                account,
                tokenResult.uuid,
                rotation,
            ),
        ).rejects.toBeInstanceOf(ForbiddenError);
        expect(personalAccessTokenModel.rotate).not.toHaveBeenCalled();
    });

    it.each([
        fromOauth(createSessionUser(), {
            accessToken: 'oauth-token',
            client: {
                id: 'oauth-client-id',
                organizationUuid: 'organization-uuid',
            },
        }),
        fromSession(createSessionUser()),
    ])('allows other authenticated accounts', async (account) => {
        const { personalAccessTokenModel, service } = createDependencies();

        await expect(
            service.rotatePersonalAccessToken(
                account,
                tokenResult.uuid,
                rotation,
            ),
        ).resolves.toEqual(tokenResult);
        expect(personalAccessTokenModel.rotate).toHaveBeenCalledOnce();
    });
});
