import { type AiAgentThread } from '@lightdash/common';
import { renderHook } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { useAiAgentThreadArtifact } from './useAiAgentThreadArtifact';

const { dispatchMock, deepResearchRegistrationStateMock } = vi.hoisted(() => ({
    dispatchMock: vi.fn(),
    deepResearchRegistrationStateMock: vi.fn(),
}));

vi.mock('../store/hooks', () => ({
    useAiAgentStoreDispatch: () => dispatchMock,
    useAiAgentStoreSelector: () => null,
}));

vi.mock('../store/aiArtifactSlice', () => ({
    clearPreview: () => ({ type: 'clearPreview' }),
    setArtifact: (payload: unknown) => ({ type: 'setArtifact', payload }),
}));

vi.mock('./useDeepResearch', () => ({
    useDeepResearchThreadRunRegistrationState:
        deepResearchRegistrationStateMock,
}));

const thread = {
    uuid: 'thread-1',
    messages: [
        {
            role: 'user',
            uuid: 'deep-research-prompt',
            message: 'Research revenue by country',
        },
        {
            role: 'assistant',
            uuid: 'deep-research-prompt',
            artifacts: [
                {
                    artifactUuid: 'artifact-1',
                    versionUuid: 'version-1',
                },
            ],
        },
    ],
} as AiAgentThread;

const regularArtifactThread = {
    ...thread,
    messages: [
        ...thread.messages,
        {
            role: 'user',
            uuid: 'regular-prompt',
            message: 'Show revenue by payment method',
        },
        {
            role: 'assistant',
            uuid: 'regular-prompt',
            artifacts: [
                {
                    artifactUuid: 'regular-artifact',
                    versionUuid: 'regular-version',
                },
            ],
        },
    ],
} as AiAgentThread;

describe('useAiAgentThreadArtifact', () => {
    beforeEach(() => {
        dispatchMock.mockReset();
        deepResearchRegistrationStateMock.mockReturnValue({
            registrations: [
                {
                    runUuid: 'run-1',
                    promptUuid: 'deep-research-prompt',
                },
            ],
            isReady: true,
        });
    });

    it('does not auto-open artifacts generated by Deep Research', () => {
        renderHook(() =>
            useAiAgentThreadArtifact({
                projectUuid: 'project-1',
                agentUuid: 'agent-1',
                threadUuid: 'thread-1',
                thread,
            }),
        );

        expect(dispatchMock).not.toHaveBeenCalledWith(
            expect.objectContaining({ type: 'setArtifact' }),
        );
    });

    it('auto-opens a regular artifact while Deep Research is registered', () => {
        renderHook(() =>
            useAiAgentThreadArtifact({
                projectUuid: 'project-1',
                agentUuid: 'agent-1',
                threadUuid: 'thread-1',
                thread: regularArtifactThread,
            }),
        );

        expect(dispatchMock).toHaveBeenCalledWith({
            type: 'setArtifact',
            payload: {
                artifactUuid: 'regular-artifact',
                versionUuid: 'regular-version',
                messageUuid: 'regular-prompt',
                threadUuid: 'thread-1',
                projectUuid: 'project-1',
                agentUuid: 'agent-1',
            },
        });
    });

    it('does not auto-open while Deep Research registration lookup is unresolved', () => {
        deepResearchRegistrationStateMock.mockReturnValue({
            registrations: [],
            isReady: false,
        });

        renderHook(() =>
            useAiAgentThreadArtifact({
                projectUuid: 'project-1',
                agentUuid: 'agent-1',
                threadUuid: 'thread-1',
                thread: regularArtifactThread,
            }),
        );

        expect(dispatchMock).not.toHaveBeenCalledWith(
            expect.objectContaining({ type: 'setArtifact' }),
        );
    });

    it('keeps a Deep Research artifact closed when registration loading completes', () => {
        deepResearchRegistrationStateMock.mockReturnValue({
            registrations: [],
            isReady: false,
        });

        const { rerender } = renderHook(() =>
            useAiAgentThreadArtifact({
                projectUuid: 'project-1',
                agentUuid: 'agent-1',
                threadUuid: 'thread-1',
                thread,
            }),
        );

        deepResearchRegistrationStateMock.mockReturnValue({
            registrations: [
                {
                    runUuid: 'run-1',
                    promptUuid: 'deep-research-prompt',
                },
            ],
            isReady: true,
        });
        rerender();

        expect(dispatchMock).not.toHaveBeenCalledWith(
            expect.objectContaining({ type: 'setArtifact' }),
        );
    });
});
