import { type AiAgentThread } from '@lightdash/common';
import { renderHook } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { useAiAgentThreadArtifact } from './useAiAgentThreadArtifact';

const {
    fastDecisionsMock,
    dispatchMock,
    deepResearchRegistrationStateMock,
    artifactSelectorMock,
} = vi.hoisted(() => ({
    fastDecisionsMock: vi.fn(),
    dispatchMock: vi.fn(),
    artifactSelectorMock: vi.fn(),
    deepResearchRegistrationStateMock: vi.fn(),
}));

vi.mock('../../../../hooks/useServerOrClientFeatureFlag', () => ({
    useServerFeatureFlag: fastDecisionsMock,
}));

vi.mock('../store/hooks', () => ({
    useAiAgentStoreDispatch: () => dispatchMock,
    useAiAgentStoreSelector: artifactSelectorMock,
}));

vi.mock('../store/aiArtifactSlice', () => ({
    clearPreview: () => ({ type: 'clearPreview' }),
    setPreview: (payload: unknown) => ({ type: 'setPreview', payload }),
    selectArtifactPreview: () => null,
}));

vi.mock('./useDeepResearch', () => ({
    useDeepResearchThreadRunRegistrationState:
        deepResearchRegistrationStateMock,
}));

const thread = {
    uuid: 'thread-1',
    messages: [
        {
            role: 'user',
            uuid: 'deep-research-prompt',
            message: 'Research revenue by country',
        },
        {
            role: 'assistant',
            uuid: 'deep-research-prompt',
            artifacts: [
                {
                    artifactUuid: 'artifact-1',
                    versionUuid: 'version-1',
                },
            ],
        },
    ],
} as AiAgentThread;

const regularArtifactThread = {
    ...thread,
    messages: [
        ...thread.messages,
        {
            role: 'user',
            uuid: 'regular-prompt',
            message: 'Show revenue by payment method',
        },
        {
            role: 'assistant',
            uuid: 'regular-prompt',
            artifacts: [
                {
                    artifactUuid: 'regular-artifact',
                    versionUuid: 'regular-version',
                },
            ],
        },
    ],
} as AiAgentThread;

describe('useAiAgentThreadArtifact', () => {
    beforeEach(() => {
        fastDecisionsMock.mockReturnValue({ data: { enabled: true } });
        dispatchMock.mockReset();
        artifactSelectorMock.mockReset().mockReturnValue(null);
        deepResearchRegistrationStateMock.mockReturnValue({
            registrations: [
                {
                    runUuid: 'run-1',
                    promptUuid: 'deep-research-prompt',
                },
            ],
            isReady: true,
        });
    });

    it('does not auto-open artifacts generated by Deep Research', () => {
        renderHook(() =>
            useAiAgentThreadArtifact({
                projectUuid: 'project-1',
                agentUuid: 'agent-1',
                threadUuid: 'thread-1',
                thread,
            }),
        );

        expect(dispatchMock).not.toHaveBeenCalledWith(
            expect.objectContaining({ type: 'setPreview' }),
        );
    });

    it('auto-opens a regular artifact while Deep Research is registered', () => {
        renderHook(() =>
            useAiAgentThreadArtifact({
                projectUuid: 'project-1',
                agentUuid: 'agent-1',
                threadUuid: 'thread-1',
                thread: regularArtifactThread,
            }),
        );

        expect(dispatchMock).toHaveBeenCalledWith({
            type: 'setPreview',
            payload: {
                type: 'artifact',
                artifactUuid: 'regular-artifact',
                versionUuid: 'regular-version',
                messageUuid: 'regular-prompt',
                threadUuid: 'thread-1',
                projectUuid: 'project-1',
                agentUuid: 'agent-1',
            },
        });
    });

    it('does not auto-open while Deep Research registration lookup is unresolved', () => {
        deepResearchRegistrationStateMock.mockReturnValue({
            registrations: [],
            isReady: false,
        });

        renderHook(() =>
            useAiAgentThreadArtifact({
                projectUuid: 'project-1',
                agentUuid: 'agent-1',
                threadUuid: 'thread-1',
                thread: regularArtifactThread,
            }),
        );

        expect(dispatchMock).not.toHaveBeenCalledWith(
            expect.objectContaining({ type: 'setPreview' }),
        );
    });

    it('keeps a Deep Research artifact closed when registration loading completes', () => {
        deepResearchRegistrationStateMock.mockReturnValue({
            registrations: [],
            isReady: false,
        });

        const { rerender } = renderHook(() =>
            useAiAgentThreadArtifact({
                projectUuid: 'project-1',
                agentUuid: 'agent-1',
                threadUuid: 'thread-1',
                thread,
            }),
        );

        deepResearchRegistrationStateMock.mockReturnValue({
            registrations: [
                {
                    runUuid: 'run-1',
                    promptUuid: 'deep-research-prompt',
                },
            ],
            isReady: true,
        });
        rerender();

        expect(dispatchMock).not.toHaveBeenCalledWith(
            expect.objectContaining({ type: 'setPreview' }),
        );
    });

    it.each([false, undefined])(
        'does not follow revisions when the flag is off or unresolved (%s)',
        (enabled) => {
            fastDecisionsMock.mockReturnValue({
                data: enabled === undefined ? undefined : { enabled },
            });
            const { rerender } = renderHook(
                ({ currentThread }) =>
                    useAiAgentThreadArtifact({
                        projectUuid: 'project-1',
                        agentUuid: 'agent-1',
                        threadUuid: 'thread-1',
                        thread: currentThread,
                    }),
                { initialProps: { currentThread: regularArtifactThread } },
            );
            const first = dispatchMock.mock.calls.findLast(
                ([action]) => action.type === 'setPreview',
            )?.[0].payload;
            artifactSelectorMock.mockReturnValue(first);
            rerender({ currentThread: regularArtifactThread });
            dispatchMock.mockClear();
            rerender({
                currentThread: {
                    ...regularArtifactThread,
                    messages: regularArtifactThread.messages.map((message) =>
                        message.role === 'assistant' &&
                        message.uuid === 'regular-prompt'
                            ? {
                                  ...message,
                                  artifacts: [
                                      {
                                          artifactUuid: 'regular-artifact',
                                          versionUuid: 'version-2',
                                      },
                                  ],
                              }
                            : message,
                    ),
                } as AiAgentThread,
            });
            expect(dispatchMock).not.toHaveBeenCalledWith(
                expect.objectContaining({ type: 'setPreview' }),
            );
        },
    );

    it.each(['closed', 'manual version'])(
        'follows streamed revisions until the preview is %s',
        (manualAction) => {
            const updatedThread = (versionUuid: string) =>
                ({
                    ...regularArtifactThread,
                    messages: regularArtifactThread.messages.map((message) =>
                        message.role === 'assistant' &&
                        message.uuid === 'regular-prompt'
                            ? {
                                  ...message,
                                  artifacts: [
                                      {
                                          artifactUuid: 'regular-artifact',
                                          versionUuid,
                                      },
                                  ],
                              }
                            : message,
                    ),
                }) as AiAgentThread;
            const { rerender } = renderHook(
                ({ currentThread }) =>
                    useAiAgentThreadArtifact({
                        projectUuid: 'project-1',
                        agentUuid: 'agent-1',
                        threadUuid: 'thread-1',
                        thread: currentThread,
                    }),
                { initialProps: { currentThread: regularArtifactThread } },
            );
            const first = dispatchMock.mock.calls.findLast(
                ([action]) => action.type === 'setPreview',
            )?.[0].payload;
            artifactSelectorMock.mockReturnValue(first);
            rerender({ currentThread: regularArtifactThread });
            rerender({ currentThread: updatedThread('version-2') });
            expect(dispatchMock).toHaveBeenLastCalledWith({
                type: 'setPreview',
                payload: { ...first, versionUuid: 'version-2' },
            });
            artifactSelectorMock.mockReturnValue({
                ...first,
                versionUuid: 'version-2',
            });
            rerender({ currentThread: updatedThread('version-2') });
            artifactSelectorMock.mockReturnValue(
                manualAction === 'closed'
                    ? null
                    : { ...first, versionUuid: 'regular-version' },
            );
            rerender({ currentThread: updatedThread('version-2') });
            dispatchMock.mockClear();
            rerender({ currentThread: updatedThread('version-3') });
            expect(dispatchMock).not.toHaveBeenCalledWith(
                expect.objectContaining({ type: 'setPreview' }),
            );
        },
    );
});
