import { expect } from 'vitest';
import { ApiClient, type Body } from './api-client';

const mcpHeaders = { Accept: 'application/json, text/event-stream' };

export type McpResult = {
    isError?: boolean;
    content: Array<{ type: string; text?: string }>;
};
export type McpResponse<T> = { jsonrpc: string; id: number; result: T };

export function parseMcpResponse<T>(
    body: McpResponse<T> | string,
): McpResponse<T> {
    if (typeof body !== 'string') return body;
    const data = body
        .split('\n')
        .filter((line) => line.startsWith('data:'))
        .at(-1);
    if (!data) throw new Error('MCP response contains no SSE data');
    try {
        return JSON.parse(data.slice(5).trim()) as McpResponse<T>;
    } catch {
        throw new Error('MCP response contains invalid SSE JSON');
    }
}

export const mcpText = (result: McpResult) =>
    result.content
        .filter((content) => content.type === 'text')
        .map((content) => content.text ?? '')
        .join('\n');

export const personalAccessTokens: { client: ApiClient; uuid: string }[] = [];

export async function createPersonalAccessToken(
    client: ApiClient,
): Promise<string> {
    const response = await client.post<Body<{ uuid: string; token: string }>>(
        '/api/v1/user/me/personal-access-tokens',
        {
            description: 'mcp-api-test',
            expiresAt: null,
            autoGenerated: false,
        },
    );
    expect(response.status).toBe(200);
    personalAccessTokens.push({ client, uuid: response.body.results.uuid });
    return response.body.results.token;
}

export async function openMcpSession(client: ApiClient, projectUuid: string) {
    const token = await createPersonalAccessToken(client);
    const authHeaders = { ...mcpHeaders, Authorization: `ApiKey ${token}` };
    const mcp = new ApiClient();
    const response = await mcp.post<McpResponse<unknown> | string>(
        '/api/v1/mcp',
        {
            jsonrpc: '2.0',
            id: 1,
            method: 'initialize',
            params: {
                protocolVersion: '2025-03-26',
                capabilities: {},
                clientInfo: { name: 'mcp-api-test', version: '1.0.0' },
            },
        },
        { headers: authHeaders },
    );
    expect(response.status).toBe(200);
    expect(parseMcpResponse(response.body).result).toHaveProperty(
        'protocolVersion',
    );
    const sessionId = response.headers.get('mcp-session-id');
    expect(sessionId).toBeTruthy();
    const headers = { ...authHeaders, 'Mcp-Session-Id': sessionId! };
    let requestId = 1;
    const callTool = async (name: string, args: Record<string, unknown>) => {
        requestId += 1;
        const called = await mcp.post<McpResponse<McpResult> | string>(
            '/api/v1/mcp',
            {
                jsonrpc: '2.0',
                id: requestId,
                method: 'tools/call',
                params: { name, arguments: args },
            },
            { headers },
        );
        expect(called.status).toBe(200);
        const parsed = parseMcpResponse(called.body);
        expect(parsed.id).toBe(requestId);
        return parsed.result;
    };
    const readResource = async (uri: string) => {
        requestId += 1;
        const resourceResponse = await mcp.post<
            | McpResponse<{
                  contents: Array<{
                      uri: string;
                      mimeType: string;
                      text: string;
                  }>;
              }>
            | string
        >(
            '/api/v1/mcp',
            {
                jsonrpc: '2.0',
                id: requestId,
                method: 'resources/read',
                params: { uri },
            },
            { headers },
        );
        expect(resourceResponse.status).toBe(200);
        const parsed = parseMcpResponse(resourceResponse.body);
        expect(parsed.id).toBe(requestId);
        return parsed.result;
    };
    const selected = await callTool('set_project', { projectUuid });
    if (selected.isError) throw new Error(mcpText(selected));
    return Object.assign(callTool, { readResource });
}
