import { execFileSync } from 'node:child_process';
import { readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import * as peg from 'pegjs';
import { filterExpressionGrammar } from '../src/ee/AiAgent/schemas/filterExpressions/grammar';

const PACKAGE_DIR = path.resolve(__dirname, '..');
const OUTPUT_PATH = path.resolve(
    PACKAGE_DIR,
    'src/ee/AiAgent/schemas/filterExpressions/parser.ts',
);

const PARITY_CORPUS = [
    'orders_status equals=completed',
    'orders_status equals=open AND orders_region equals=emea',
    'orders_status equals=open or orders_region equals=emea',
    "orders_status include=1,2,'3,4,5'",
    'orders_revenue greaterThanOrEqual=100.5',
    'orders_created_date inThePast=30,days,false',
    'orders_customer_id isNull',
    'orders_customer_id equals=null',
    '`and` equals=value',
    'android_version equals=value',
    "field equals='a,b',\"line\\nvalue\",''",
    'field equals=café,日本語,🎉emoji',
    'field equals=value AND\nother equals=value',
    '',
    ' ',
    'and equals=value',
    'field equals=',
    'field equals=value,',
    'field equals=value trailing',
    'field isNull=true',
    'field equals=(value)',
    String.raw`field equals='bad\q'`,
    'a equals=1 AND b equals=2 OR c equals=3',
    'field include=value, AND other equals=value',
    'field equals="unbalanced',
    'f'.repeat(500),
];

const HEADER = `/* eslint-disable */
// @ts-nocheck
/**
 * AUTO-GENERATED by scripts/generateFilterExpressionParser.ts — DO NOT EDIT.
 *
 * Precompiled, eval-free parser for AI/MCP filter expressions. Regenerate with
 * \`pnpm -F common generate:filter-expression-parser\` after editing grammar.ts.
 */
`;

const bareParser = peg.generate(filterExpressionGrammar, {
    output: 'source',
    format: 'bare',
});

const content = `${HEADER}export const filterExpressionParser: {
    parse: (input: string) => unknown;
} = ${bareParser};
`;

const fail = (message: string): never => {
    console.error(
        `${message}\nRun: pnpm -F common generate:filter-expression-parser`,
    );
    return process.exit(1);
};

const formatLikeCommitted = (source: string): string => {
    const temporaryPath = path.join(
        tmpdir(),
        `filterExpression.parser.regen.${process.pid}.tmp.ts`,
    );
    try {
        writeFileSync(temporaryPath, source);
        execFileSync('pnpm', ['exec', 'oxfmt', '--write', temporaryPath], {
            cwd: PACKAGE_DIR,
            stdio: 'ignore',
        });
        return readFileSync(temporaryPath, 'utf8');
    } finally {
        try {
            rmSync(temporaryPath);
        } catch {
            // Best-effort temporary-file cleanup.
        }
    }
};

async function check(): Promise<void> {
    let committedSource: string;
    try {
        committedSource = readFileSync(OUTPUT_PATH, 'utf8');
    } catch {
        return fail('filterExpressions/parser.ts is missing.');
    }

    if (formatLikeCommitted(content) !== committedSource) {
        return fail(
            'filterExpressions/parser.ts is out of sync with grammar.ts.',
        );
    }

    const reference = peg.generate(filterExpressionGrammar);
    const { filterExpressionParser: committed } =
        await import('../src/ee/AiAgent/schemas/filterExpressions/parser');
    const outcome = (
        parser: { parse: (input: string) => unknown },
        input: string,
    ): string => {
        try {
            return `ok:${JSON.stringify(parser.parse(input))}`;
        } catch {
            return 'error';
        }
    };
    const drifted = PARITY_CORPUS.filter(
        (input) => outcome(reference, input) !== outcome(committed, input),
    );
    if (drifted.length > 0) {
        return fail(
            `filterExpressions/parser.ts behavior differs from grammar.ts.\nDiverging inputs: ${JSON.stringify(
                drifted,
            )}`,
        );
    }

    console.log(
        'filterExpressions/parser.ts is in sync with grammar.ts (source + behavior).',
    );
}

if (process.argv.includes('--check')) {
    void check();
} else {
    writeFileSync(OUTPUT_PATH, content);
    console.log(`Wrote ${OUTPUT_PATH}`);
}
