/**
 * Precompiles the PEG.js filter grammar into a standalone, eval-free parser.
 *
 * PEG.js's `peg.generate(grammarString)` compiles the grammar at runtime using
 * `eval()`, which violates strict Content-Security-Policy (`script-src` without
 * `unsafe-eval`) in the browser SDK bundle. The generated parser itself is plain
 * recursive-descent JavaScript with no `eval`/`new Function`, so we generate it
 * at build time and commit the result.
 *
 *   pnpm -F common generate:filter-grammar-parser        # regenerate
 *   pnpm -F common check:filter-grammar-parser           # CI: verify in sync
 *
 * Run this after editing `filterGrammar.grammar.ts`.
 */
import { writeFileSync } from 'fs';
import path from 'path';
import * as peg from 'pegjs';
import filterGrammar from '../src/types/filterGrammar.grammar';

const OUTPUT_PATH = path.resolve(
    __dirname,
    '../src/types/filterGrammar.parser.ts',
);

// Representative inputs covering every grammar branch. The committed parser must
// produce identical output to a freshly-compiled reference parser for each.
const PARITY_CORPUS = [
    '',
    'pedram',
    'with space',
    'with_multiple_underscores',
    '!pedram',
    '>= 5',
    '<= 10',
    '> 3',
    '< 7.5',
    'between 1 and 10',
    'between "2020-01-01" and "2020-12-31"',
    'inThePast 7 days',
    'inTheNext 3 months',
    '%contains%',
    'starts%',
    '%ends',
    'EMPTY',
    'empty',
    'NULL',
    'null',
    'a,b,c',
    '"quoted, value"',
    '-excluded',
    '2020-01-01',
];

const HEADER = `/* eslint-disable */
// @ts-nocheck
/**
 * AUTO-GENERATED by scripts/generateFilterGrammarParser.ts — DO NOT EDIT.
 *
 * Precompiled, eval-free parser for the metric filter grammar. Regenerate with
 * \`pnpm -F common generate:filter-grammar-parser\` after editing
 * filterGrammar.grammar.ts.
 */
`;

const bareParser = peg.generate(filterGrammar, {
    output: 'source',
    format: 'bare',
} as peg.OutputFormatBare);

const content = `${HEADER}export const filterGrammarParser: {
    parse: (input: string) => any;
} = ${bareParser};
`;

async function check(): Promise<void> {
    // Behavioural parity: compare the committed precompiled parser against a
    // reference parser compiled from the current grammar. This is immune to
    // formatting (oxfmt/prettier) and directly verifies what we care about —
    // that the committed parser still matches the grammar.
    const reference = peg.generate(filterGrammar);
    let committed: { parse: (input: string) => unknown };
    try {
        ({ filterGrammarParser: committed } = await import(
            '../src/types/filterGrammar.parser'
        ));
    } catch {
        // eslint-disable-next-line no-console
        console.error(
            'filterGrammar.parser.ts is missing — run: pnpm -F common generate:filter-grammar-parser',
        );
        process.exit(1);
    }
    const drifted = PARITY_CORPUS.filter((input) => {
        const a = JSON.stringify(reference.parse(input));
        const b = JSON.stringify(committed.parse(input));
        return a !== b;
    });
    if (drifted.length > 0) {
        // eslint-disable-next-line no-console
        console.error(
            'filterGrammar.parser.ts is out of sync with filterGrammar.grammar.ts.\n' +
                `Diverging inputs: ${JSON.stringify(drifted)}\n` +
                'Run: pnpm -F common generate:filter-grammar-parser',
        );
        process.exit(1);
    }
    // eslint-disable-next-line no-console
    console.log('filterGrammar.parser.ts is in sync with the grammar.');
}

if (process.argv.includes('--check')) {
    void check();
} else {
    writeFileSync(OUTPUT_PATH, content);
    // eslint-disable-next-line no-console
    console.log(`Wrote ${OUTPUT_PATH}`);
}
