/**
 * Precompiles the PEG.js filter grammar into a standalone, eval-free parser.
 *
 * PEG.js's `peg.generate(grammarString)` compiles the grammar at runtime using
 * `eval()`, which violates strict Content-Security-Policy (`script-src` without
 * `unsafe-eval`) in the browser SDK bundle. The generated parser itself is plain
 * recursive-descent JavaScript with no `eval`/`new Function`, so we generate it
 * at build time and commit the result.
 *
 *   pnpm -F common generate:filter-grammar-parser        # regenerate
 *   pnpm -F common check:filter-grammar-parser           # CI: verify in sync
 *
 * Run this after editing `filterGrammar.grammar.ts`.
 */
import { execFileSync } from 'child_process';
import { readFileSync, rmSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import path from 'path';
import * as peg from 'pegjs';
import filterGrammar from '../src/types/filterGrammar.grammar';

const PACKAGE_DIR = path.resolve(__dirname, '..');
const OUTPUT_PATH = path.resolve(
    PACKAGE_DIR,
    'src/types/filterGrammar.parser.ts',
);

// Inputs covering every grammar branch plus the awkward edges (escapes,
// unicode, malformed strings, numeric formats, very long inputs). The committed
// parser must produce identical output — value or thrown error — to a freshly
// compiled reference parser for each, so any grammar/parser drift is caught.
const PARITY_CORPUS = [
    // empty / whitespace
    '',
    ' ',
    '  ',
    // plain terms
    'pedram',
    'ABC',
    'with space',
    'with  double  space',
    'with_multiple_underscores',
    'with-dash',
    // numbers (numeric coercion + scientific notation)
    '123',
    '0',
    '-5',
    '1.5',
    '-1.5e-2',
    '3.',
    '.5',
    '1e3',
    '1E3',
    // operators
    '>= 5',
    '<= 10',
    '> 3',
    '< 7.5',
    '>=5',
    '<=10',
    '>3.5',
    '< -2',
    // between (numeric + date, both cases)
    'between 1 and 10',
    'BETWEEN 1 AND 10',
    'between -5 and 5',
    'between "2020-01-01" and "2020-12-31"',
    'between 2020-01-01 and 2020-12-31',
    // dates (valid + boundary-invalid)
    '2020-01-01',
    '"2020-12-31"',
    '2020-01-01T12:30:00Z',
    '2020-13-01',
    '2020-00-01',
    // relative dates
    'inThePast 7 days',
    'inTheNext 3 months',
    'inThePast 1 year',
    'inTheNext 12 weeks',
    // lists
    'a,b,c',
    'a, b, c',
    '!a,!b,!c',
    'a,b,',
    // wildcards
    '%contains%',
    'starts%',
    '%ends',
    '%x%y%',
    '%%',
    'pre%post',
    '%a_b%',
    // keywords + negation
    'EMPTY',
    'empty',
    'NULL',
    'null',
    '!EMPTY',
    '!NULL',
    '!pedram',
    '!%x%',
    '!123',
    '! abc',
    // caret escapes
    'a^_b',
    'a^,b',
    'a^%b',
    'caret^^end',
    'trailing ^ ',
    // quoted strings
    '"quoted value"',
    '"quoted, value"',
    '""',
    '"a\\\\"b"',
    // unicode
    'café',
    '日本語',
    '🎉emoji',
    'mixedCafé123',
    // stress / malformed (both parsers should error consistently)
    'a'.repeat(500),
    '%'.repeat(50),
    '"unbalanced',
    'unbalanced"',
    '><',
    '>=<=',
    '!!',
    ',,,',
    'between 1 and',
    'between and 10',
    '>= ',
    'inThePast days',
    'inThePast 7',
];

const HEADER = `/* eslint-disable */
// @ts-nocheck
/**
 * AUTO-GENERATED by scripts/generateFilterGrammarParser.ts — DO NOT EDIT.
 *
 * Precompiled, eval-free parser for the metric filter grammar. Regenerate with
 * \`pnpm -F common generate:filter-grammar-parser\` after editing
 * filterGrammar.grammar.ts.
 */
`;

const bareParser = peg.generate(filterGrammar, {
    output: 'source',
    format: 'bare',
} as peg.OutputFormatBare);

const content = `${HEADER}export const filterGrammarParser: {
    parse: (input: string) => any;
} = ${bareParser};
`;

const fail = (message: string): never => {
    // eslint-disable-next-line no-console
    console.error(
        `${message}\nRun: pnpm -F common generate:filter-grammar-parser`,
    );
    return process.exit(1);
};

// Format an arbitrary source string exactly as the committed file is formatted,
// by running it through oxfmt. The throwaway file lives in the OS temp dir —
// NOT under src/ — so it never collides with the lint/format/typecheck quality
// checks that scan src/ in parallel in CI. oxfmt resolves the repo config the
// same way, so the output matches the committed file byte-for-byte.
const formatLikeCommitted = (source: string): string => {
    const tmp = path.join(
        tmpdir(),
        `filterGrammar.parser.regen.${process.pid}.tmp.ts`,
    );
    try {
        writeFileSync(tmp, source);
        execFileSync('pnpm', ['exec', 'oxfmt', '--write', tmp], {
            cwd: PACKAGE_DIR,
            stdio: 'ignore',
        });
        return readFileSync(tmp, 'utf-8');
    } finally {
        try {
            rmSync(tmp);
        } catch {
            // best-effort cleanup
        }
    }
};

async function check(): Promise<void> {
    // 1. SOURCE drift (primary): regenerate the parser from the current grammar,
    //    format it identically, and compare byte-for-byte to the committed file.
    //    This catches ANY grammar change — including new operators/intervals that
    //    no behavioural corpus input happens to exercise.
    let committedSource: string;
    try {
        committedSource = readFileSync(OUTPUT_PATH, 'utf-8');
    } catch {
        return fail('filterGrammar.parser.ts is missing.');
    }
    if (formatLikeCommitted(content) !== committedSource) {
        return fail(
            'filterGrammar.parser.ts is out of sync with filterGrammar.grammar.ts (regenerated parser source differs).',
        );
    }

    // 2. BEHAVIOURAL parity (secondary): also confirm the committed parser
    //    actually behaves like a fresh reference parser over the corpus — a
    //    cheap guard against a pathological generation/build issue.
    const reference = peg.generate(filterGrammar);
    const { filterGrammarParser: committed } = (await import(
        '../src/types/filterGrammar.parser'
    )) as { filterGrammarParser: { parse: (input: string) => unknown } };
    const outcome = (
        parser: { parse: (input: string) => unknown },
        input: string,
    ) => {
        try {
            return `ok:${JSON.stringify(parser.parse(input))}`;
        } catch {
            return 'error';
        }
    };
    const drifted = PARITY_CORPUS.filter(
        (input) => outcome(reference, input) !== outcome(committed, input),
    );
    if (drifted.length > 0) {
        return fail(
            `filterGrammar.parser.ts behaviour differs from the grammar.\nDiverging inputs: ${JSON.stringify(
                drifted,
            )}`,
        );
    }

    // eslint-disable-next-line no-console
    console.log('filterGrammar.parser.ts is in sync with the grammar (source + behaviour).');
}

if (process.argv.includes('--check')) {
    void check();
} else {
    writeFileSync(OUTPUT_PATH, content);
    // eslint-disable-next-line no-console
    console.log(`Wrote ${OUTPUT_PATH}`);
}
