import { isChartTypeIcon, type ChartTypeIcon } from '@lightdash/common';
import {
    IconActivity,
    IconArrowsSplit,
    IconBinaryTree,
    IconCalendar,
    IconChartArcs,
    IconChartArea,
    IconChartAreaLine,
    IconChartArrows,
    IconChartArrowsVertical,
    IconChartBar,
    IconChartBubble,
    IconChartCandle,
    IconChartCircles,
    IconChartDonut,
    IconChartDonut2,
    IconChartDots,
    IconChartDots2,
    IconChartGridDots,
    IconChartHistogram,
    IconChartInfographic,
    IconChartLine,
    IconChartPie,
    IconChartPie2,
    IconChartRadar,
    IconChartSankey,
    IconChartScatter3d,
    IconChartTreemap,
    IconClock,
    IconFilter,
    IconGauge,
    IconGitBranch,
    IconGitMerge,
    IconGridDots,
    IconHierarchy,
    IconHierarchy2,
    IconLayoutGrid,
    IconLayoutKanban,
    IconList,
    IconMap,
    IconNetwork,
    IconNumber,
    IconPercentage,
    IconPuzzle,
    IconSitemap,
    IconSquareNumber1,
    IconStack,
    IconTable,
    IconTarget,
    IconTimeline,
    IconTopologyStar,
    IconTrendingDown,
    IconTrendingUp,
    IconWaveSine,
    IconWorld,
    type Icon as TablerIcon,
} from '@tabler/icons-react';

/** Every curated chart type icon, statically imported so the bundle only
 *  carries these components rather than the whole Tabler set. */
const CHART_TYPE_ICON_COMPONENTS: Record<ChartTypeIcon, TablerIcon> = {
    'chart-bar': IconChartBar,
    'chart-histogram': IconChartHistogram,
    'chart-line': IconChartLine,
    'chart-area': IconChartArea,
    'chart-area-line': IconChartAreaLine,
    'chart-arrows': IconChartArrows,
    'chart-arrows-vertical': IconChartArrowsVertical,
    'chart-candle': IconChartCandle,
    'chart-infographic': IconChartInfographic,
    'chart-dots': IconChartDots,
    'chart-dots-2': IconChartDots2,
    'chart-bubble': IconChartBubble,
    'chart-scatter-3d': IconChartScatter3d,
    'chart-grid-dots': IconChartGridDots,
    'chart-pie': IconChartPie,
    'chart-pie-2': IconChartPie2,
    'chart-donut': IconChartDonut,
    'chart-donut-2': IconChartDonut2,
    'chart-arcs': IconChartArcs,
    'chart-circles': IconChartCircles,
    'chart-radar': IconChartRadar,
    'chart-treemap': IconChartTreemap,
    'chart-sankey': IconChartSankey,
    hierarchy: IconHierarchy,
    'hierarchy-2': IconHierarchy2,
    'binary-tree': IconBinaryTree,
    sitemap: IconSitemap,
    'topology-star': IconTopologyStar,
    network: IconNetwork,
    'git-branch': IconGitBranch,
    'git-merge': IconGitMerge,
    'arrows-split': IconArrowsSplit,
    map: IconMap,
    world: IconWorld,
    timeline: IconTimeline,
    calendar: IconCalendar,
    clock: IconClock,
    table: IconTable,
    'layout-grid': IconLayoutGrid,
    'layout-kanban': IconLayoutKanban,
    list: IconList,
    'grid-dots': IconGridDots,
    number: IconNumber,
    'square-number-1': IconSquareNumber1,
    percentage: IconPercentage,
    'trending-up': IconTrendingUp,
    'trending-down': IconTrendingDown,
    gauge: IconGauge,
    target: IconTarget,
    activity: IconActivity,
    'wave-sine': IconWaveSine,
    filter: IconFilter,
    stack: IconStack,
    puzzle: IconPuzzle,
};

/** The component for a chosen chart type icon; the puzzle piece for null
 *  (no icon chosen) or an unrecognised name, matching the rest of the app's
 *  fallback. */
export const getChartTypeIcon = (icon: ChartTypeIcon | null): TablerIcon =>
    (icon && CHART_TYPE_ICON_COMPONENTS[icon]) || IconPuzzle;

/** Human label for an icon name: drops a leading "chart-", turns hyphens
 *  into spaces, and capitalises the first letter. */
export const getChartTypeIconLabel = (icon: ChartTypeIcon): string => {
    // Drop the "chart-" prefix unless that would collide with another icon.
    const stripped = icon.startsWith('chart-') ? icon.slice(6) : icon;
    const base =
        isChartTypeIcon(stripped) && stripped !== icon ? icon : stripped;
    const label = base.replace(/-/g, ' ');
    return label.charAt(0).toUpperCase() + label.slice(1);
};
