#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/runGitSecrets.sh"

# Check if profiles.yml has been modified
if git diff --cached --name-only | grep -q "examples/full-jaffle-shop-demo/profiles/profiles.yml"; then
  echo "Error: Modifications to profiles.yml are not allowed"
  exit 1
fi

npx lint-staged
pnpm -F frontend unused-exports
