version: 2
models:
  - name: stg_customers
    meta: 
      group_label: "staging"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
        description: ""
      - name: first_name
        description: ""
      - name: last_name
        description: ""
      - name: created
        description: ""
  - name: stg_orders
    meta: 
      group_label: "staging"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: ""
      - name: status
        tests:
          - accepted_values:
              values:
                - placed
                - shipped
                - completed
                - return_pending
                - returned
        description: ""
      - name: customer_id
        description: ""
      - name: order_date
        description: ""
  - name: stg_payments
    meta: 
      group_label: "staging"
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
        description: ""
      - name: payment_method
        tests:
          - accepted_values:
              values:
                - credit_card
                - coupon
                - bank_transfer
                - gift_card
        description: ""
      - name: order_id
        description: ""
      - name: amount
        description: ""
