with source as (

    {#-
    Normally we would select from the table here, but we are using seeds to load
    our data in this project
    #}
    select * from {{ ref('raw_parts') }}

),

renamed as (

    select
        part_id,
        part_number,
        part_name,
        part_category,
        part_subcategory,
        manufacturer,
        manufacturer_part_number,
        supplier,
        supplier_part_number,
        part_description,
        unit_of_measure,
        unit_cost::numeric as unit_cost,
        retail_price::numeric as retail_price,
        markup_percent::numeric as markup_percent,
        stock_quantity::integer as stock_quantity,
        reorder_point::integer as reorder_point,
        reorder_quantity::integer as reorder_quantity,
        max_stock_level::integer as max_stock_level,
        min_stock_level::integer as min_stock_level,
        stock_status,
        warehouse_location,
        bin_location,
        last_restock_date::date as last_restock_date,
        next_restock_date::date as next_restock_date,
        lead_time_days::integer as lead_time_days,
        quantity_on_order::integer as quantity_on_order,
        supplier_order_number,
        expected_delivery_date::date as expected_delivery_date,
        total_quantity_used_ytd::integer as total_quantity_used_ytd,
        total_quantity_used_last_month::integer as total_quantity_used_last_month,
        average_monthly_usage::numeric as average_monthly_usage,
        usage_trend,
        stockout_incidents_ytd::integer as stockout_incidents_ytd,
        last_stockout_date::date as last_stockout_date,
        compatible_equipment_types,
        critical_part::boolean as critical_part,
        seasonal_demand::boolean as seasonal_demand,
        weight_lbs::numeric as weight_lbs,
        dimensions_inches,
        hazmat::boolean as hazmat,
        hazmat_class,
        shelf_life_months::integer as shelf_life_months,
        temperature_controlled::boolean as temperature_controlled,
        warranty_months::integer as warranty_months,
        returnable::boolean as returnable,
        part_condition,
        quality_grade,
        inspection_required::boolean as inspection_required,
        last_inspection_date::date as last_inspection_date,
        certification_required::boolean as certification_required,
        certifications,
        eco_friendly::boolean as eco_friendly,
        recycled_content_percent::integer as recycled_content_percent,
        energy_star_rated::boolean as energy_star_rated,
        country_of_origin,
        tariff_code,
        import_duty_percent::numeric as import_duty_percent,
        substitute_part_ids,
        superseded_by_part_id::integer as superseded_by_part_id,
        obsolete::boolean as obsolete,
        discontinuation_date,
        total_value_in_stock::numeric as total_value_in_stock,
        inventory_turnover_ratio::numeric as inventory_turnover_ratio,
        days_in_inventory::integer as days_in_inventory,
        carrying_cost_annual::numeric as carrying_cost_annual,
        storage_cost_monthly::numeric as storage_cost_monthly,
        insurance_value::numeric as insurance_value,
        shrinkage_rate_percent::numeric as shrinkage_rate_percent,
        damage_rate_percent::numeric as damage_rate_percent,
        work_orders_used_count::integer as work_orders_used_count,
        average_install_time_minutes::integer as average_install_time_minutes,
        skill_level_required,
        tools_required,
        installation_notes,
        maintenance_interval_months::integer as maintenance_interval_months,
        failure_rate_percent::numeric as failure_rate_percent,
        mtbf_hours::integer as mtbf_hours,
        warranty_claims_ytd::integer as warranty_claims_ytd,
        return_rate_percent::numeric as return_rate_percent,
        customer_rating::numeric as customer_rating,
        total_ratings::integer as total_ratings,
        supplier_rating::numeric as supplier_rating,
        supplier_lead_time_reliability::numeric as supplier_lead_time_reliability,
        price_trend_3month,
        price_volatility,
        contract_pricing::boolean as contract_pricing,
        volume_discount_available::boolean as volume_discount_available,
        bulk_order_minimum::integer as bulk_order_minimum,
        image_url,
        datasheet_url,
        video_tutorial_url,
        last_price_update::date as last_price_update,
        next_price_review::date as next_price_review,
        created_date::date as created_date,
        updated_date::date as updated_date,
        created_by,
        updated_by,
        notes

    from source

)

select * from renamed

