with source as (

    {#-
    Normally we would select from the table here, but we are using seeds to load
    our data in this project
    #}
    select * from {{ ref('raw_buildings') }}

),

renamed as (

    select
        building_id,
        property_code,
        building_name,
        building_type,
        primary_use,
        secondary_use,
        address_street,
        address_city,
        address_state,
        address_zip,
        country,
        region,
        territory,
        {{ cast_numeric('latitude') }} as latitude,
        {{ cast_numeric('longitude') }} as longitude,
        {{ cast_date('acquisition_date') }} as acquisition_date,
        {{ cast_integer('construction_year') }} as construction_year,
        {{ cast_integer('last_renovation_year') }} as last_renovation_year,
        {{ cast_integer('building_age_years') }} as building_age_years,
        {{ cast_integer('total_square_feet') }} as total_square_feet,
        {{ cast_integer('rentable_square_feet') }} as rentable_square_feet,
        {{ cast_integer('usable_square_feet') }} as usable_square_feet,
        {{ cast_integer('common_area_square_feet') }} as common_area_square_feet,
        {{ cast_integer('number_of_floors') }} as number_of_floors,
        {{ cast_integer('basement_levels') }} as basement_levels,
        roof_type,
        {{ cast_integer('roof_age_years') }} as roof_age_years,
        foundation_type,
        exterior_material,
        {{ cast_integer('parking_spaces') }} as parking_spaces,
        parking_type,
        {{ cast_numeric('parking_revenue_monthly') }} as parking_revenue_monthly,
        building_status,
        occupancy_status,
        {{ cast_numeric('occupancy_rate') }} as occupancy_rate,
        {{ cast_integer('total_units') }} as total_units,
        {{ cast_integer('occupied_units') }} as occupied_units,
        {{ cast_integer('vacant_units') }} as vacant_units,
        {{ cast_integer('number_of_tenants') }} as number_of_tenants,
        {{ cast_integer('largest_tenant_sqft') }} as largest_tenant_sqft,
        anchor_tenant_name,
        {{ cast_date('lease_expiry_soonest') }} as lease_expiry_soonest,
        property_manager_id,
        facility_manager_id,
        {{ cast_numeric('building_value') }} as building_value,
        {{ cast_numeric('assessed_value') }} as assessed_value,
        {{ cast_numeric('property_tax_annual') }} as property_tax_annual,
        {{ cast_numeric('insurance_premium_annual') }} as insurance_premium_annual,
        {{ cast_numeric('utility_cost_monthly') }} as utility_cost_monthly,
        {{ cast_numeric('maintenance_cost_monthly') }} as maintenance_cost_monthly,
        {{ cast_numeric('janitorial_cost_monthly') }} as janitorial_cost_monthly,
        {{ cast_numeric('security_cost_monthly') }} as security_cost_monthly,
        {{ cast_numeric('landscaping_cost_monthly') }} as landscaping_cost_monthly,
        {{ cast_numeric('total_operating_cost_monthly') }} as total_operating_cost_monthly,
        {{ cast_numeric('revenue_monthly') }} as revenue_monthly,
        {{ cast_numeric('net_operating_income_monthly') }} as net_operating_income_monthly,
        {{ cast_numeric('cap_rate') }} as cap_rate,
        {{ cast_integer('energy_star_score') }} as energy_star_score,
        leed_certification,
        {{ cast_integer('walkability_score') }} as walkability_score,
        {{ cast_integer('transit_score') }} as transit_score,
        {{ cast_integer('bike_score') }} as bike_score,
        flood_zone,
        seismic_zone,
        hvac_system_type,
        {{ cast_integer('hvac_system_age') }} as hvac_system_age,
        {{ cast_integer('hvac_capacity_tons') }} as hvac_capacity_tons,
        heating_system_type,
        cooling_system_type,
        ventilation_type,
        {{ cast_integer('electrical_capacity_amps') }} as electrical_capacity_amps,
        {{ cast_boolean('backup_generator') }} as backup_generator,
        {{ cast_integer('generator_capacity_kw') }} as generator_capacity_kw,
        {{ cast_integer('elevator_count') }} as elevator_count,
        {{ cast_date('elevator_last_inspection') }} as elevator_last_inspection,
        fire_suppression_type,
        fire_alarm_type,
        sprinkler_coverage,
        {{ cast_boolean('ada_compliant') }} as ada_compliant,
        security_system_type,
        access_control_system,
        {{ cast_integer('cctv_camera_count') }} as cctv_camera_count,
        parking_access_system,
        internet_provider,
        {{ cast_integer('bandwidth_mbps') }} as bandwidth_mbps,
        cell_coverage_quality,
        water_source,
        sewer_system,
        gas_service,
        {{ cast_integer('average_water_usage_gallons') }} as average_water_usage_gallons,
        {{ cast_integer('average_electricity_kwh') }} as average_electricity_kwh,
        {{ cast_integer('average_gas_therms') }} as average_gas_therms,
        sustainability_rating,
        {{ cast_boolean('solar_panels') }} as solar_panels,
        {{ cast_integer('solar_capacity_kw') }} as solar_capacity_kw,
        {{ cast_integer('ev_charging_stations') }} as ev_charging_stations,
        {{ cast_integer('bike_storage_capacity') }} as bike_storage_capacity,
        {{ cast_boolean('recycling_program') }} as recycling_program,
        {{ cast_boolean('composting_program') }} as composting_program,
        {{ cast_boolean('green_roof') }} as green_roof,
        {{ cast_boolean('rainwater_harvesting') }} as rainwater_harvesting,
        {{ cast_date('last_inspection_date') }} as last_inspection_date,
        {{ cast_date('last_safety_audit') }} as last_safety_audit,
        {{ cast_date('next_inspection_due') }} as next_inspection_due,
        {{ cast_integer('building_code_violations') }} as building_code_violations,
        {{ cast_integer('code_violations_resolved') }} as code_violations_resolved,
        {{ cast_integer('insurance_claims_5yr') }} as insurance_claims_5yr,
        {{ cast_integer('total_work_orders_ytd') }} as total_work_orders_ytd,
        {{ cast_integer('open_work_orders') }} as open_work_orders,
        {{ cast_numeric('average_work_order_cost') }} as average_work_order_cost,
        {{ cast_numeric('preventive_maintenance_compliance') }} as preventive_maintenance_compliance,
        {{ cast_numeric('tenant_satisfaction_score') }} as tenant_satisfaction_score,
        building_management_system,
        smart_building_features,
        amenities

    from source

)

select * from renamed
