with source as (

    {#-
    Normally we would select from the table here, but we are using seeds to load
    our data in this project
    #}
    select * from {{ ref('raw_buildings') }}

),

renamed as (

    select
        building_id,
        property_code,
        building_name,
        building_type,
        primary_use,
        secondary_use,
        address_street,
        address_city,
        address_state,
        address_zip,
        country,
        region,
        territory,
        latitude::numeric as latitude,
        longitude::numeric as longitude,
        acquisition_date::date as acquisition_date,
        construction_year::integer as construction_year,
        last_renovation_year::integer as last_renovation_year,
        building_age_years::integer as building_age_years,
        total_square_feet::integer as total_square_feet,
        rentable_square_feet::integer as rentable_square_feet,
        usable_square_feet::integer as usable_square_feet,
        common_area_square_feet::integer as common_area_square_feet,
        number_of_floors::integer as number_of_floors,
        basement_levels::integer as basement_levels,
        roof_type,
        roof_age_years::integer as roof_age_years,
        foundation_type,
        exterior_material,
        parking_spaces::integer as parking_spaces,
        parking_type,
        parking_revenue_monthly::numeric as parking_revenue_monthly,
        building_status,
        occupancy_status,
        occupancy_rate::numeric as occupancy_rate,
        total_units::integer as total_units,
        occupied_units::integer as occupied_units,
        vacant_units::integer as vacant_units,
        number_of_tenants::integer as number_of_tenants,
        largest_tenant_sqft::integer as largest_tenant_sqft,
        anchor_tenant_name,
        lease_expiry_soonest::date as lease_expiry_soonest,
        property_manager_id,
        facility_manager_id,
        building_value::numeric as building_value,
        assessed_value::numeric as assessed_value,
        property_tax_annual::numeric as property_tax_annual,
        insurance_premium_annual::numeric as insurance_premium_annual,
        utility_cost_monthly::numeric as utility_cost_monthly,
        maintenance_cost_monthly::numeric as maintenance_cost_monthly,
        janitorial_cost_monthly::numeric as janitorial_cost_monthly,
        security_cost_monthly::numeric as security_cost_monthly,
        landscaping_cost_monthly::numeric as landscaping_cost_monthly,
        total_operating_cost_monthly::numeric as total_operating_cost_monthly,
        revenue_monthly::numeric as revenue_monthly,
        net_operating_income_monthly::numeric as net_operating_income_monthly,
        cap_rate::numeric as cap_rate,
        energy_star_score::integer as energy_star_score,
        leed_certification,
        walkability_score::integer as walkability_score,
        transit_score::integer as transit_score,
        bike_score::integer as bike_score,
        flood_zone,
        seismic_zone,
        hvac_system_type,
        hvac_system_age::integer as hvac_system_age,
        hvac_capacity_tons::integer as hvac_capacity_tons,
        heating_system_type,
        cooling_system_type,
        ventilation_type,
        electrical_capacity_amps::integer as electrical_capacity_amps,
        backup_generator::boolean as backup_generator,
        generator_capacity_kw::integer as generator_capacity_kw,
        elevator_count::integer as elevator_count,
        elevator_last_inspection::date as elevator_last_inspection,
        fire_suppression_type,
        fire_alarm_type,
        sprinkler_coverage,
        ada_compliant::boolean as ada_compliant,
        security_system_type,
        access_control_system,
        cctv_camera_count::integer as cctv_camera_count,
        parking_access_system,
        internet_provider,
        bandwidth_mbps::integer as bandwidth_mbps,
        cell_coverage_quality,
        water_source,
        sewer_system,
        gas_service,
        average_water_usage_gallons::integer as average_water_usage_gallons,
        average_electricity_kwh::integer as average_electricity_kwh,
        average_gas_therms::integer as average_gas_therms,
        sustainability_rating,
        solar_panels::boolean as solar_panels,
        solar_capacity_kw::integer as solar_capacity_kw,
        ev_charging_stations::integer as ev_charging_stations,
        bike_storage_capacity::integer as bike_storage_capacity,
        recycling_program::boolean as recycling_program,
        composting_program::boolean as composting_program,
        green_roof::boolean as green_roof,
        rainwater_harvesting::boolean as rainwater_harvesting,
        last_inspection_date::date as last_inspection_date,
        last_safety_audit::date as last_safety_audit,
        next_inspection_due::date as next_inspection_due,
        building_code_violations::integer as building_code_violations,
        code_violations_resolved::integer as code_violations_resolved,
        insurance_claims_5yr::integer as insurance_claims_5yr,
        total_work_orders_ytd::integer as total_work_orders_ytd,
        open_work_orders::integer as open_work_orders,
        average_work_order_cost::numeric as average_work_order_cost,
        preventive_maintenance_compliance::numeric as preventive_maintenance_compliance,
        tenant_satisfaction_score::numeric as tenant_satisfaction_score,
        building_management_system,
        smart_building_features,
        amenities

    from source

)

select * from renamed

