with source as (

    {#-
    Normally we would select from the table here, but we are using seeds to load
    our data in this project
    #}
    select * from {{ ref('raw_service_contracts') }}

),

renamed as (

    select
        contract_id,
        contract_number,
        {{ cast_integer('building_id') }} as building_id,
        {{ cast_integer('customer_id') }} as customer_id,
        contract_name,
        contract_type,
        service_level,
        coverage_scope,
        {{ cast_date('start_date') }} as start_date,
        {{ cast_date('end_date') }} as end_date,
        {{ cast_integer('contract_term_months') }} as contract_term_months,
        status,
        payment_terms,
        payment_frequency,
        {{ cast_integer('billing_cycle_day') }} as billing_cycle_day,
        {{ cast_numeric('contract_value_total') }} as contract_value_total,
        {{ cast_numeric('monthly_recurring_revenue') }} as monthly_recurring_revenue,
        {{ cast_numeric('annual_contract_value') }} as annual_contract_value,
        payment_status,
        {{ cast_integer('invoice_count_ytd') }} as invoice_count_ytd,
        {{ cast_integer('paid_invoices_ytd') }} as paid_invoices_ytd,
        {{ cast_integer('overdue_invoices') }} as overdue_invoices,
        {{ cast_numeric('total_amount_invoiced_ytd') }} as total_amount_invoiced_ytd,
        {{ cast_numeric('total_amount_paid_ytd') }} as total_amount_paid_ytd,
        {{ cast_numeric('outstanding_balance') }} as outstanding_balance,
        {{ cast_date('last_payment_date') }} as last_payment_date,
        {{ cast_numeric('last_payment_amount') }} as last_payment_amount,
        {{ cast_date('next_invoice_date') }} as next_invoice_date,
        {{ cast_boolean('auto_renew') }} as auto_renew,
        {{ cast_integer('renewal_notice_days') }} as renewal_notice_days,
        {{ cast_numeric('price_escalation_percent') }} as price_escalation_percent,
        price_escalation_frequency,
        {{ cast_numeric('discount_percent') }} as discount_percent,
        discount_reason,
        sales_rep_id,
        account_manager_id,
        {{ cast_date('signed_date') }} as signed_date,
        signed_by_customer,
        signed_by_vendor,
        contract_file_url,
        {{ cast_integer('response_time_sla_minutes') }} as response_time_sla_minutes,
        {{ cast_numeric('resolution_time_sla_hours') }} as resolution_time_sla_hours,
        {{ cast_numeric('first_time_fix_sla_percent') }} as first_time_fix_sla_percent,
        {{ cast_numeric('customer_satisfaction_sla') }} as customer_satisfaction_sla,
        {{ cast_numeric('availability_sla_percent') }} as availability_sla_percent,
        {{ cast_numeric('uptime_guarantee_percent') }} as uptime_guarantee_percent,
        {{ cast_boolean('penalty_clause') }} as penalty_clause,
        {{ cast_numeric('penalty_amount_per_incident') }} as penalty_amount_per_incident,
        {{ cast_numeric('max_penalty_percent') }} as max_penalty_percent,
        {{ cast_boolean('emergency_response_included') }} as emergency_response_included,
        {{ cast_boolean('after_hours_included') }} as after_hours_included,
        {{ cast_boolean('weekend_coverage_included') }} as weekend_coverage_included,
        {{ cast_boolean('holiday_coverage_included') }} as holiday_coverage_included,
        {{ cast_boolean('parts_included') }} as parts_included,
        {{ cast_boolean('labor_included') }} as labor_included,
        {{ cast_boolean('travel_included') }} as travel_included,
        {{ cast_boolean('prevantive_maintenance_included') }} as prevantive_maintenance_included,
        {{ cast_integer('pm_frequency_months') }} as pm_frequency_months,
        {{ cast_integer('pm_visits_per_year') }} as pm_visits_per_year,
        {{ cast_integer('equipment_covered_count') }} as equipment_covered_count,
        equipment_types_covered,
        {{ cast_integer('buildings_covered_count') }} as buildings_covered_count,
        {{ cast_integer('service_area_miles') }} as service_area_miles,
        {{ cast_boolean('priority_service') }} as priority_service,
        {{ cast_boolean('dedicated_technician') }} as dedicated_technician,
        escalation_contact_name,
        escalation_contact_phone,
        {{ cast_integer('total_work_orders_ytd') }} as total_work_orders_ytd,
        {{ cast_integer('completed_work_orders_ytd') }} as completed_work_orders_ytd,
        {{ cast_integer('open_work_orders') }} as open_work_orders,
        {{ cast_integer('cancelled_work_orders') }} as cancelled_work_orders,
        {{ cast_integer('emergency_calls_ytd') }} as emergency_calls_ytd,
        {{ cast_numeric('response_time_met_percent') }} as response_time_met_percent,
        {{ cast_numeric('resolution_time_met_percent') }} as resolution_time_met_percent,
        {{ cast_numeric('first_time_fix_rate') }} as first_time_fix_rate,
        {{ cast_numeric('customer_satisfaction_score') }} as customer_satisfaction_score,
        {{ cast_numeric('sla_compliance_score') }} as sla_compliance_score,
        {{ cast_integer('penalties_assessed_ytd') }} as penalties_assessed_ytd,
        {{ cast_numeric('penalty_amount_ytd') }} as penalty_amount_ytd,
        {{ cast_integer('warranty_claims_ytd') }} as warranty_claims_ytd,
        {{ cast_numeric('total_labor_hours_ytd') }} as total_labor_hours_ytd,
        {{ cast_numeric('total_parts_cost_ytd') }} as total_parts_cost_ytd,
        {{ cast_numeric('total_service_cost_ytd') }} as total_service_cost_ytd,
        {{ cast_numeric('profitability_percent') }} as profitability_percent,
        {{ cast_numeric('customer_rating') }} as customer_rating,
        {{ cast_integer('total_ratings') }} as total_ratings,
        renewal_probability,
        {{ cast_integer('competitor_contracts') }} as competitor_contracts,
        market_segment,
        industry_vertical,
        customer_size,
        {{ cast_integer('customer_tenure_years') }} as customer_tenure_years,
        contract_notes,
        risk_level,
        renewal_strategy,
        upsell_opportunities,
        cross_sell_opportunities,
        {{ cast_integer('contract_amendments') }} as contract_amendments,
        {{ cast_date('last_amendment_date') }} as last_amendment_date,
        {{ cast_date('next_review_date') }} as next_review_date,
        {{ cast_date('created_date') }} as created_date,
        {{ cast_date('updated_date') }} as updated_date,
        created_by,
        updated_by

    from source

)

select * from renamed
