with source as (

    {#-
    Normally we would select from the table here, but we are using seeds to load
    our data in this project
    #}
    select * from {{ ref('raw_service_contracts') }}

),

renamed as (

    select
        contract_id,
        contract_number,
        building_id::integer as building_id,
        customer_id::integer as customer_id,
        contract_name,
        contract_type,
        service_level,
        coverage_scope,
        start_date::date as start_date,
        end_date::date as end_date,
        contract_term_months::integer as contract_term_months,
        status,
        payment_terms,
        payment_frequency,
        billing_cycle_day::integer as billing_cycle_day,
        contract_value_total::numeric as contract_value_total,
        monthly_recurring_revenue::numeric as monthly_recurring_revenue,
        annual_contract_value::numeric as annual_contract_value,
        payment_status,
        invoice_count_ytd::integer as invoice_count_ytd,
        paid_invoices_ytd::integer as paid_invoices_ytd,
        overdue_invoices::integer as overdue_invoices,
        total_amount_invoiced_ytd::numeric as total_amount_invoiced_ytd,
        total_amount_paid_ytd::numeric as total_amount_paid_ytd,
        outstanding_balance::numeric as outstanding_balance,
        last_payment_date::date as last_payment_date,
        last_payment_amount::numeric as last_payment_amount,
        next_invoice_date::date as next_invoice_date,
        auto_renew::boolean as auto_renew,
        renewal_notice_days::integer as renewal_notice_days,
        price_escalation_percent::numeric as price_escalation_percent,
        price_escalation_frequency,
        discount_percent::numeric as discount_percent,
        discount_reason,
        sales_rep_id,
        account_manager_id,
        signed_date::date as signed_date,
        signed_by_customer,
        signed_by_vendor,
        contract_file_url,
        response_time_sla_minutes::integer as response_time_sla_minutes,
        resolution_time_sla_hours::numeric as resolution_time_sla_hours,
        first_time_fix_sla_percent::numeric as first_time_fix_sla_percent,
        customer_satisfaction_sla::numeric as customer_satisfaction_sla,
        availability_sla_percent::numeric as availability_sla_percent,
        uptime_guarantee_percent::numeric as uptime_guarantee_percent,
        penalty_clause::boolean as penalty_clause,
        penalty_amount_per_incident::numeric as penalty_amount_per_incident,
        max_penalty_percent::numeric as max_penalty_percent,
        emergency_response_included::boolean as emergency_response_included,
        after_hours_included::boolean as after_hours_included,
        weekend_coverage_included::boolean as weekend_coverage_included,
        holiday_coverage_included::boolean as holiday_coverage_included,
        parts_included::boolean as parts_included,
        labor_included::boolean as labor_included,
        travel_included::boolean as travel_included,
        prevantive_maintenance_included::boolean as prevantive_maintenance_included,
        pm_frequency_months::integer as pm_frequency_months,
        pm_visits_per_year::integer as pm_visits_per_year,
        equipment_covered_count::integer as equipment_covered_count,
        equipment_types_covered,
        buildings_covered_count::integer as buildings_covered_count,
        service_area_miles::integer as service_area_miles,
        priority_service::boolean as priority_service,
        dedicated_technician::boolean as dedicated_technician,
        escalation_contact_name,
        escalation_contact_phone,
        total_work_orders_ytd::integer as total_work_orders_ytd,
        completed_work_orders_ytd::integer as completed_work_orders_ytd,
        open_work_orders::integer as open_work_orders,
        cancelled_work_orders::integer as cancelled_work_orders,
        emergency_calls_ytd::integer as emergency_calls_ytd,
        response_time_met_percent::numeric as response_time_met_percent,
        resolution_time_met_percent::numeric as resolution_time_met_percent,
        first_time_fix_rate::numeric as first_time_fix_rate,
        customer_satisfaction_score::numeric as customer_satisfaction_score,
        sla_compliance_score::numeric as sla_compliance_score,
        penalties_assessed_ytd::integer as penalties_assessed_ytd,
        penalty_amount_ytd::numeric as penalty_amount_ytd,
        warranty_claims_ytd::integer as warranty_claims_ytd,
        total_labor_hours_ytd::numeric as total_labor_hours_ytd,
        total_parts_cost_ytd::numeric as total_parts_cost_ytd,
        total_service_cost_ytd::numeric as total_service_cost_ytd,
        profitability_percent::numeric as profitability_percent,
        customer_rating::numeric as customer_rating,
        total_ratings::integer as total_ratings,
        renewal_probability,
        competitor_contracts::integer as competitor_contracts,
        market_segment,
        industry_vertical,
        customer_size,
        customer_tenure_years::integer as customer_tenure_years,
        contract_notes,
        risk_level,
        renewal_strategy,
        upsell_opportunities,
        cross_sell_opportunities,
        contract_amendments::integer as contract_amendments,
        last_amendment_date::date as last_amendment_date,
        next_review_date::date as next_review_date,
        created_date::date as created_date,
        updated_date::date as updated_date,
        created_by,
        updated_by

    from source

)

select * from renamed

