with source as (

    {#-
    Normally we would select from the table here, but we are using seeds to load
    our data in this project
    #}
    select * from {{ ref('raw_parts') }}

),

renamed as (

    select
        part_id,
        part_number,
        part_name,
        part_category,
        part_subcategory,
        manufacturer,
        manufacturer_part_number,
        supplier,
        supplier_part_number,
        part_description,
        unit_of_measure,
        {{ cast_numeric('unit_cost') }} as unit_cost,
        {{ cast_numeric('retail_price') }} as retail_price,
        {{ cast_numeric('markup_percent') }} as markup_percent,
        {{ cast_integer('stock_quantity') }} as stock_quantity,
        {{ cast_integer('reorder_point') }} as reorder_point,
        {{ cast_integer('reorder_quantity') }} as reorder_quantity,
        {{ cast_integer('max_stock_level') }} as max_stock_level,
        {{ cast_integer('min_stock_level') }} as min_stock_level,
        stock_status,
        warehouse_location,
        bin_location,
        {{ cast_date('last_restock_date') }} as last_restock_date,
        {{ cast_date('next_restock_date') }} as next_restock_date,
        {{ cast_integer('lead_time_days') }} as lead_time_days,
        {{ cast_integer('quantity_on_order') }} as quantity_on_order,
        supplier_order_number,
        {{ cast_date('expected_delivery_date') }} as expected_delivery_date,
        {{ cast_integer('total_quantity_used_ytd') }} as total_quantity_used_ytd,
        {{ cast_integer('total_quantity_used_last_month') }} as total_quantity_used_last_month,
        {{ cast_numeric('average_monthly_usage') }} as average_monthly_usage,
        usage_trend,
        {{ cast_integer('stockout_incidents_ytd') }} as stockout_incidents_ytd,
        {{ cast_date('last_stockout_date') }} as last_stockout_date,
        compatible_equipment_types,
        {{ cast_boolean('critical_part') }} as critical_part,
        {{ cast_boolean('seasonal_demand') }} as seasonal_demand,
        {{ cast_numeric('weight_lbs') }} as weight_lbs,
        dimensions_inches,
        {{ cast_boolean('hazmat') }} as hazmat,
        hazmat_class,
        {{ cast_integer('shelf_life_months') }} as shelf_life_months,
        {{ cast_boolean('temperature_controlled') }} as temperature_controlled,
        {{ cast_integer('warranty_months') }} as warranty_months,
        {{ cast_boolean('returnable') }} as returnable,
        part_condition,
        quality_grade,
        {{ cast_boolean('inspection_required') }} as inspection_required,
        {{ cast_date('last_inspection_date') }} as last_inspection_date,
        {{ cast_boolean('certification_required') }} as certification_required,
        certifications,
        {{ cast_boolean('eco_friendly') }} as eco_friendly,
        {{ cast_integer('recycled_content_percent') }} as recycled_content_percent,
        {{ cast_boolean('energy_star_rated') }} as energy_star_rated,
        country_of_origin,
        tariff_code,
        {{ cast_numeric('import_duty_percent') }} as import_duty_percent,
        substitute_part_ids,
        {{ cast_integer('superseded_by_part_id') }} as superseded_by_part_id,
        {{ cast_boolean('obsolete') }} as obsolete,
        discontinuation_date,
        {{ cast_numeric('total_value_in_stock') }} as total_value_in_stock,
        {{ cast_numeric('inventory_turnover_ratio') }} as inventory_turnover_ratio,
        {{ cast_integer('days_in_inventory') }} as days_in_inventory,
        {{ cast_numeric('carrying_cost_annual') }} as carrying_cost_annual,
        {{ cast_numeric('storage_cost_monthly') }} as storage_cost_monthly,
        {{ cast_numeric('insurance_value') }} as insurance_value,
        {{ cast_numeric('shrinkage_rate_percent') }} as shrinkage_rate_percent,
        {{ cast_numeric('damage_rate_percent') }} as damage_rate_percent,
        {{ cast_integer('work_orders_used_count') }} as work_orders_used_count,
        {{ cast_integer('average_install_time_minutes') }} as average_install_time_minutes,
        skill_level_required,
        tools_required,
        installation_notes,
        {{ cast_integer('maintenance_interval_months') }} as maintenance_interval_months,
        {{ cast_numeric('failure_rate_percent') }} as failure_rate_percent,
        {{ cast_integer('mtbf_hours') }} as mtbf_hours,
        {{ cast_integer('warranty_claims_ytd') }} as warranty_claims_ytd,
        {{ cast_numeric('return_rate_percent') }} as return_rate_percent,
        {{ cast_numeric('customer_rating') }} as customer_rating,
        {{ cast_integer('total_ratings') }} as total_ratings,
        {{ cast_numeric('supplier_rating') }} as supplier_rating,
        {{ cast_numeric('supplier_lead_time_reliability') }} as supplier_lead_time_reliability,
        price_trend_3month,
        price_volatility,
        {{ cast_boolean('contract_pricing') }} as contract_pricing,
        {{ cast_boolean('volume_discount_available') }} as volume_discount_available,
        {{ cast_integer('bulk_order_minimum') }} as bulk_order_minimum,
        image_url,
        datasheet_url,
        video_tutorial_url,
        {{ cast_date('last_price_update') }} as last_price_update,
        {{ cast_date('next_price_review') }} as next_price_review,
        {{ cast_date('created_date') }} as created_date,
        {{ cast_date('updated_date') }} as updated_date,
        created_by,
        updated_by,
        notes

    from source

)

select * from renamed
