import { FieldType, PivotData } from '@lightdash/common';

const pivot3: PivotData = {
    headerValueTypes: [],
    headerValues: [],

    indexValueTypes: [
        {
            type: FieldType.DIMENSION,
            fieldId: 'orders_status',
        },
        {
            type: FieldType.DIMENSION,
            fieldId: 'payments_payment_method',
        },
        { type: FieldType.METRIC },
    ],

    indexValues: [
        ['completed', 'bank_transfer', 'Unique orders count'],
        ['completed', 'bank_transfer', 'Average Order Size'],
        ['completed', 'coupon', 'Unique orders count'],
        ['completed', 'coupon', 'Average Order Size'],
        ['completed', 'credit_card', 'Unique orders count'],
        ['completed', 'credit_card', 'Average Order Size'],
        ['completed', 'gift_card', 'Unique orders count'],
        ['completed', 'gift_card', 'Average Order Size'],

        ['placed', 'bank_transfer', 'Unique orders count'],
        ['placed', 'bank_transfer', 'Average Order Size'],
        ['placed', 'coupon', 'Unique orders count'],
        ['placed', 'coupon', 'Average Order Size'],
        ['placed', 'credit_card', 'Unique orders count'],
        ['placed', 'credit_card', 'Average Order Size'],
        ['placed', 'gift_card', 'Unique orders count'],
        ['placed', 'gift_card', 'Average Order Size'],

        ['return_pending', 'bank_transfer', 'Unique orders count'],
        ['return_pending', 'bank_transfer', 'Average Order Size'],
        ['return_pending', 'coupon', 'Unique orders count'],
        ['return_pending', 'coupon', 'Average Order Size'],
        ['return_pending', 'credit_card', 'Unique orders count'],
        ['return_pending', 'credit_card', 'Average Order Size'],
        ['return_pending', 'gift_card', 'Unique orders count'],
        ['return_pending', 'gift_card', 'Average Order Size'],

        ['returned', 'bank_transfer', 'Unique orders count'],
        ['returned', 'bank_transfer', 'Average Order Size'],
        ['returned', 'coupon', 'Unique orders count'],
        ['returned', 'coupon', 'Average Order Size'],
        ['returned', 'credit_card', 'Unique orders count'],
        ['returned', 'credit_card', 'Average Order Size'],
        ['returned', 'gift_card', 'Unique orders count'],
        ['returned', 'gift_card', 'Average Order Size'],

        ['shipped', 'bank_transfer', 'Unique orders count'],
        ['shipped', 'bank_transfer', 'Average Order Size'],
        ['shipped', 'coupon', 'Unique orders count'],
        ['shipped', 'coupon', 'Average Order Size'],
        ['shipped', 'credit_card', 'Unique orders count'],
        ['shipped', 'credit_card', 'Average Order Size'],
        ['shipped', 'gift_card', 'Unique orders count'],
        ['shipped', 'gift_card', 'Average Order Size'],
    ],

    rows: [
        [7],
        [14.86],
        [4],
        [20],
        [9],
        [14.3],
        [2],
        [13.5],
        [8],
        [9.25],
        [2],
        [24.5],
        [10],
        [23.73],
        [4],
        [29],
        [4],
        [27.25],
        [3],
        [25.67],
        [12],
        [20.62],
        [2],
        [12],
        [7],
        [13.71],
        [2],
        [9],
        [10],
        [19],
        [2],
        [15.5],
        [7],
        [19],
        [2],
        [12],
        [10],
        [18.91],
        [2],
        [25.5],
    ],

    rowTotals: [],
    columnTotals: [],
};

export { pivot3 };
