import { describeContentAsCodeSchemaContract } from './schemaContractTestUtils';

describeContentAsCodeSchemaContract({
    resource: 'virtual_view',
    modelSchema: 'Explore',
    documentSchema: 'VirtualViewAsCode',
    skippedModelFields: [
        'aiHint',
        'baseTable',
        'caseSensitive',
        'customMeta',
        'databricksCompute',
        'externalSource',
        'granularityLabels',
        'groupLabel',
        'groups',
        'joinedTables',
        'label',
        'preAggregateSource',
        'preAggregates',
        'savedParameterValues',
        'spotlight',
        'sqlPath',
        'tables',
        'tags',
        'targetDatabase',
        'type',
        'unfilteredTables',
        'warehouse',
        'warnings',
        'ymlPath',
    ],
    documentOnlyFields: [
        'columns',
        // The portable name of the connection the view runs on.
        'connectionName',
        'contentType',
        'slug',
        'sql',
        'version',
    ],
});
