import os, pandas as pd, numpy as np
SP=os.environ.get('AI_SPIKE_DIR', '.')
p=pd.read_csv(SP+'/prompts.csv', low_memory=False)
pr=pd.read_csv(SP+'/projects.csv'); ag=pd.read_csv(SP+'/agents.csv'); org=pd.read_csv(SP+'/orgs.csv')
p['ts']=pd.to_datetime(p['ts']); p['next_prompt_ts']=pd.to_datetime(p['next_prompt_ts'])
p['tool_seq']=p['tool_seq'].fillna(''); p['n_tools']=p['n_tools'].fillna(0)
p['pos']=((p['max_score']==1)|(p['chart_created'].fillna(0)>0)|(p['chart_explored'].fillna(0)>0)).astype(int)
p['neg']=((p['min_score']==-1)&(p['pos']==0)).astype(int)
p['labelled']=((p['pos']==1)|(p['neg']==1)).astype(int)
p['thumb_up']=(p['max_score']==1).astype(int); p['thumb_down']=(p['min_score']==-1).astype(int)
p['chart_action']=((p['chart_created'].fillna(0)>0)|(p['chart_explored'].fillna(0)>0)).astype(int)
p['reask_2m']=((p['next_prompt_ts']-p['ts']).dt.total_seconds()<120).fillna(False).astype(int)
def has(pat): return p['tool_seq'].str.contains(pat, regex=True).astype(int)
p['viz']=has(r'generateVisualization'); p['viz_n']=p['tool_seq'].str.count('generateVisualization')
p['search']=has(r'grepFields|discoverFields|searchSemanticLayer|findExplores'); p['metadata']=has(r'getMetadata')
p['values']=has(r'searchFieldValues'); p['sql']=has(r'runSql|runQuery|listWarehouseTables|describeWarehouseTable')
p['content']=has(r'findContent|readContent|runSavedChart|runContentQuery|listContent|getDashboardCharts')
p['knowledge']=has(r'nowledgeDocument'); p['skill']=has(r'loadSkill'); p['projctx']=has(r'loadProjectContext')
p['repo']=has(r'exploreRepo|editDbtProject|repoShell|discoverRepos'); p['dash']=has(r'generateDashboard')
p['no_tools']=(p['n_tools']==0).astype(int)
p['first_tool']=p['tool_seq'].str.split('>').str[0].replace('', 'none')
p=p.merge(pr.drop(columns=['organization_id']), on='project_id', how='left')
p=p.merge(ag[['ai_agent_id','tags_count','integrations_count','memory_generated','memory_cited']], on='ai_agent_id', how='left')
p=p.merge(org, on='organization_id', how='left')
p['metrics_per_model']=p['metrics_count']/p['models_count'].replace(0,np.nan)
p['fmt_ratio']=p['formatted_fields_count']/p['metrics_count'].replace(0,np.nan)
p['scoped']=(p['tags_count'].fillna(0)>0).astype(int); p['memory']=(p['memory_generated'].fillna(0)>0).astype(int)
p['slack']=(p['prompt_context']=='slack').astype(int)
p['own_key']=(p['key_management'].fillna('').str.contains('own|customer|self|user', case=False)).astype(int)
p['reasoning']=(p['reasoning_tokens'].fillna(0)>0).astype(int)
p.to_pickle(SP+'/p.pkl')
print('prompts',len(p),'threads',p.thread_id.nunique(),'orgs',p.organization_id.nunique(),'agents',p.ai_agent_id.nunique(),'users',p.user_id.nunique())
print('with tools',(p.n_tools>0).mean().round(3),'with token rows',p.model.notna().mean().round(3),'with project features',p.metrics_count.notna().mean().round(3),'with agent features',p.tags_count.notna().mean().round(3))
print('label rates: pos',p.pos.mean().round(4),'neg',p.neg.mean().round(4),'thumb_up',p.thumb_up.mean().round(4),'thumb_down',p.thumb_down.mean().round(4),'chart_action',p.chart_action.mean().round(4),'labelled',p.labelled.mean().round(4))
print('context', p.prompt_context.value_counts(dropna=False).to_dict())
print('feature', p.feature.value_counts(dropna=False).head(8).to_dict())
print('model', p.model.value_counts(dropna=False).head(10).to_dict())
print('provider', p.provider.value_counts(dropna=False).head(6).to_dict())
print('key_management', p.key_management.value_counts(dropna=False).head(5).to_dict())
print('n_tools quantiles', p.n_tools.quantile([.25,.5,.75,.9,.99]).to_dict())
print('org type', p.organization_type.value_counts(dropna=False).to_dict(), 'paying', p.is_paying.value_counts(dropna=False).to_dict())
oc=p.groupby('organization_id').size().sort_values(ascending=False); print('top10 orgs share of prompts', round(oc.head(10).sum()/oc.sum(),3), 'orgs>=100 prompts', (oc>=100).sum(), 'orgs>=30', (oc>=30).sum())
print('first tool', p.first_tool.value_counts().head(8).to_dict())
