name: Cleanup Preview Environment

on:
  pull_request:
    types:
      - closed

permissions:
  deployments: write
  contents: read

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
      - name: Context
        uses: okteto/context@5212ce5ebf9d3584bafd33f4a295a8521fc5abe7 # latest
        with:
          url: ${{secrets.OKTETO_CONTEXT}}
          token: ${{ secrets.OKTETO_TOKEN }}

      # Ideally would clean up deployment status
      # but unsure how to obtain the environment id from
      # the preview.yml workflow

      - name: Destroy preview environment
        uses: okteto/destroy-preview@f1897ba6c598f134ced128fb01c56ff5e9c92f73 # latest
        with:
          name: pr-${{ github.event.number }} 